import { ShoppingCart } from 'lucide-react';
import type { ModuleDef } from '../../types';

export const salesModule: ModuleDef = {
  id: 'sales',
  name: 'Sales & Orders',
  nameKey: 'modules.sales.name',
  nameAr: 'المبيعات والطلبات',
  description: 'Manage orders, POS checkout, abandoned carts, and sales transactions.',
  descriptionKey: 'modules.sales.description',
  descriptionAr: 'إدارة الطلبات، نقاط البيع، السلات المتروكة، ومعاملات البيع.',
  icon: ShoppingCart,
  category: 'operations',
  color: '#2563EB',
  dependencies: ['core'],
  features: [
    { id: 'orders', label: 'Orders', labelAr: 'الطلبات', defaultEnabled: true },
    { id: 'quotes', label: 'Quotations', labelAr: 'عروض الأسعار', defaultEnabled: false },
    { id: 'invoices', label: 'Invoices', labelAr: 'الفواتير', defaultEnabled: true },
    { id: 'payments', label: 'Payments', labelAr: 'المدفوعات', defaultEnabled: true },
    { id: 'customers', label: 'Customers', labelAr: 'العملاء', defaultEnabled: true },
    { id: 'returns', label: 'Returns', labelAr: 'المرتجعات', defaultEnabled: false },
    { id: 'loyalty', label: 'Loyalty Points', labelAr: 'نقاط الولاء', defaultEnabled: false },
    { id: 'subscriptions', label: 'Subscriptions', labelAr: 'الاشتراكات', defaultEnabled: false },
    { id: 'pos', label: 'Quick Sales (POS)', labelAr: 'المبيعات السريعة (POS)', defaultEnabled: false },
    { id: 'epayment', label: 'E-Payment', labelAr: 'الدفع الإلكتروني', defaultEnabled: false },
    { id: 'orderStatus', label: 'Order Status', labelAr: 'حالات الطلب', defaultEnabled: true },
    { id: 'abandonedCart', label: 'Abandoned Cart', labelAr: 'السلة المتروكة', defaultEnabled: true },
  ],
  pages: [
    { id: 'sales', label: 'Orders', route: '/business/dashboard?tab=sales', tabId: 'sales', existing: true },
    { id: 'pos', label: 'POS System', route: '/business/dashboard?tab=pos', tabId: 'pos', existing: true },
    { id: 'abandoned_cart', label: 'Abandoned Cart', route: '/business/dashboard?tab=abandonedCart', tabId: 'abandonedCart', existing: true },
    { id: 'quotes', label: 'Quotes', route: '/business/dashboard?tab=quotes', tabId: 'quotes' },
    { id: 'payments', label: 'Payments', route: '/business/dashboard?tab=payments', tabId: 'payments' },
    { id: 'returns', label: 'Returns', route: '/business/dashboard?tab=returns', tabId: 'returns' },
    { id: 'loyalty', label: 'Loyalty', route: '/business/dashboard?tab=loyalty', tabId: 'loyalty' },
    { id: 'subscriptions', label: 'Subscriptions', route: '/business/dashboard?tab=subscriptions', tabId: 'subscriptions' },
    { id: 'epayment', label: 'E-Payment', route: '/business/dashboard?tab=epayment', tabId: 'epayment' },
    { id: 'orderStatus', label: 'Order Status', route: '/business/dashboard?tab=orderStatus', tabId: 'orderStatus' },
  ],
  navigation: [
    {
      id: 'sales',
      title: 'Sales',
      titleKey: 'dashboard.sections.sales',
      order: 10,
      items: [
        { id: 'sales', label: 'Orders', labelKey: 'business.dashboardTabs.sales', route: '/business/dashboard?tab=sales', tabId: 'sales', icon: 'CreditCard', order: 0 },
        { id: 'abandoned_cart', label: 'Abandoned Cart', labelKey: 'business.dashboardTabs.abandonedCart', route: '/business/dashboard?tab=abandonedCart', tabId: 'abandonedCart', icon: 'ShoppingCart', order: 1 },
        { id: 'quotes', label: 'Quotes', labelKey: 'business.dashboardTabs.quotes', route: '/business/dashboard?tab=quotes', tabId: 'quotes', icon: 'FileText', order: 2 },
        { id: 'payments', label: 'Payments', labelKey: 'business.dashboardTabs.payments', route: '/business/dashboard?tab=payments', tabId: 'payments', icon: 'Wallet', order: 3 },
        { id: 'returns', label: 'Returns', labelKey: 'business.dashboardTabs.returns', route: '/business/dashboard?tab=returns', tabId: 'returns', icon: 'ArrowLeftRight', order: 4 },
        { id: 'loyalty', label: 'Loyalty Points', labelKey: 'business.dashboardTabs.loyalty', route: '/business/dashboard?tab=loyalty', tabId: 'loyalty', icon: 'Star', order: 5 },
        { id: 'subscriptions', label: 'Subscriptions', labelKey: 'business.dashboardTabs.subscriptions', route: '/business/dashboard?tab=subscriptions', tabId: 'subscriptions', icon: 'CreditCard', order: 6 },
        { id: 'pos', label: 'POS', labelKey: 'business.dashboardTabs.pos', route: '/business/dashboard?tab=pos', tabId: 'pos', icon: 'ScanLine', order: 7 },
        { id: 'epayment', label: 'E-Payment', labelKey: 'business.dashboardTabs.epayment', route: '/business/dashboard?tab=epayment', tabId: 'epayment', icon: 'CreditCard', order: 8 },
        { id: 'orderStatus', label: 'Order Status', labelKey: 'business.dashboardTabs.orderStatus', route: '/business/dashboard?tab=orderStatus', tabId: 'orderStatus', icon: 'ListChecks', order: 9 },
      ],
    },
  ],
  dashboardWidgets: [
    { id: 'recent_orders', label: 'Recent Orders', labelKey: 'modules.sales.widgetRecentOrders', component: 'RecentOrders', order: 2, size: 'medium' },
    { id: 'sales_chart', label: 'Sales Chart', labelKey: 'modules.sales.widgetSalesChart', component: 'SalesChart', order: 3, size: 'large' },
  ],
  permissions: [
    { id: 'sales.view', label: 'View Orders' },
    { id: 'sales.manage', label: 'Manage Orders' },
    { id: 'pos.use', label: 'Use POS' },
  ],
  settingsSections: [
    { id: 'sales', label: 'Sales Settings', labelKey: 'dashboard.settings.sales' },
    { id: 'pos', label: 'POS Settings', labelKey: 'dashboard.settings.pos' },
  ],
  defaultEnabled: true,
  optional: true,
  estimatedSetupMinutes: 5,
};
