import {
  LayoutDashboard,
  Bell,
  CreditCard,
  Package,
  CircleDollarSign,
  Megaphone,
  Users,
  CalendarDays,
  UserCog,
  BarChart3,
  Globe,
  Bot,
  Settings,
  Home,
  Shield,
  Store,
  Puzzle,
  LayoutGrid,
  Share2,
  TrendingDown,
  User,
  ShoppingCart,
  Printer,
  Scale,
  BookOpen,
  Wallet as WalletIcon,
  FileText,
  ShoppingBag,
  Award,
  Gift,
  Repeat,
  Calculator,
  Receipt,
  ScanBarcode,
  Clock,
  ClipboardList,
  Truck,
  FileStack,
  Warehouse,
  ArrowLeftRight,
  ReceiptText,
  Landmark,
  FileBarChart,
  Percent,
  BadgePercent,
  Ticket,
  MessageSquare,
  Sparkles,
  Target,
  Tag,
  UserRoundSearch,
  Headset,
  MessagesSquare,
  MessageCircle,
  LifeBuoy,
  Star,
  Briefcase,
  KeyRound,
  UserCheck,
  Timer,
  Coins,
  Hourglass,
  ClipboardCheck,
  PenLine,
  Palette,
  LayoutTemplate,
  Gem,
  Wand2,
  ImagePlus,
  SearchCheck,
  BrainCircuit,
  Lightbulb,
  FileSpreadsheet,
  Radar,
  Workflow,
  Boxes,
  Building2,
  GitBranch,
  UsersRound,
  FileCheck,
  PackageCheck,
  Tags,
  ScrollText,
  PiggyBank,
  ScanLine,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type SidebarItem = {
  id: string;
  label: string;
  labelAr: string;
  icon: LucideIcon;
  href: string;
  /** false = local-only / not yet released (shows a "قريباً" badge) */
  published?: boolean;
};

export type SidebarSection = {
  id: string;
  title: string;
  titleAr: string;
  moduleId?: string;
  icon?: LucideIcon;
  items: SidebarItem[];
  mainHref?: string;
  /** false = local-only / not yet released section */
  published?: boolean;
};

// Colored accent per section — used by TopNav and Sidebar so each
// section's page icons feel visually distinct.
export const SECTION_COLORS: Record<string, string> = {
  dashboard: 'text-sky-500',
  branches: 'text-blue-600',
  team: 'text-teal-600',
  sales: 'text-emerald-500',
  pos: 'text-lime-600',
  inventory: 'text-amber-500',
  finance: 'text-teal-500',
  accounting: 'text-indigo-500',
  marketing: 'text-rose-500',
  customers: 'text-cyan-600',
  crm: 'text-violet-500',
  bookings: 'text-pink-500',
  hr: 'text-orange-500',
  website: 'text-blue-500',
  analytics: 'text-fuchsia-500',
  ai: 'text-purple-500',
  settings: 'text-slate-500',
};

// Market-launch switch: items/sections marked `published: false` are hidden
// from merchants in production builds and stay visible on local/dev machines
// so the team can keep working on them before release.
export const HIDE_UNPUBLISHED = process.env.NODE_ENV === 'production';

export const sidebarSections: SidebarSection[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    titleAr: 'الرئيسية',
    items: [
      {
        id: 'overview',
        label: 'Overview',
        labelAr: 'نظرة عامة',
        icon: LayoutDashboard,
        href: '/dashboard',
      },
      {
        id: 'notifications',
        label: 'Notifications',
        labelAr: 'الإشعارات',
        icon: Bell,
        href: '/dashboard/notifications',
      },
      {
        id: 'dashboardSettings',
        label: 'Dashboard Settings',
        labelAr: 'إعدادات الإشعارات',
        icon: Settings,
        href: '/dashboard/settings?tab=notifications&from=dashboard',
      },
    ],
  },
  {
    id: 'website',
    title: 'Website',
    titleAr: 'الموقع الإلكتروني',
    moduleId: 'website',
    icon: Globe,
    mainHref: '/dashboard/website/themes',
    items: [
      {
        id: 'website_themes',
        label: 'Themes',
        labelAr: 'قوالب الثيمات',
        icon: LayoutTemplate,
        href: '/dashboard/website/themes',
      },
      {
        id: 'website_builder',
        label: 'Website Builder',
        labelAr: 'مُنشئ الموقع',
        icon: Globe,
        href: '/dashboard/website',
      },
      {
        id: 'websiteSettings',
        label: 'Website Settings',
        labelAr: 'إعدادات الموقع',
        icon: Settings,
        href: '/dashboard/settings?tab=store&from=website',
      },
    ],
  },
  {
    id: 'sales',
    title: 'Sales',
    titleAr: 'المبيعات',
    moduleId: 'sales',
    icon: CreditCard,
    items: [
      {
        id: 'sales',
        label: 'Orders',
        labelAr: 'الطلبات',
        icon: ShoppingCart,
        href: '/dashboard/sales',
      },
      {
        id: 'salesOrders',
        published: false,
        label: 'Sales Orders',
        labelAr: 'أوامر البيع',
        icon: FileCheck,
        href: '/dashboard/sales/orders',
      },
      {
        id: 'deliveryNotes',
        published: false,
        label: 'Delivery Notes',
        labelAr: 'أوراق الصرف',
        icon: PackageCheck,
        href: '/dashboard/sales/delivery-notes',
      },
      {
        id: 'quotes',
        published: false,
        label: 'Quotes',
        labelAr: 'عروض الأسعار',
        icon: FileText,
        href: '/dashboard/sales/quotes',
      },
      {
        id: 'abandonedCart',
        published: false,
        label: 'Abandoned Carts',
        labelAr: 'السلات المتروكة',
        icon: ShoppingBag,
        href: '/dashboard/sales/abandoned-cart',
      },
      {
        id: 'loyalty',
        published: false,
        label: 'Loyalty Points',
        labelAr: 'نقاط الولاء',
        icon: Award,
        href: '/dashboard/sales/loyalty',
      },
      {
        id: 'loyaltyCard',
        published: false,
        label: 'Loyalty Card',
        labelAr: 'بطاقة الولاء',
        icon: Gift,
        href: '/dashboard/sales/loyalty-card',
      },
      {
        id: 'subscriptions',
        published: false,
        label: 'Subscriptions',
        labelAr: 'الاشتراكات',
        icon: Repeat,
        href: '/dashboard/sales/subscriptions',
      },
      {
        id: 'epayment',
        published: false,
        label: 'E-Payment',
        labelAr: 'الدفع الإلكتروني',
        icon: CreditCard,
        href: '/dashboard/sales/epayment',
      },
      {
        id: 'salesSettings',
        label: 'Order Settings',
        labelAr: 'إعدادات الطلبات',
        icon: Settings,
        href: '/dashboard/settings?tab=orders_settings&from=sales',
      },
    ],
  },
  {
    id: 'pos',
    title: 'POS / Cashier',
    titleAr: 'الكاشير',
    moduleId: 'pos',
    icon: Calculator,
    mainHref: '/dashboard/pos',
    items: [
      {
        id: 'posCheckout',
        label: 'Cashier',
        labelAr: 'الكاشير',
        icon: ScanBarcode,
        href: '/dashboard/pos',
      },
      {
        id: 'posShifts',
        label: 'Shifts',
        labelAr: 'الورديات',
        icon: Clock,
        href: '/dashboard/pos/shifts',
      },
      {
        id: 'posSettings',
        label: 'POS Settings',
        labelAr: 'إعدادات الكاشير',
        icon: Settings,
        href: '/dashboard/settings?tab=pos_settings&from=pos',
      },
      {
        id: 'posReports',
        label: 'POS Reports',
        labelAr: 'تقارير الكاشير',
        icon: BarChart3,
        href: '/dashboard/pos/reports',
      },
    ],
  },
  {
    id: 'inventory',
    title: 'Inventory',
    titleAr: 'المخزون',
    moduleId: 'inventory',
    icon: Package,
    items: [
      {
        id: 'inventoryOverview',
        label: 'Inventory',
        labelAr: 'المخزون',
        icon: Package,
        href: '/dashboard/inventory',
      },
      {
        id: 'products',
        label: 'Products',
        labelAr: 'المنتجات',
        icon: Boxes,
        href: '/dashboard/inventory/products',
      },
      {
        id: 'purchaseOrders',
        label: 'Purchase Orders',
        labelAr: 'أوامر الشراء',
        icon: FileStack,
        href: '/dashboard/inventory/purchase-orders',
      },
      {
        id: 'warehouses',
        label: 'Warehouses',
        labelAr: 'المخازن',
        icon: Warehouse,
        href: '/dashboard/inventory/warehouses',
      },
      {
        id: 'stocktake',
        label: 'Stock Take',
        labelAr: 'جرد المخزون',
        icon: ClipboardList,
        href: '/dashboard/inventory/stocktake',
      },
      {
        id: 'suppliers',
        label: 'Suppliers',
        labelAr: 'الموردون',
        icon: Truck,
        href: '/dashboard/inventory/suppliers',
      },
      // ملاحظة: الفئات/المتغيرات/الباركود تبويبات داخل المنتجات، والنقل والحركات
      // تبويبات داخل المخازن، وتتبع الكميات وتنبيهات النفاد تبويبات داخل المخزون.
      // القاعدة: الوظيفة الكبيرة = صفحة، التابعة = تبويب، العملية = إجراء داخل الصفحة.
      {
        id: 'inventorySettings',
        label: 'Inventory Settings',
        labelAr: 'إعدادات المخزون',
        icon: Settings,
        href: '/dashboard/settings?tab=inventory_settings&from=inventory',
      },
    ],
  },
  {
    id: 'branches',
    published: false,
    title: 'Branches',
    titleAr: 'الفروع',
    moduleId: 'branches',
    icon: Building2,
    items: [
      {
        id: 'branchesList',
        label: 'Branches',
        labelAr: 'إدارة الفروع',
        icon: Building2,
        href: '/dashboard/branches',
      },
      {
        id: 'branchCompare',
        label: 'Branch Comparison',
        labelAr: 'مقارنة الفروع',
        icon: GitBranch,
        href: '/dashboard/branches/compare',
      },
      {
        id: 'branchesSettings',
        label: 'Branches Settings',
        labelAr: 'إعدادات الفروع',
        icon: Settings,
        href: '/dashboard/settings?tab=branches_settings&from=branches',
      },
    ],
  },
  {
    id: 'finance',
    title: 'Finance',
    titleAr: 'المالية',
    moduleId: 'finance',
    icon: CircleDollarSign,
    items: [
      {
        id: 'invoice',
        label: 'Invoices',
        labelAr: 'الفواتير',
        icon: ReceiptText,
        href: '/dashboard/finance',
      },
      {
        id: 'collections',
        label: 'Collections & Payments',
        labelAr: 'التحصيلات والمدفوعات',
        icon: ArrowLeftRight,
        href: '/dashboard/finance/collections',
      },
      {
        id: 'wallets',
        label: 'Cash, Banks & Wallets',
        labelAr: 'النقدية والبنوك والمحافظ',
        icon: WalletIcon,
        href: '/dashboard/finance/wallets',
      },
      {
        id: 'expenses',
        label: 'Expenses',
        labelAr: 'المصروفات',
        icon: TrendingDown,
        href: '/dashboard/finance/expenses',
      },
      {
        id: 'receivables',
        label: 'Customers & Debtors',
        labelAr: 'العملاء والمدينون',
        icon: Users,
        href: '/dashboard/finance/receivables',
      },
      {
        id: 'payables',
        label: 'Suppliers & Creditors',
        labelAr: 'الموردون والدائنون',
        icon: Truck,
        href: '/dashboard/finance/payables',
      },
      {
        id: 'settlements',
        label: 'Financial Reconciliations',
        labelAr: 'التسويات المالية',
        icon: Scale,
        href: '/dashboard/finance/settlements',
      },
      {
        id: 'eta',
        published: false,
        label: 'E-Invoice (ETA)',
        labelAr: 'الفاتورة الإلكترونية',
        icon: ScanLine,
        href: '/dashboard/finance/eta',
      },
      {
        id: 'financeSettings',
        label: 'Finance Settings',
        labelAr: 'إعدادات المالية',
        icon: Settings,
        href: '/dashboard/settings?tab=payments&from=finance',
      },
    ],
  },
  {
    id: 'accounting',
    published: false,
    title: 'Accounting',
    titleAr: 'المحاسبة',
    moduleId: 'accounting',
    icon: BookOpen,
    items: [
      {
        id: 'accounts',
        label: 'Chart of Accounts',
        labelAr: 'دليل الحسابات',
        icon: Landmark,
        href: '/dashboard/finance/accounts',
      },
      {
        id: 'journal',
        label: 'Journal Entries',
        labelAr: 'القيود المحاسبية',
        icon: BookOpen,
        href: '/dashboard/finance/journal',
      },
      {
        id: 'ledger',
        label: 'General Ledger',
        labelAr: 'دفتر الأستاذ',
        icon: BookOpen,
        href: '/dashboard/finance/ledger',
      },
      {
        id: 'trialBalance',
        label: 'Trial Balance',
        labelAr: 'ميزان المراجعة',
        icon: Scale,
        href: '/dashboard/finance/trial-balance',
      },
      {
        id: 'financialReports',
        label: 'Financial Statements',
        labelAr: 'القوائم المالية',
        icon: FileBarChart,
        href: '/dashboard/finance/financial-reports',
      },
      {
        id: 'taxes',
        label: 'Taxes',
        labelAr: 'الضرائب',
        icon: Percent,
        href: '/dashboard/finance/taxes',
      },
      {
        id: 'accountingSettings',
        label: 'Accounting Settings',
        labelAr: 'إعدادات المحاسبة',
        icon: Settings,
        href: '/dashboard/settings?tab=accounting_settings&from=accounting',
      },
    ],
  },
  {
    id: 'team',
    published: false,
    title: 'Team',
    titleAr: 'فريق العمل',
    moduleId: 'team',
    icon: UsersRound,
    items: [
      {
        id: 'teamMembers',
        label: 'Team Members',
        labelAr: 'المستخدمون',
        icon: UsersRound,
        href: '/dashboard/team',
      },
      {
        id: 'teamRoles',
        label: 'Roles & Permissions',
        labelAr: 'الأدوار والصلاحيات',
        icon: KeyRound,
        href: '/dashboard/team/roles',
      },
    ],
  },
  {
    id: 'marketing',
    title: 'Marketing',
    titleAr: 'التسويق',
    moduleId: 'marketing',
    icon: Megaphone,
    items: [
      {
        id: 'marketingHub',
        label: 'Marketing Hub',
        labelAr: 'مركز التسويق',
        icon: Target,
        href: '/dashboard/marketing',
      },
      {
        id: 'campaigns',
        label: 'Campaigns',
        labelAr: 'الحملات',
        icon: Megaphone,
        href: '/dashboard/marketing/campaigns',
      },
      {
        id: 'offers',
        label: 'Offers & Discounts',
        labelAr: 'العروض والخصومات',
        icon: BadgePercent,
        href: '/dashboard/marketing/offers',
      },
      {
        id: 'messages',
        label: 'Messages',
        labelAr: 'الرسائل والتواصل',
        icon: MessageSquare,
        href: '/dashboard/marketing/messages',
      },
      {
        id: 'loyaltyPrograms',
        label: 'Loyalty Programs',
        labelAr: 'برامج الولاء',
        icon: Sparkles,
        href: '/dashboard/marketing/loyalty-programs',
      },
      {
        id: 'marketingSettings',
        label: 'Marketing Settings',
        labelAr: 'إعدادات التسويق',
        icon: Settings,
        href: '/dashboard/settings?tab=social_media&from=marketing',
      },
    ],
  },
  {
    id: 'customers',
    title: 'Customers',
    titleAr: 'العملاء',
    moduleId: 'customers',
    icon: Users,
    items: [
      {
        id: 'customers',
        label: 'Customers',
        labelAr: 'العملاء',
        icon: Users,
        href: '/dashboard/customers',
      },
      {
        id: 'customerStatements',
        label: 'Statements',
        labelAr: 'كشوف الحساب',
        icon: ScrollText,
        href: '/dashboard/customers/statements',
      },
      {
        id: 'creditLimits',
        label: 'Credit Limits',
        labelAr: 'حدود الائتمان',
        icon: PiggyBank,
        href: '/dashboard/customers/credit-limits',
      },
      {
        id: 'wholesalePricing',
        published: false,
        label: 'Wholesale Pricing',
        labelAr: 'أسعار الجملة',
        icon: Tags,
        href: '/dashboard/customers/wholesale-pricing',
      },
      {
        id: 'customerSegments',
        label: 'Segments',
        labelAr: 'الشرائح',
        icon: UserRoundSearch,
        href: '/dashboard/customers/segments',
      },
      {
        id: 'customerTags',
        label: 'Tags',
        labelAr: 'الوسوم',
        icon: Tag,
        href: '/dashboard/customers/tags',
      },
      {
        id: 'loyaltyProgram',
        label: 'Loyalty & Rewards',
        labelAr: 'الولاء والمكافآت',
        icon: Award,
        href: '/dashboard/customers/loyalty',
      },
      {
        id: 'customersSettings',
        label: 'Customer Settings',
        labelAr: 'إعدادات العملاء',
        icon: Settings,
        href: '/dashboard/settings?tab=customers_settings&from=customers',
      },
    ],
  },
  {
    id: 'crm',
    published: false,
    title: 'Customer Service',
    titleAr: 'خدمة العملاء',
    moduleId: 'crm',
    icon: Headset,
    mainHref: '/dashboard/crm',
    items: [
      {
        id: 'chats',
        label: 'Chats',
        labelAr: 'المحادثات',
        icon: MessagesSquare,
        href: '/dashboard/crm/chats',
      },
      {
        id: 'tickets',
        label: 'Tickets',
        labelAr: 'التذاكر',
        icon: Ticket,
        href: '/dashboard/crm/tickets',
      },
      {
        id: 'complaints',
        label: 'Complaints',
        labelAr: 'الشكاوى',
        icon: LifeBuoy,
        href: '/dashboard/crm/complaints',
      },
      {
        id: 'reviews',
        label: 'Reviews',
        labelAr: 'التقييمات',
        icon: Star,
        href: '/dashboard/crm/reviews',
      },
      {
        id: 'crmSettings',
        label: 'Customer Service Settings',
        labelAr: 'إعدادات خدمة العملاء',
        icon: Settings,
        href: '/dashboard/settings?tab=crm_settings&from=crm',
      },
    ],
  },
  {
    id: 'bookings',
    title: 'Booking Management',
    titleAr: 'الحجوزات',
    moduleId: 'bookings',
    icon: CalendarDays,
    mainHref: '/dashboard/bookings',
    items: [
      {
        id: 'bookingsSchedule',
        label: 'Bookings Schedule',
        labelAr: 'مواعيد الحجوزات',
        icon: CalendarDays,
        href: '/dashboard/bookings',
      },
      {
        id: 'bookingsSettings',
        label: 'Settings',
        labelAr: 'الإعدادات',
        icon: Settings,
        href: '/dashboard/settings?tab=booking_settings&from=bookings',
      },
    ],
  },
  {
    id: 'hr',
    published: true,
    title: 'Human Resources',
    titleAr: 'الموارد البشرية',
    moduleId: 'hr',
    icon: UserCog,
    items: [
      {
        id: 'employees',
        label: 'Employees',
        labelAr: 'الموظفين',
        icon: Briefcase,
        href: '/dashboard/hr',
      },
      {
        id: 'permissions',
        label: 'Permissions',
        labelAr: 'الصلاحيات',
        icon: KeyRound,
        href: '/dashboard/hr/permissions',
      },
      {
        id: 'attendance',
        label: 'Attendance',
        labelAr: 'الحضور',
        icon: UserCheck,
        href: '/dashboard/hr/attendance',
      },
      {
        id: 'checkout',
        label: 'Check-out',
        labelAr: 'الانصراف',
        icon: Timer,
        href: '/dashboard/hr/check-out',
      },
      {
        id: 'payroll',
        label: 'Payroll',
        labelAr: 'الرواتب',
        icon: Coins,
        href: '/dashboard/hr/payroll',
      },
      {
        id: 'leaves',
        label: 'Leaves',
        labelAr: 'الإجازات',
        icon: Hourglass,
        href: '/dashboard/hr/leaves',
      },
      {
        id: 'tasks',
        label: 'Tasks',
        labelAr: 'المهام',
        icon: ClipboardCheck,
        href: '/dashboard/hr/tasks',
      },
      {
        id: 'hrSettings',
        label: 'Team Settings',
        labelAr: 'إعدادات الفريق',
        icon: Settings,
        href: '/dashboard/settings?tab=hr_settings&from=hr',
      },
    ],
  },
  {
    id: 'analytics',
    title: 'Analytics',
    titleAr: 'التحليلات',
    moduleId: 'analytics',
    icon: BarChart3,
    mainHref: '/dashboard/analytics/reports',
    items: [
      {
        id: 'analyticsOverview',
        label: 'Overview',
        labelAr: 'نظرة عامة',
        icon: LayoutDashboard,
        href: '/dashboard/analytics',
      },
      {
        id: 'analyticsInsights',
        label: 'KPIs & Charts',
        labelAr: 'المؤشرات والرسوم',
        icon: Target,
        href: '/dashboard/analytics/insights',
      },
      {
        id: 'analyticsPerformance',
        label: 'Sales & Products',
        labelAr: 'المبيعات والمنتجات',
        icon: ShoppingBag,
        href: '/dashboard/analytics/performance',
      },
      {
        id: 'analyticsCustomers',
        label: 'Customers & Growth',
        labelAr: 'العملاء والنمو',
        icon: UsersRound,
        href: '/dashboard/analytics/customers',
      },
      {
        id: 'analyticsOperations',
        label: 'Stock & Operations',
        labelAr: 'المخزون والعمليات',
        icon: Boxes,
        href: '/dashboard/analytics/operations',
      },
      {
        id: 'analyticsFinance',
        label: 'Finance & Payments',
        labelAr: 'المالية والمدفوعات',
        icon: PiggyBank,
        href: '/dashboard/analytics/finance',
      },
      {
        id: 'reportsHub',
        label: 'Analytics & Reports',
        labelAr: 'التحليلات والتقارير',
        icon: FileBarChart,
        href: '/dashboard/analytics/reports',
      },
      {
        id: 'analyticsSettings',
        label: 'Analytics Settings',
        labelAr: 'إعدادات التحليلات',
        icon: Settings,
        href: '/dashboard/settings?tab=analytics_settings&from=analytics',
      },
    ],
  },
  {
    id: 'ai',
    published: false,
    title: 'AI Assistant',
    titleAr: 'الذكاء الاصطناعي',
    moduleId: 'ai',
    icon: Bot,
    items: [
      {
        id: 'aiContent',
        label: 'AI Content',
        labelAr: 'كتابة المحتوى',
        icon: PenLine,
        href: '/dashboard/ai',
      },
      {
        id: 'aiTheme',
        label: 'AI Theme Generator',
        labelAr: 'مولد الثيم',
        icon: Palette,
        href: '/dashboard/ai/theme-generator',
      },
      {
        id: 'aiPages',
        label: 'AI Pages Generator',
        labelAr: 'مولد صفحات AI',
        icon: LayoutTemplate,
        href: '/dashboard/ai/ai-pages',
      },
      {
        id: 'aiBrand',
        label: 'Brand Identity',
        labelAr: 'هوية العلامة',
        icon: Gem,
        href: '/dashboard/ai/brand-identity',
      },
      {
        id: 'aiSettings',
        label: 'AI Settings',
        labelAr: 'إعدادات الذكاء الاصطناعي',
        icon: Settings,
        href: '/dashboard/settings?tab=apps&from=ai',
      },
      {
        id: 'aiDesign',
        label: 'Design Assistant',
        labelAr: 'مساعد التصميم',
        icon: Wand2,
        href: '/dashboard/ai/design-assistant',
      },
      {
        id: 'aiImages',
        label: 'AI Images',
        labelAr: 'إنشاء الصور',
        icon: ImagePlus,
        href: '/dashboard/ai/images',
      },
      {
        id: 'aiSEO',
        label: 'AI SEO',
        labelAr: 'تحسين SEO',
        icon: SearchCheck,
        href: '/dashboard/ai/seo',
      },
      {
        id: 'aiAnalysis',
        label: 'AI Analysis',
        labelAr: 'تحليل النشاط',
        icon: BrainCircuit,
        href: '/dashboard/ai/analysis',
      },
      {
        id: 'aiReplies',
        label: 'AI Replies',
        labelAr: 'الردود التلقائية',
        icon: MessageCircle,
        href: '/dashboard/ai/replies',
      },
      {
        id: 'aiSuggestions',
        label: 'AI Suggestions',
        labelAr: 'الاقتراحات',
        icon: Lightbulb,
        href: '/dashboard/ai/suggestions',
      },
      // aiPageGen (AI Page Builder) مخفي مؤقتًا — ميزة مستقبلية حتى تنضج (المسار /dashboard/ai/page-builder ما زال موجودًا)
      {
        id: 'aiDataAnalysis',
        label: 'AI Data Analysis',
        labelAr: 'تحليل البيانات',
        icon: FileSpreadsheet,
        href: '/dashboard/ai/data-analysis',
      },
      {
        id: 'aiInsights',
        label: 'AI Insights',
        labelAr: 'رؤى AI',
        icon: Radar,
        href: '/dashboard/ai/insights',
      },
      {
        id: 'aiAutomations',
        label: 'AI Automations',
        labelAr: 'أتمتة AI',
        icon: Workflow,
        href: '/dashboard/ai/automations',
      },
    ],
  },
  {
    id: 'settings',
    moduleId: 'settings',
    title: 'Settings',
    titleAr: 'الإعدادات',
    items: [
      {
        id: 'settings_overview',
        label: 'Overview',
        labelAr: 'النظرة العامة',
        icon: Home,
        href: '/dashboard/settings?tab=overview',
      },
      {
        id: 'settings_store',
        label: 'Store',
        labelAr: 'بيانات المتجر والنشاط',
        icon: Store,
        href: '/dashboard/settings?tab=store',
      },
      {
        id: 'settings_bookings',
        label: 'Bookings Settings',
        labelAr: 'إعدادات الحجوزات',
        icon: CalendarDays,
        href: '/dashboard/settings?tab=booking_settings',
      },
      {
        id: 'settings_orders',
        label: 'Orders Settings',
        labelAr: 'إعدادات الطلبات',
        icon: ShoppingCart,
        href: '/dashboard/settings?tab=orders_settings',
      },
      {
        id: 'settings_pos',
        label: 'POS Settings',
        labelAr: 'إعدادات الكاشير (POS)',
        icon: Printer,
        href: '/dashboard/settings?tab=pos_settings',
      },
      {
        id: 'settings_payments',
        label: 'Payments',
        labelAr: 'المدفوعات',
        icon: CreditCard,
        href: '/dashboard/settings?tab=payments',
      },
      {
        id: 'settings_account',
        label: 'Account',
        labelAr: 'الحساب',
        icon: User,
        href: '/dashboard/settings?tab=account',
      },
      {
        id: 'settings_security',
        label: 'Security',
        labelAr: 'الأمان',
        icon: Shield,
        href: '/dashboard/settings?tab=security',
      },
      {
        id: 'settings_receipt_theme',
        label: 'Receipt Theme',
        labelAr: 'تصميم الإيصال',
        icon: Receipt,
        href: '/dashboard/settings?tab=receipt_theme',
      },
      {
        id: 'settings_notifications',
        label: 'Notifications',
        labelAr: 'الإشعارات',
        icon: Bell,
        href: '/dashboard/settings?tab=notifications',
      },
      {
        id: 'settings_social_media',
        label: 'Social Media',
        labelAr: 'السوشيال ميديا',
        icon: Share2,
        href: '/dashboard/settings?tab=social_media',
      },
      {
        id: 'settings_modules',
        label: 'Modules',
        labelAr: 'الوحدات',
        icon: Puzzle,
        href: '/dashboard/settings?tab=modules',
      },
      {
        id: 'settings_apps',
        label: 'Apps',
        labelAr: 'التطبيقات',
        icon: LayoutGrid,
        href: '/dashboard/settings?tab=apps',
      },
    ],
  },
];
