import {
  LayoutDashboard,
  Bell,
  CreditCard,
  Package,
  CircleDollarSign,
  Megaphone,
  Users,
  CalendarDays,
  UserCog,
  BarChart3,
  Globe,
  Bot,
  Settings,
  Home,
  Shield,
  Store,
  Puzzle,
  LayoutGrid,
  Share2,
  TrendingUp,
  TrendingDown,
  User,
  Plus,
  ShoppingCart,
  Scale,
  BookOpen,
  Wallet as WalletIcon,
  FileText,
  Undo2,
  ShoppingBag,
  Award,
  Gift,
  Repeat,
  Banknote,
  Calculator,
  Receipt,
  ScanBarcode,
  Clock,
  FolderOpen,
  Layers,
  ClipboardList,
  Truck,
  FileStack,
  Warehouse,
  ArrowLeftRight,
  Barcode,
  PackageSearch,
  AlertTriangle,
  ReceiptText,
  LineChart,
  Landmark,
  FileBarChart,
  Percent,
  BadgePercent,
  Ticket,
  MessageSquare,
  Mail,
  Smartphone,
  Sparkles,
  Target,
  Tag,
  UserRoundSearch,
  Headset,
  MessagesSquare,
  MessageCircle,
  LifeBuoy,
  Star,
  CalendarClock,
  CalendarCheck,
  CalendarRange,
  Stethoscope,
  BedDouble,
  Utensils,
  Briefcase,
  KeyRound,
  UserCheck,
  Timer,
  Coins,
  Hourglass,
  ClipboardCheck,
  PenLine,
  Palette,
  LayoutTemplate,
  Gem,
  Wand2,
  ImagePlus,
  SearchCheck,
  BrainCircuit,
  Lightbulb,
  FileSpreadsheet,
  Radar,
  Workflow,
  Activity,
  ChartPie,
  Eye,
  MousePointerClick,
  Boxes,
  Heart,
  Building2,
  GitBranch,
  UsersRound,
  FileCheck,
  PackageCheck,
  Tags,
  ScrollText,
  PiggyBank,
  ScanLine,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type SidebarItem = {
  id: string;
  label: string;
  labelAr: string;
  icon: LucideIcon;
  href: string;
  /** false = local-only / not yet released (shows a "قريباً" badge) */
  published?: boolean;
};

export type SidebarSection = {
  id: string;
  title: string;
  titleAr: string;
  moduleId?: string;
  icon?: LucideIcon;
  items: SidebarItem[];
  mainHref?: string;
  /** false = local-only / not yet released section */
  published?: boolean;
};

// Colored accent per section — used by TopNav and Sidebar so each
// section's page icons feel visually distinct.
export const SECTION_COLORS: Record<string, string> = {
  dashboard: 'text-sky-500',
  branches: 'text-blue-600',
  team: 'text-teal-600',
  sales: 'text-emerald-500',
  pos: 'text-lime-600',
  inventory: 'text-amber-500',
  finance: 'text-teal-500',
  accounting: 'text-indigo-500',
  marketing: 'text-rose-500',
  customers: 'text-cyan-600',
  crm: 'text-violet-500',
  bookings: 'text-pink-500',
  hr: 'text-orange-500',
  website: 'text-blue-500',
  analytics: 'text-fuchsia-500',
  ai: 'text-purple-500',
  settings: 'text-slate-500',
};

// Market-launch switch: items/sections marked `published: false` are hidden
// from merchants in production builds and stay visible on local/dev machines
// so the team can keep working on them before release.
export const HIDE_UNPUBLISHED = process.env.NODE_ENV === 'production';

export const sidebarSections: SidebarSection[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    titleAr: 'الرئيسية',
    items: [
      {
        id: 'overview',
        label: 'Overview',
        labelAr: 'نظرة عامة',
        icon: LayoutDashboard,
        href: '/dashboard',
      },
      {
        id: 'notifications',
        label: 'Notifications',
        labelAr: 'الإشعارات',
        icon: Bell,
        href: '/dashboard/notifications',
      },
    ],
  },
  {
    id: 'sales',
    title: 'Sales',
    titleAr: 'المبيعات',
    moduleId: 'sales',
    icon: CreditCard,
    items: [
      {
        id: 'sales',
        label: 'Orders',
        labelAr: 'الطلبات',
        icon: ShoppingCart,
        href: '/dashboard/sales',
      },
      {
        id: 'salesOrders',
        published: false,
        label: 'Sales Orders',
        labelAr: 'أوامر البيع',
        icon: FileCheck,
        href: '/dashboard/sales/orders',
      },
      {
        id: 'deliveryNotes',
        published: false,
        label: 'Delivery Notes',
        labelAr: 'أوراق الصرف',
        icon: PackageCheck,
        href: '/dashboard/sales/delivery-notes',
      },
      {
        id: 'quotes',
        published: false,
        label: 'Quotes',
        labelAr: 'عروض الأسعار',
        icon: FileText,
        href: '/dashboard/sales/quotes',
      },
      {
        id: 'abandonedCart',
        published: false,
        label: 'Abandoned Carts',
        labelAr: 'السلات المتروكة',
        icon: ShoppingBag,
        href: '/dashboard/sales/abandoned-cart',
      },
      {
        id: 'loyalty',
        published: false,
        label: 'Loyalty Points',
        labelAr: 'نقاط الولاء',
        icon: Award,
        href: '/dashboard/sales/loyalty',
      },
      {
        id: 'loyaltyCard',
        published: false,
        label: 'Loyalty Card',
        labelAr: 'بطاقة الولاء',
        icon: Gift,
        href: '/dashboard/sales/loyalty-card',
      },
      {
        id: 'subscriptions',
        published: false,
        label: 'Subscriptions',
        labelAr: 'الاشتراكات',
        icon: Repeat,
        href: '/dashboard/sales/subscriptions',
      },
      {
        id: 'epayment',
        published: false,
        label: 'E-Payment',
        labelAr: 'الدفع الإلكتروني',
        icon: CreditCard,
        href: '/dashboard/sales/epayment',
      },
    ],
  },
  {
    id: 'pos',
    title: 'POS / Cashier',
    titleAr: 'الكاشير',
    moduleId: 'pos',
    icon: Calculator,
    mainHref: '/dashboard/pos',
    items: [
      {
        id: 'posCheckout',
        label: 'Cashier',
        labelAr: 'الكاشير',
        icon: ScanBarcode,
        href: '/dashboard/pos',
      },
      {
        id: 'posShifts',
        label: 'Shifts',
        labelAr: 'الورديات',
        icon: Clock,
        href: '/dashboard/pos/shifts',
      },
      {
        id: 'posSettings',
        label: 'POS Settings',
        labelAr: 'إعدادات الكاشير',
        icon: Settings,
        href: '/dashboard/pos/settings',
      },
      {
        id: 'posReports',
        label: 'POS Reports',
        labelAr: 'تقارير الكاشير',
        icon: BarChart3,
        href: '/dashboard/pos/reports',
      },
    ],
  },
  {
    id: 'inventory',
    title: 'Inventory',
    titleAr: 'المخزون',
    moduleId: 'inventory',
    icon: Package,
    items: [
      {
        id: 'products',
        label: 'Products',
        labelAr: 'المنتجات',
        icon: Package,
        href: '/dashboard/inventory',
      },
      {
        id: 'categories',
        label: 'Categories',
        labelAr: 'الفئات',
        icon: FolderOpen,
        href: '/dashboard/inventory/categories',
      },
      {
        id: 'variants',
        published: false,
        label: 'Variants',
        labelAr: 'الأنواع',
        icon: Layers,
        href: '/dashboard/inventory/variants',
      },
      {
        id: 'stocktake',
        label: 'Stock Take',
        labelAr: 'جرد المخزون',
        icon: ClipboardList,
        href: '/dashboard/inventory/stocktake',
      },
      {
        id: 'suppliers',
        published: false,
        label: 'Suppliers',
        labelAr: 'الموردين',
        icon: Truck,
        href: '/dashboard/inventory/suppliers',
      },
      {
        id: 'purchaseOrders',
        published: false,
        label: 'Purchase Orders',
        labelAr: 'أوامر الشراء',
        icon: FileStack,
        href: '/dashboard/inventory/purchase-orders',
      },
      {
        id: 'warehouses',
        published: false,
        label: 'Warehouses',
        labelAr: 'المخازن',
        icon: Warehouse,
        href: '/dashboard/inventory/warehouses',
      },
      {
        id: 'transfers',
        published: false,
        label: 'Transfers',
        labelAr: 'النقل بين المخازن',
        icon: ArrowLeftRight,
        href: '/dashboard/inventory/transfers',
      },
      {
        id: 'barcode',
        label: 'Barcode',
        labelAr: 'الباركود',
        icon: Barcode,
        href: '/dashboard/inventory/barcode',
      },
      {
        id: 'stockTracking',
        published: false,
        label: 'Stock Tracking',
        labelAr: 'تتبع الكميات',
        icon: PackageSearch,
        href: '/dashboard/inventory/stock-tracking',
      },
      {
        id: 'lowStockAlerts',
        label: 'Low Stock',
        labelAr: 'تنبيهات النفاد',
        icon: AlertTriangle,
        href: '/dashboard/inventory/low-stock',
      },
    ],
  },
  {
    id: 'branches',
    published: false,
    title: 'Branches',
    titleAr: 'الفروع',
    moduleId: 'branches',
    icon: Building2,
    items: [
      {
        id: 'branchesList',
        label: 'Branches',
        labelAr: 'إدارة الفروع',
        icon: Building2,
        href: '/dashboard/branches',
      },
      {
        id: 'branchCompare',
        label: 'Branch Comparison',
        labelAr: 'مقارنة الفروع',
        icon: GitBranch,
        href: '/dashboard/branches/compare',
      },
    ],
  },
  {
    id: 'finance',
    title: 'Finance',
    titleAr: 'المالية',
    moduleId: 'finance',
    icon: CircleDollarSign,
    items: [
      {
        id: 'invoice',
        label: 'Invoices',
        labelAr: 'الفواتير',
        icon: ReceiptText,
        href: '/dashboard/finance',
      },
      {
        id: 'newInvoice',
        label: 'New Invoice',
        labelAr: 'فاتورة جديدة',
        icon: Plus,
        href: '/dashboard/finance?action=new',
      },
      {
        id: 'revenue',
        label: 'Revenue',
        labelAr: 'الإيرادات',
        icon: TrendingUp,
        href: '/dashboard/finance/revenue',
      },
      {
        id: 'wallets',
        published: false,
        label: 'Wallets',
        labelAr: 'المحافظ والخزائن',
        icon: WalletIcon,
        href: '/dashboard/finance/wallets',
      },
      {
        id: 'cashflow',
        published: false,
        label: 'Cash Flow',
        labelAr: 'التدفق النقدي',
        icon: Share2,
        href: '/dashboard/finance/cashflow',
      },
      {
        id: 'profits',
        published: false,
        label: 'Profits',
        labelAr: 'الأرباح',
        icon: LineChart,
        href: '/dashboard/finance/profits',
      },
      {
        id: 'eta',
        published: false,
        label: 'E-Invoice (ETA)',
        labelAr: 'الفاتورة الإلكترونية',
        icon: ScanLine,
        href: '/dashboard/finance/eta',
      },
    ],
  },
  {
    id: 'accounting',
    published: false,
    title: 'Accounting',
    titleAr: 'المحاسبة',
    moduleId: 'accounting',
    icon: BookOpen,
    items: [
      {
        id: 'accounts',
        label: 'Chart of Accounts',
        labelAr: 'دليل الحسابات',
        icon: Landmark,
        href: '/dashboard/finance/accounts',
      },
      {
        id: 'journal',
        label: 'Journal Entries',
        labelAr: 'القيود المحاسبية',
        icon: BookOpen,
        href: '/dashboard/finance/journal',
      },
      {
        id: 'trialBalance',
        label: 'Trial Balance',
        labelAr: 'ميزان المراجعة',
        icon: Scale,
        href: '/dashboard/finance/trial-balance',
      },
      {
        id: 'financialReports',
        label: 'Financial Reports',
        labelAr: 'القوائم المالية',
        icon: FileBarChart,
        href: '/dashboard/finance/financial-reports',
      },
      {
        id: 'expenses',
        label: 'Expenses',
        labelAr: 'المصروفات',
        icon: TrendingDown,
        href: '/dashboard/finance/expenses',
      },
      {
        id: 'taxes',
        label: 'Taxes',
        labelAr: 'الضرائب',
        icon: Percent,
        href: '/dashboard/finance/taxes',
      },
    ],
  },
  {
    id: 'team',
    published: false,
    title: 'Team',
    titleAr: 'فريق العمل',
    moduleId: 'team',
    icon: UsersRound,
    items: [
      {
        id: 'teamMembers',
        label: 'Team Members',
        labelAr: 'المستخدمون',
        icon: UsersRound,
        href: '/dashboard/team',
      },
      {
        id: 'teamRoles',
        label: 'Roles & Permissions',
        labelAr: 'الأدوار والصلاحيات',
        icon: KeyRound,
        href: '/dashboard/team/roles',
      },
    ],
  },
  {
    id: 'marketing',
    published: false,
    title: 'Marketing',
    titleAr: 'التسويق',
    moduleId: 'marketing',
    icon: Megaphone,
    items: [
      {
        id: 'promotions',
        label: 'Promotions',
        labelAr: 'الترويج',
        icon: BadgePercent,
        href: '/dashboard/marketing',
      },
      {
        id: 'campaigns',
        label: 'Campaigns',
        labelAr: 'الحملات',
        icon: Megaphone,
        href: '/dashboard/marketing/campaigns',
      },
      {
        id: 'coupons',
        label: 'Coupons',
        labelAr: 'الكوبونات',
        icon: Ticket,
        href: '/dashboard/marketing/coupons',
      },
      {
        id: 'discounts',
        label: 'Discounts',
        labelAr: 'الخصومات',
        icon: Percent,
        href: '/dashboard/marketing/discounts',
      },
      {
        id: 'messages',
        label: 'Messages',
        labelAr: 'الرسائل',
        icon: MessageSquare,
        href: '/dashboard/marketing/messages',
      },
      {
        id: 'emailCampaigns',
        label: 'Email Campaigns',
        labelAr: 'حملات الإيميل',
        icon: Mail,
        href: '/dashboard/marketing/email-campaigns',
      },
      {
        id: 'smsCampaigns',
        label: 'SMS Campaigns',
        labelAr: 'حملات SMS',
        icon: Smartphone,
        href: '/dashboard/marketing/sms-campaigns',
      },
      {
        id: 'loyaltyPrograms',
        label: 'Loyalty Programs',
        labelAr: 'برامج الولاء',
        icon: Sparkles,
        href: '/dashboard/marketing/loyalty-programs',
      },
      {
        id: 'pushNotifications',
        label: 'Push Notifications',
        labelAr: 'الإشعارات الفورية',
        icon: Bell,
        href: '/dashboard/marketing/push-notifications',
      },
      {
        id: 'seasonalOffers',
        label: 'Seasonal Offers',
        labelAr: 'العروض الموسمية',
        icon: Gift,
        href: '/dashboard/marketing/seasonal-offers',
      },
      {
        id: 'marketingHub',
        label: 'Marketing Hub',
        labelAr: 'مركز التسويق',
        icon: Target,
        href: '/dashboard/marketing/hub',
      },
    ],
  },
  {
    id: 'customers',
    title: 'Customers',
    titleAr: 'العملاء',
    moduleId: 'customers',
    icon: Users,
    items: [
      {
        id: 'customers',
        label: 'Customers',
        labelAr: 'العملاء',
        icon: Users,
        href: '/dashboard/crm',
      },
      {
        id: 'customerStatements',
        label: 'Statements',
        labelAr: 'كشوف الحساب',
        icon: ScrollText,
        href: '/dashboard/customers/statements',
      },
      {
        id: 'creditLimits',
        label: 'Credit Limits',
        labelAr: 'حدود الائتمان',
        icon: PiggyBank,
        href: '/dashboard/customers/credit-limits',
      },
      {
        id: 'wholesalePricing',
        published: false,
        label: 'Wholesale Pricing',
        labelAr: 'أسعار الجملة',
        icon: Tags,
        href: '/dashboard/customers/wholesale-pricing',
      },
      {
        id: 'customerSegments',
        published: false,
        label: 'Segments',
        labelAr: 'الشرائح',
        icon: UserRoundSearch,
        href: '/dashboard/customers/segments',
      },
      {
        id: 'customerTags',
        published: false,
        label: 'Tags',
        labelAr: 'الوسوم',
        icon: Tag,
        href: '/dashboard/customers/tags',
      },
    ],
  },
  {
    id: 'crm',
    published: false,
    title: 'Customer Service',
    titleAr: 'خدمة العملاء',
    moduleId: 'crm',
    icon: Headset,
    items: [
      {
        id: 'chats',
        label: 'Chats',
        labelAr: 'المحادثات',
        icon: MessagesSquare,
        href: '/dashboard/crm/chats',
      },
      {
        id: 'tickets',
        label: 'Tickets',
        labelAr: 'التذاكر',
        icon: Ticket,
        href: '/dashboard/crm/tickets',
      },
      {
        id: 'complaints',
        label: 'Complaints',
        labelAr: 'الشكاوى',
        icon: LifeBuoy,
        href: '/dashboard/crm/complaints',
      },
      {
        id: 'reviews',
        label: 'Reviews',
        labelAr: 'التقييمات',
        icon: Star,
        href: '/dashboard/crm/reviews',
      },
    ],
  },
  {
    id: 'bookings',
    title: 'Booking Management',
    titleAr: 'الحجوزات',
    moduleId: 'bookings',
    icon: CalendarDays,
    mainHref: '/dashboard/bookings',
    items: [
      {
        id: 'bookingsOverview',
        label: 'Overview',
        labelAr: 'نظرة عامة',
        icon: CalendarClock,
        href: '/dashboard/bookings?tab=overview',
      },
      {
        id: 'reservations',
        label: 'Reservations',
        labelAr: 'الحجوزات',
        icon: CalendarCheck,
        href: '/dashboard/bookings?tab=reservations',
      },
      {
        id: 'calendar',
        label: 'Calendar',
        labelAr: 'التقويم',
        icon: CalendarDays,
        href: '/dashboard/bookings?tab=calendar',
      },
      {
        id: 'appointments',
        label: 'Appointments',
        labelAr: 'جدول المواعيد',
        icon: CalendarRange,
        href: '/dashboard/bookings?tab=appointments',
      },
      {
        id: 'doctors',
        label: 'Doctors',
        labelAr: 'الأطباء والمقدمون',
        icon: Stethoscope,
        href: '/dashboard/bookings?tab=doctors',
      },
      {
        id: 'rooms',
        label: 'Rooms',
        labelAr: 'الغرف والقاعات',
        icon: BedDouble,
        href: '/dashboard/bookings?tab=rooms',
      },
      {
        id: 'tables',
        label: 'Tables',
        labelAr: 'الطاولات والأماكن',
        icon: Utensils,
        href: '/dashboard/bookings?tab=tables',
      },
      {
        id: 'bookingsNotifications',
        label: 'Notifications',
        labelAr: 'الإشعارات',
        icon: Bell,
        href: '/dashboard/bookings?tab=notifications',
      },
      {
        id: 'bookingsSettings',
        label: 'Settings',
        labelAr: 'الإعدادات',
        icon: Settings,
        href: '/dashboard/bookings?tab=settings',
      },
    ],
  },
  {
    id: 'hr',
    published: false,
    title: 'Human Resources',
    titleAr: 'الموارد البشرية',
    moduleId: 'hr',
    icon: UserCog,
    items: [
      {
        id: 'employees',
        label: 'Employees',
        labelAr: 'الموظفين',
        icon: Briefcase,
        href: '/dashboard/hr',
      },
      {
        id: 'permissions',
        label: 'Permissions',
        labelAr: 'الصلاحيات',
        icon: KeyRound,
        href: '/dashboard/hr/permissions',
      },
      {
        id: 'attendance',
        label: 'Attendance',
        labelAr: 'الحضور',
        icon: UserCheck,
        href: '/dashboard/hr/attendance',
      },
      {
        id: 'checkout',
        label: 'Check-out',
        labelAr: 'الانصراف',
        icon: Timer,
        href: '/dashboard/hr/check-out',
      },
      {
        id: 'payroll',
        label: 'Payroll',
        labelAr: 'الرواتب',
        icon: Coins,
        href: '/dashboard/hr/payroll',
      },
      {
        id: 'leaves',
        label: 'Leaves',
        labelAr: 'الإجازات',
        icon: Hourglass,
        href: '/dashboard/hr/leaves',
      },
      {
        id: 'tasks',
        label: 'Tasks',
        labelAr: 'المهام',
        icon: ClipboardCheck,
        href: '/dashboard/hr/tasks',
      },
    ],
  },
  {
    id: 'website',
    title: 'Website',
    titleAr: 'الموقع الإلكتروني',
    moduleId: 'website',
    icon: Globe,
    mainHref: '/dashboard/website',
    items: [
      {
        id: 'website',
        label: 'Website',
        labelAr: 'الموقع الإلكتروني',
        icon: Globe,
        href: '/dashboard/website',
      },
    ],
  },
  {
    id: 'analytics',
    title: 'Analytics',
    titleAr: 'التحليلات',
    moduleId: 'analytics',
    icon: BarChart3,
    items: [
      {
        id: 'allAnalytics',
        label: 'All Analytics',
        labelAr: 'كل التحليلات',
        icon: LayoutGrid,
        href: '/dashboard/analytics',
      },
      {
        id: 'kpi',
        label: 'KPIs',
        labelAr: 'المؤشرات',
        icon: Activity,
        href: '/dashboard/analytics/kpi',
      },
      {
        id: 'charts',
        label: 'Charts',
        labelAr: 'الرسوم البيانية',
        icon: ChartPie,
        href: '/dashboard/analytics/charts',
      },
      {
        id: 'salesPerformance',
        label: 'Sales Performance',
        labelAr: 'أداء المبيعات',
        icon: TrendingUp,
        href: '/dashboard/analytics/sales-performance',
      },
      {
        id: 'productPerformance',
        label: 'Product Performance',
        labelAr: 'أداء المنتجات',
        icon: PackageSearch,
        href: '/dashboard/analytics/product-performance',
      },
      {
        id: 'inventoryReports',
        label: 'Inventory Reports',
        labelAr: 'تقارير المخزون',
        icon: Boxes,
        href: '/dashboard/analytics/inventory',
      },
      {
        id: 'customerInsights',
        label: 'Customer Insights',
        labelAr: 'تحليلات العملاء',
        icon: Users,
        href: '/dashboard/analytics/customer-insights',
      },
      {
        id: 'engagementAnalytics',
        label: 'Engagement',
        labelAr: 'تحليلات المشاركة',
        icon: Heart,
        href: '/dashboard/analytics/engagement',
      },
      {
        id: 'visitors',
        label: 'Visitors',
        labelAr: 'الزوار',
        icon: Eye,
        href: '/dashboard/analytics/visitors',
      },
      {
        id: 'conversions',
        label: 'Conversions',
        labelAr: 'التحويلات',
        icon: MousePointerClick,
        href: '/dashboard/analytics/conversions',
      },
      {
        id: 'returnsReport',
        label: 'Returns Reports',
        labelAr: 'تقارير المرتجعات',
        icon: Undo2,
        href: '/dashboard/analytics/returns',
      },
      {
        id: 'financeAnalytics',
        label: 'Finance Reports',
        labelAr: 'تقارير المالية',
        icon: Landmark,
        href: '/dashboard/analytics/finance',
      },
      {
        id: 'marketingAnalytics',
        label: 'Marketing Analytics',
        labelAr: 'تحليلات التسويق',
        icon: Megaphone,
        href: '/dashboard/analytics/marketing',
      },
      {
        id: 'operationsAnalytics',
        label: 'Operations Analytics',
        labelAr: 'تحليلات العمليات',
        icon: Workflow,
        href: '/dashboard/analytics/operations',
      },
      {
        id: 'paymentsAnalytics',
        label: 'Payments Reports',
        labelAr: 'تقارير المدفوعات',
        icon: Banknote,
        href: '/dashboard/analytics/payments',
      },
      {
        id: 'logisticsAnalytics',
        label: 'Logistics Reports',
        labelAr: 'تقارير اللوجستيات',
        icon: Truck,
        href: '/dashboard/analytics/logistics',
      },
    ],
  },
  {
    id: 'ai',
    published: false,
    title: 'AI Assistant',
    titleAr: 'الذكاء الاصطناعي',
    moduleId: 'ai',
    icon: Bot,
    items: [
      {
        id: 'aiContent',
        label: 'AI Content',
        labelAr: 'كتابة المحتوى',
        icon: PenLine,
        href: '/dashboard/ai',
      },
      {
        id: 'aiTheme',
        label: 'AI Theme Generator',
        labelAr: 'مولد الثيم',
        icon: Palette,
        href: '/dashboard/ai/theme-generator',
      },
      {
        id: 'aiPages',
        label: 'AI Pages Generator',
        labelAr: 'مولد صفحات AI',
        icon: LayoutTemplate,
        href: '/dashboard/ai/ai-pages',
      },
      {
        id: 'aiBrand',
        label: 'Brand Identity',
        labelAr: 'هوية العلامة',
        icon: Gem,
        href: '/dashboard/ai/brand-identity',
      },
      {
        id: 'aiDesign',
        label: 'Design Assistant',
        labelAr: 'مساعد التصميم',
        icon: Wand2,
        href: '/dashboard/ai/design-assistant',
      },
      {
        id: 'aiImages',
        label: 'AI Images',
        labelAr: 'إنشاء الصور',
        icon: ImagePlus,
        href: '/dashboard/ai/images',
      },
      {
        id: 'aiSEO',
        label: 'AI SEO',
        labelAr: 'تحسين SEO',
        icon: SearchCheck,
        href: '/dashboard/ai/seo',
      },
      {
        id: 'aiAnalysis',
        label: 'AI Analysis',
        labelAr: 'تحليل النشاط',
        icon: BrainCircuit,
        href: '/dashboard/ai/analysis',
      },
      {
        id: 'aiReplies',
        label: 'AI Replies',
        labelAr: 'الردود التلقائية',
        icon: MessageCircle,
        href: '/dashboard/ai/replies',
      },
      {
        id: 'aiSuggestions',
        label: 'AI Suggestions',
        labelAr: 'الاقتراحات',
        icon: Lightbulb,
        href: '/dashboard/ai/suggestions',
      },
      // aiPageGen (AI Page Builder) مخفي مؤقتًا — ميزة مستقبلية حتى تنضج (المسار /dashboard/ai/page-builder ما زال موجودًا)
      {
        id: 'aiDataAnalysis',
        label: 'AI Data Analysis',
        labelAr: 'تحليل البيانات',
        icon: FileSpreadsheet,
        href: '/dashboard/ai/data-analysis',
      },
      {
        id: 'aiInsights',
        label: 'AI Insights',
        labelAr: 'رؤى AI',
        icon: Radar,
        href: '/dashboard/ai/insights',
      },
      {
        id: 'aiAutomations',
        label: 'AI Automations',
        labelAr: 'أتمتة AI',
        icon: Workflow,
        href: '/dashboard/ai/automations',
      },
    ],
  },
  {
    id: 'settings',
    moduleId: 'settings',
    title: 'Settings',
    titleAr: 'الإعدادات',
    items: [
      {
        id: 'settings_overview',
        label: 'Overview',
        labelAr: 'النظرة العامة',
        icon: Home,
        href: '/dashboard/settings?tab=overview',
      },
      {
        id: 'settings_account',
        label: 'Account',
        labelAr: 'الحساب',
        icon: User,
        href: '/dashboard/settings?tab=account',
      },
      {
        id: 'settings_security',
        label: 'Security',
        labelAr: 'الأمان',
        icon: Shield,
        href: '/dashboard/settings?tab=security',
      },
      {
        id: 'settings_store',
        label: 'Store',
        labelAr: 'المتجر',
        icon: Store,
        href: '/dashboard/settings?tab=store',
      },
      {
        id: 'settings_modules',
        label: 'Modules',
        labelAr: 'الوحدات',
        icon: Puzzle,
        href: '/dashboard/settings?tab=modules',
      },
      {
        id: 'settings_apps',
        label: 'Apps',
        labelAr: 'التطبيقات',
        icon: LayoutGrid,
        href: '/dashboard/settings?tab=apps',
      },
      {
        id: 'settings_receipt_theme',
        label: 'Receipt Theme',
        labelAr: 'تصميم الإيصال',
        icon: Receipt,
        href: '/dashboard/settings?tab=receipt_theme',
      },
      {
        id: 'settings_payments',
        label: 'Payments',
        labelAr: 'المدفوعات',
        icon: CreditCard,
        href: '/dashboard/settings?tab=payments',
      },
      {
        id: 'settings_social_media',
        label: 'Social Media',
        labelAr: 'السوشيال ميديا',
        icon: Share2,
        href: '/dashboard/settings?tab=social_media',
      },
      {
        id: 'settings_notifications',
        label: 'Notifications',
        labelAr: 'الإشعارات',
        icon: Bell,
        href: '/dashboard/settings?tab=notifications',
      },
    ],
  },
];
