// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';
import {syncer} from '../models';

export function AddCashMovement(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Checkout(arg1:main.CheckoutRequest):Promise<main.CheckoutResult>;

export function CloseShift(arg1:number,arg2:string):Promise<store.Shift>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CurrentSession():Promise<string>;

export function DeleteHeldOrder(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GateAdmin(arg1:string):Promise<void>;

export function GateSubmit(arg1:string,arg2:string,arg3:number):Promise<store.Shift>;

export function GetActiveShift():Promise<store.Shift>;

export function GetCashMovements():Promise<Array<store.CashMovement>>;

export function GetCategories():Promise<Array<string>>;

export function GetGate():Promise<main.GateInfo>;

export function GetHeldOrders():Promise<Array<store.HeldOrder>>;

export function GetOrders(arg1:string):Promise<Array<store.Order>>;

export function GetProducts(arg1:string,arg2:string):Promise<Array<store.Product>>;

export function GetShiftReport():Promise<Record<string, any>>;

export function GetShiftsHistory():Promise<Array<store.Shift>>;

export function GetState():Promise<main.AppState>;

export function GetSyncStatus():Promise<syncer.Status>;

export function HoldOrder(arg1:string,arg2:string):Promise<void>;

export function LockScreen():Promise<void>;

export function SessionExpired():Promise<void>;

export function SyncNow():Promise<syncer.Status>;

export function UpdateTokens(arg1:string,arg2:string):Promise<void>;
