// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCashMovement(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCashMovement'](arg1, arg2, arg3);
}

export function Checkout(arg1) {
  return window['go']['main']['App']['Checkout'](arg1);
}

export function CloseShift(arg1, arg2) {
  return window['go']['main']['App']['CloseShift'](arg1, arg2);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function CurrentSession() {
  return window['go']['main']['App']['CurrentSession']();
}

export function DeleteHeldOrder(arg1) {
  return window['go']['main']['App']['DeleteHeldOrder'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GateAdmin(arg1) {
  return window['go']['main']['App']['GateAdmin'](arg1);
}

export function GateSubmit(arg1, arg2, arg3) {
  return window['go']['main']['App']['GateSubmit'](arg1, arg2, arg3);
}

export function GetActiveShift() {
  return window['go']['main']['App']['GetActiveShift']();
}

export function GetCashMovements() {
  return window['go']['main']['App']['GetCashMovements']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetGate() {
  return window['go']['main']['App']['GetGate']();
}

export function GetHeldOrders() {
  return window['go']['main']['App']['GetHeldOrders']();
}

export function GetOrders(arg1) {
  return window['go']['main']['App']['GetOrders'](arg1);
}

export function GetProducts(arg1, arg2) {
  return window['go']['main']['App']['GetProducts'](arg1, arg2);
}

export function GetShiftReport() {
  return window['go']['main']['App']['GetShiftReport']();
}

export function GetShiftsHistory() {
  return window['go']['main']['App']['GetShiftsHistory']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function HoldOrder(arg1, arg2) {
  return window['go']['main']['App']['HoldOrder'](arg1, arg2);
}

export function LockScreen() {
  return window['go']['main']['App']['LockScreen']();
}

export function SessionExpired() {
  return window['go']['main']['App']['SessionExpired']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function UpdateTokens(arg1, arg2) {
  return window['go']['main']['App']['UpdateTokens'](arg1, arg2);
}
