import type { BusinessCategoryDef, BusinessTypeDef, ModuleRecommendation, ModuleId } from './types';

export const BUSINESS_CATEGORIES: BusinessCategoryDef[] = [
  {
    id: 'food_market',
    title: 'Food & Market',
    titleKey: 'business.categories.foodMarket',
    titleAr: 'طعام وتموينات',
    description: 'Restaurants, cafes, grocery stores, supermarkets, and bakeries.',
    descriptionAr: 'مطاعم، مقاهي، بقالات، سوبر ماركت، ومخابز.',
    icon: 'utensils',
    color: '#EA580C',
  },
  {
    id: 'fashion_home',
    title: 'Fashion & Home',
    titleKey: 'business.categories.fashionHome',
    titleAr: 'أزياء ومنزل',
    description: 'Clothing, shoes, fabrics, curtains, furniture, and home goods.',
    descriptionAr: 'ملابس، أحذية، أقمشة، ستائر، أثاث، ومستلزمات منزلية.',
    icon: 'shirt',
    color: '#BE185D',
  },
  {
    id: 'jewelry_luxury',
    title: 'Jewelry & Luxury',
    titleKey: 'business.categories.jewelryLuxury',
    titleAr: 'مجوهرات وفاخر',
    description: 'Gold, silver, jewelry, watches, and premium gifts.',
    descriptionAr: 'ذهب، فضة، مجوهرات، ساعات، وهدايا فاخرة.',
    icon: 'crown',
    color: '#D97706',
  },
  {
    id: 'real_estate',
    title: 'Real Estate & Construction',
    titleKey: 'business.categories.realEstate',
    titleAr: 'عقارات ومقاولات',
    description: 'Properties, lands, contractors, and building supplies.',
    descriptionAr: 'عقارات، أراضي، مقاولات، ومواد بناء.',
    icon: 'building',
    color: '#2563EB',
  },
  {
    id: 'vehicles',
    title: 'Vehicles',
    titleKey: 'business.categories.vehicles',
    titleAr: 'مركبات',
    description: 'Car showrooms, auto services, and spare parts.',
    descriptionAr: 'معارض سيارات، خدمات سيارات، وقطع غيار.',
    icon: 'car',
    color: '#DC2626',
  },
  {
    id: 'agriculture',
    title: 'Agriculture',
    titleKey: 'business.categories.agriculture',
    titleAr: 'زراعة',
    description: 'Seeds, fertilizers, nurseries, and landscaping.',
    descriptionAr: 'بذور، أسمدة، مشاتل، وتنسيق حدائق.',
    icon: 'sprout',
    color: '#16A34A',
  },
  {
    id: 'services',
    title: 'Services',
    titleKey: 'business.categories.services',
    titleAr: 'خدمات',
    description: 'Service companies, individual technicians, and workshops.',
    descriptionAr: 'شركات خدمات، فنيين أفراد، وورش.',
    icon: 'wrench',
    color: '#0891B2',
  },
  {
    id: 'electronics_health',
    title: 'Electronics & Health',
    titleKey: 'business.categories.electronicsHealth',
    titleAr: 'إلكترونيات وصحة',
    description: 'Computers, mobiles, pharmacies, and medical devices.',
    descriptionAr: 'حواسيب، جوالات، صيدليات، وأجهزة طبية.',
    icon: 'smartphone',
    color: '#0EA5E9',
  },
  {
    id: 'industrial_trade',
    title: 'Industrial & Trade',
    titleKey: 'business.categories.industrialTrade',
    titleAr: 'صناعة وتجارة',
    description: 'Factories, production lines, trading, import & export.',
    descriptionAr: 'مصانع، خطوط إنتاج، تجارة، واستيراد وتصدير.',
    icon: 'factory',
    color: '#475569',
  },
  {
    id: 'tourism_travel',
    title: 'Tourism & Travel',
    titleKey: 'business.categories.tourismTravel',
    titleAr: 'سياحة وسفر',
    description: 'Tour packages, hotels, flights, and travel services.',
    descriptionAr: 'باقات سياحية، فنادق، طيران، وخدمات سفر.',
    icon: 'plane',
    color: '#0EA5E9',
  },
  {
    id: 'livestock_fisheries',
    title: 'Livestock & Fisheries',
    titleKey: 'business.categories.livestockFisheries',
    titleAr: 'ثروة حيوانية ومصايد',
    description: 'Animal husbandry, feed, veterinary, and fish farming.',
    descriptionAr: 'تربية حيوانات، أعلاف، بيطرة، وتربية أسماك.',
    icon: 'fish',
    color: '#A16207',
  },
  {
    id: 'energy',
    title: 'Energy & Electrical',
    titleKey: 'business.categories.energy',
    titleAr: 'طاقة وكهرباء',
    description: 'Solar panels, batteries, generators, and electrical services.',
    descriptionAr: 'ألواح شمسية، بطاريات، مولدات، وخدمات كهربائية.',
    icon: 'zap',
    color: '#F59E0B',
  },
  {
    id: 'professional_services',
    title: 'Professional Services',
    titleKey: 'business.categories.professionalServices',
    titleAr: 'خدمات مهنية',
    description: 'Accounting, legal, translation, consulting, and freelance.',
    descriptionAr: 'محاسبة، قانوني، ترجمة، استشارات، وعمل حر.',
    icon: 'briefcase',
    color: '#1E3A8A',
  },
  {
    id: 'home_services',
    title: 'Home Services',
    titleKey: 'business.categories.homeServices',
    titleAr: 'خدمات منزلية',
    description: 'Plumbing, electrical, carpentry, painting, and cleaning.',
    descriptionAr: 'سباكة، كهرباء، نجارة، دهان، وتنظيف.',
    icon: 'home',
    color: '#DC2626',
  },
  {
    id: 'bookings',
    title: 'Bookings & Appointments',
    titleKey: 'business.categories.bookings',
    titleAr: 'حجوزات ومواعيد',
    description: 'Clinics, salons, spas, hotels, events, sports, and education.',
    descriptionAr: 'عيادات، صالونات، سبا، فنادق، فعاليات، رياضة، وتعليم.',
    icon: 'calendar',
    color: '#0891B2',
  },
  {
    id: 'other',
    title: 'Other',
    titleKey: 'business.categories.other',
    titleAr: 'أخرى',
    description: 'Any business not listed above — fully customizable.',
    descriptionAr: 'أي نشاط غير مدرج — قابل للتخصيص بالكامل.',
    icon: 'circle',
    color: '#334155',
  },
];

const rec = (moduleId: ModuleId, reason: string, priority: 'required' | 'recommended' | 'optional' = 'recommended'): ModuleRecommendation => ({
  moduleId,
  reason,
  priority,
});

export const BUSINESS_TYPES: BusinessTypeDef[] = [
  {
    id: 'restaurant',
    categoryId: 'food_market',
    title: 'Restaurant / Cafe',
    titleKey: 'business.types.restaurant',
    titleAr: 'مطعم / مقهى',
    description: 'Menu, tables, orders, delivery, offers, and meals.',
    descriptionAr: 'منيو، طاولات، طلبات، توصيل، عروض، ووجبات.',
    category: 'RESTAURANT',
    specialties: ['Family Restaurant', 'Cafe', 'Fast Food', 'Grill House', 'Seafood', 'Healthy/Diet', 'Street Food', 'Buffet', 'Bakery & Sweets', 'Halal/Kosher'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('inventory', 'Menu items and food categories', 'required'),
      rec('sales', 'Order management and POS for dine-in/takeaway', 'required'),
      rec('bookings', 'Table reservations and booking management', 'recommended'),
      rec('finance', 'Track daily revenue and expenses', 'recommended'),
      rec('marketing', 'Promote daily specials and meal deals', 'recommended'),
      rec('crm', 'Customer loyalty and repeat orders', 'optional'),
      rec('analytics', 'Sales trends and peak hours analysis', 'optional'),
      rec('website', 'Online menu and storefront', 'recommended'),
      rec('hr', 'Staff scheduling for shifts', 'optional'),
    ],
  },
  {
    id: 'grocery',
    categoryId: 'food_market',
    title: 'Supermarket / Grocery',
    titleKey: 'business.types.grocery',
    titleAr: 'سوبر ماركت / بقالة',
    description: 'Daily products, sections, fast stock, offers, and supplies.',
    descriptionAr: 'منتجات يومية، أقسام، مخزون سريع، عروض، ومستلزمات.',
    category: 'FOOD',
    specialties: ['Supermarket', 'Grocery', 'Herbs & Spices', 'Fruits & Vegetables', 'Canned Goods', 'Dairy & Fish', 'Bakery', 'Home Supply', 'Online Grocery', 'Wholesale'],
    themeActivityId: 'grocery',
    recommendedModules: [
      rec('inventory', 'Product catalog with categories and stock', 'required'),
      rec('sales', 'POS checkout and order management', 'required'),
      rec('finance', 'Track expenses and supplier payments', 'recommended'),
      rec('marketing', 'Bundle offers and weekly promotions', 'recommended'),
      rec('analytics', 'Inventory turnover and sales reports', 'recommended'),
      rec('crm', 'Customer tracking for loyalty', 'optional'),
      rec('website', 'Online store with delivery', 'optional'),
      rec('hr', 'Staff management for multiple shifts', 'optional'),
    ],
  },
  {
    id: 'fashion',
    categoryId: 'fashion_home',
    title: 'Clothing / Shoes / Accessories',
    titleKey: 'business.types.fashion',
    titleAr: 'ملابس / أحذية / إكسسوارات',
    description: 'Sizes, colors, models, seasons, offers, and exchanges.',
    descriptionAr: 'مقاسات، ألوان، موديلات، مواسم، عروض، وتبديل.',
    category: 'FASHION',
    specialties: ['Men Clothing', 'Women Clothing', 'Kids Clothing', 'Shoes', 'Accessories', 'Bags', 'Sportswear', 'Wedding Wear', 'Plus Size', 'Modest Fashion'],
    themeActivityId: 'fashion',
    recommendedModules: [
      rec('inventory', 'Product variants: sizes, colors, collections', 'required'),
      rec('sales', 'Orders, exchanges, and returns', 'required'),
      rec('marketing', 'Seasonal sales and collection launches', 'recommended'),
      rec('crm', 'Customer profiles and purchase history', 'recommended'),
      rec('analytics', 'Best-selling products and trends', 'optional'),
      rec('website', 'Online store with product catalog', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'optional'),
    ],
  },
  {
    id: 'homeTextiles',
    categoryId: 'fashion_home',
    title: 'Home Textiles & Curtains',
    titleKey: 'business.types.homeTextiles',
    titleAr: 'منسوجات وستائر',
    description: 'Measurements, materials, tailoring, installation, and catalogs.',
    descriptionAr: 'مقاسات، خامات، تفصيل، تركيب، وكتالوجات.',
    category: 'RETAIL',
    specialties: ['Carpets', 'Curtains', 'Bedding', 'Quilts & Blankets', 'Towels', 'Sofa Covers', 'Prayer Rugs', 'Tents', 'Tablecloths', 'Floor Coverings'],
    themeActivityId: 'homeTextiles',
    recommendedModules: [
      rec('inventory', 'Product catalog with measurements', 'required'),
      rec('sales', 'Custom orders and sales tracking', 'required'),
      rec('bookings', 'Installation visits and measurement appointments', 'recommended'),
      rec('website', 'Gallery and product catalog', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'optional'),
      rec('marketing', 'Seasonal promotions', 'optional'),
    ],
  },
  {
    id: 'furniture',
    categoryId: 'fashion_home',
    title: 'Furniture & Decor',
    titleKey: 'business.types.furniture',
    titleAr: 'أثاث وديكور',
    description: 'Showrooms, rooms, custom manufacturing, delivery, and installation.',
    descriptionAr: 'معارض، غرف، تصنيع حسب الطلب، توصيل، وتركيب.',
    category: 'SERVICE',
    specialties: ['Bedrooms', 'Living Rooms', 'Offices', 'Kitchens', 'Outdoor', 'Hotel Furniture', 'Interior Decor', 'Custom Manufacturing', 'Furniture Showroom', 'Installation'],
    themeActivityId: 'furniture',
    recommendedModules: [
      rec('inventory', 'Showroom catalog and custom products', 'required'),
      rec('sales', 'Orders with delivery and installation', 'required'),
      rec('bookings', 'Delivery and installation scheduling', 'recommended'),
      rec('website', 'Showroom gallery and catalog', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('hr', 'Installation and delivery teams', 'optional'),
    ],
  },
  {
    id: 'goldJewelry',
    categoryId: 'jewelry_luxury',
    title: 'Gold & Jewelry',
    titleKey: 'business.types.goldJewelry',
    titleAr: 'ذهب ومجوهرات',
    description: 'Gold, diamonds, sets, bullion, karats, craftsmanship, and maintenance.',
    descriptionAr: 'ذهب، ماس، طقم، سبائك، عيارات، صناعة، وصيانة.',
    category: 'RETAIL',
    specialties: ['18K Gold', '21K Gold', '24K Gold', 'Diamonds', 'Sets', 'Rings & Couples', 'Bullion', 'Gold Coins', 'Maintenance & Polishing', 'Custom Design'],
    themeActivityId: 'goldJewelry',
    recommendedModules: [
      rec('inventory', 'Jewelry catalog with karat pricing', 'required'),
      rec('sales', 'Sales with gold price tracking', 'required'),
      rec('finance', 'Track revenue, expenses, and gold inventory value', 'recommended'),
      rec('crm', 'VIP customer profiles and purchase history', 'recommended'),
      rec('website', 'Showcase gallery', 'recommended'),
      rec('analytics', 'Sales trends and gold price analysis', 'optional'),
      rec('marketing', 'Special occasion promotions', 'optional'),
    ],
  },
  {
    id: 'watchesGifts',
    categoryId: 'jewelry_luxury',
    title: 'Watches & Luxury Gifts',
    titleKey: 'business.types.watchesGifts',
    titleAr: 'ساعات وهدايا فاخرة',
    description: 'Watches, gift sets, warranty, and after-sales services.',
    descriptionAr: 'ساعات، طقم هدايا، ضمان، وخدمات ما بعد البيع.',
    category: 'RETAIL',
    specialties: ['Men Watches', 'Women Watches', 'Kids Watches', 'Global Brands', 'Sport Watches', 'Classic Watches', 'Perfumes', 'Gift Sets', 'Straps & Batteries', 'Watch Repair'],
    themeActivityId: 'watchesGifts',
    recommendedModules: [
      rec('inventory', 'Watch catalog with brands', 'required'),
      rec('sales', 'Sales with warranty tracking', 'required'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('crm', 'Customer profiles and warranty records', 'recommended'),
      rec('website', 'Showcase gallery', 'recommended'),
      rec('marketing', 'Seasonal gift promotions', 'optional'),
    ],
  },
  {
    id: 'realEstate',
    categoryId: 'real_estate',
    title: 'Real Estate (Buy & Rent)',
    titleKey: 'business.types.realEstate',
    titleAr: 'عقارات (بيع وإيجار)',
    description: 'Apartments, villas, shops, offices, commercial, sales, and rentals.',
    descriptionAr: 'شقق، فلل، محلات، مكاتب، تجاري، بيع، وإيجار.',
    category: 'SERVICE',
    specialties: ['Apartments', 'Villas', 'Shops', 'Offices', 'Commercial', 'Luxury', 'Furnished', 'Installments', 'Viewings', 'Consultations'],
    themeActivityId: 'realEstate',
    recommendedModules: [
      rec('inventory', 'Property listings with details', 'required'),
      rec('sales', 'Sales and rental transactions', 'required'),
      rec('bookings', 'Property viewing appointments', 'recommended'),
      rec('crm', 'Buyer/seller/tenant profiles', 'recommended'),
      rec('website', 'Property showcase website', 'recommended'),
      rec('finance', 'Track commissions and expenses', 'recommended'),
      rec('analytics', 'Market trends and sales analysis', 'optional'),
    ],
  },
  {
    id: 'contractors',
    categoryId: 'real_estate',
    title: 'Contractors & Finishing',
    titleKey: 'business.types.contractors',
    titleAr: 'مقاولات وتشطيب',
    description: 'Construction, finishing, interior design, electrical, plumbing, and painting.',
    descriptionAr: 'بناء، تشطيب، تصميم داخلي، كهرباء، سباكة، ودهان.',
    category: 'SERVICE',
    specialties: ['Apartment Finishing', 'Villa Finishing', 'Interior Design', 'Electrical', 'Plumbing', 'Painting & Decor', 'Carpentry', 'Engineering Supervision', 'General Contracting', 'Restoration'],
    themeActivityId: 'contractors',
    recommendedModules: [
      rec('sales', 'Quotations, project tracking, and contracts', 'required'),
      rec('bookings', 'Site visits and project scheduling', 'recommended'),
      rec('crm', 'Client management and project history', 'recommended'),
      rec('finance', 'Project costs and expense tracking', 'recommended'),
      rec('hr', 'Crew management and labor scheduling', 'recommended'),
      rec('website', 'Portfolio and project showcase', 'recommended'),
      rec('inventory', 'Materials and supplies tracking', 'optional'),
    ],
  },
  {
    id: 'carShowroom',
    categoryId: 'vehicles',
    title: 'Car Showroom',
    titleKey: 'business.types.carShowroom',
    titleAr: 'معرض سيارات',
    description: 'New and used cars, installments, test drives, and inspections.',
    descriptionAr: 'سيارات جديدة ومستعملة، تقسيط، قيادة تجريبية، وفحص.',
    category: 'RETAIL',
    specialties: ['New Cars', 'Used Cars', 'Installments', 'Test Drives', 'Technical Inspection', 'Luxury Cars', 'Economy Cars', 'SUV', 'Electric Cars', 'Trade-in'],
    themeActivityId: 'carShowroom',
    recommendedModules: [
      rec('inventory', 'Vehicle listings with specifications', 'required'),
      rec('sales', 'Sales with financing and installments', 'required'),
      rec('bookings', 'Test drive appointments', 'recommended'),
      rec('crm', 'Buyer profiles and follow-ups', 'recommended'),
      rec('finance', 'Track sales and commissions', 'recommended'),
      rec('website', 'Online showroom', 'recommended'),
      rec('analytics', 'Sales performance analysis', 'optional'),
    ],
  },
  {
    id: 'auto_services',
    categoryId: 'vehicles',
    title: 'Auto Services & Workshop',
    titleKey: 'business.types.autoServices',
    titleAr: 'خدمات سيارات وورشة',
    description: 'Mechanics, electrical, bodywork, painting, maintenance, and washing.',
    descriptionAr: 'ميكانيكا، كهرباء، هياكل، دهان، صيانة، وغسيل.',
    category: 'SERVICE',
    specialties: ['General Mechanics', 'Auto Electrical', 'Body & Paint', 'Periodic Maintenance', 'Full Inspection', 'Wash & Polish', 'Oil Change', 'Tires & Batteries', 'Computer Diagnostics', 'AC Service'],
    themeActivityId: 'auto_services',
    recommendedModules: [
      rec('bookings', 'Service appointments and job orders', 'required'),
      rec('sales', 'Service invoices and payments', 'required'),
      rec('inventory', 'Parts and supplies catalog', 'recommended'),
      rec('hr', 'Technician scheduling and assignments', 'recommended'),
      rec('crm', 'Customer vehicle history', 'recommended'),
      rec('finance', 'Track revenue and workshop expenses', 'recommended'),
      rec('website', 'Service catalog and gallery', 'optional'),
    ],
  },
  {
    id: 'agri_supplies',
    categoryId: 'agriculture',
    title: 'Agriculture Supplies',
    titleKey: 'business.types.agriSupplies',
    titleAr: 'مستلزمات زراعية',
    description: 'Seeds, seedlings, fertilizers, pesticides, irrigation, and farm supplies.',
    descriptionAr: 'بذور، شتلات، أسمدة، مبيدات، ري، ومستلزمات زراعية.',
    category: 'RETAIL',
    specialties: ['Seeds', 'Seedlings', 'Fertilizers', 'Pesticides', 'Irrigation Tools', 'Soil & Compost', 'Animal Feed', 'Farm Equipment', 'Pest Control', 'Agricultural Consulting'],
    themeActivityId: 'agri_supplies',
    recommendedModules: [
      rec('inventory', 'Product catalog with categories', 'required'),
      rec('sales', 'Sales and POS', 'required'),
      rec('finance', 'Track revenue and supplier payments', 'recommended'),
      rec('marketing', 'Seasonal promotions', 'recommended'),
      rec('website', 'Online store', 'optional'),
      rec('analytics', 'Sales reports', 'optional'),
    ],
  },
  {
    id: 'serviceCompanies',
    categoryId: 'services',
    title: 'Service Company',
    titleKey: 'business.types.serviceCompanies',
    titleAr: 'شركة خدمات',
    description: 'Maintenance, cleaning, security, transport, facility management.',
    descriptionAr: 'صيانة، تنظيف، أمن، نقل، وإدارة مرافق.',
    category: 'SERVICE',
    specialties: ['General Maintenance', 'Cleaning', 'Security', 'Transport', 'Facility Management', 'Real Estate Services', 'Landscaping', 'Pest Control', 'Annual Contracts', 'Corporate Services'],
    themeActivityId: 'serviceCompanies',
    recommendedModules: [
      rec('bookings', 'Service scheduling and team dispatch', 'required'),
      rec('sales', 'Service contracts and invoices', 'required'),
      rec('hr', 'Team management and shift scheduling', 'recommended'),
      rec('crm', 'Client contracts and service history', 'recommended'),
      rec('finance', 'Track revenue and operational costs', 'recommended'),
      rec('website', 'Service catalog and portfolio', 'recommended'),
      rec('analytics', 'Performance and revenue analysis', 'optional'),
    ],
  },
  {
    id: 'individualTechnicians',
    categoryId: 'services',
    title: 'Individual Technician',
    titleKey: 'business.types.individualTechnicians',
    titleAr: 'فني فرد',
    description: 'Plumber, electrician, carpenter, painter, AC, appliance repair, home visits.',
    descriptionAr: 'سباك، كهربائي، نجار، دهان، تكييف، تصليح أجهزة، زيارات منزلية.',
    category: 'SERVICE',
    specialties: ['Plumber', 'Electrician', 'Carpenter', 'Painter', 'AC Technician', 'Appliance Repair', 'Welding', 'Aluminum', 'Painting', 'General Maintenance'],
    themeActivityId: 'individualTechnicians',
    recommendedModules: [
      rec('bookings', 'Visit scheduling and appointment management', 'required'),
      rec('sales', 'Service invoices and payment tracking', 'required'),
      rec('crm', 'Customer profiles and service history', 'recommended'),
      rec('finance', 'Track income and expenses', 'recommended'),
      rec('website', 'Service showcase and gallery', 'recommended'),
      rec('marketing', 'Promote services', 'optional'),
    ],
  },
  {
    id: 'electronics',
    categoryId: 'electronics_health',
    title: 'Computers & Mobiles',
    titleKey: 'business.types.electronics',
    titleAr: 'حواسيب وجوالات',
    description: 'Devices, accessories, repairs, warranty, parts, and supplies.',
    descriptionAr: 'أجهزة، إكسسوارات، تصليح، ضمان، قطع، ومستلزمات.',
    category: 'ELECTRONICS',
    specialties: ['Mobiles', 'Laptops', 'Tablets', 'Accessories', 'Mobile Repair', 'Computer Repair', 'Monitors', 'Headphones', 'Cameras', 'Gaming'],
    themeActivityId: 'electronics',
    recommendedModules: [
      rec('inventory', 'Device catalog with specs and warranty', 'required'),
      rec('sales', 'Sales and POS', 'required'),
      rec('bookings', 'Repair service appointments', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('crm', 'Customer profiles and warranty records', 'recommended'),
      rec('website', 'Online store', 'recommended'),
      rec('marketing', 'Promotions and new arrivals', 'optional'),
      rec('analytics', 'Sales and repair revenue analysis', 'optional'),
    ],
  },
  {
    id: 'health',
    categoryId: 'electronics_health',
    title: 'Pharmacy / Health',
    titleKey: 'business.types.health',
    titleAr: 'صيدلية / صحة',
    description: 'Medicines, cosmetics, medical devices, prescriptions, and refills.',
    descriptionAr: 'أدوية، مستحضرات تجميل، أجهزة طبية، وصفات، وتجديد.',
    category: 'HEALTH',
    specialties: ['Pharmacy', 'Medicines', 'Cosmetics', 'Medical Devices', 'Supplements', 'Personal Care', 'Kids Medicine', 'Chronic Disease Meds', 'Prescriptions', 'Medicine Delivery'],
    themeActivityId: 'health',
    recommendedModules: [
      rec('inventory', 'Medicine catalog with expiry tracking', 'required'),
      rec('sales', 'Sales and POS', 'required'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('crm', 'Customer profiles and prescription history', 'recommended'),
      rec('analytics', 'Sales reports and inventory analysis', 'recommended'),
      rec('website', 'Online ordering for refills', 'optional'),
      rec('marketing', 'Health awareness promotions', 'optional'),
    ],
  },
  {
    id: 'factories',
    categoryId: 'industrial_trade',
    title: 'Factory / Production Line',
    titleKey: 'business.types.factories',
    titleAr: 'مصنع / خط إنتاج',
    description: 'Raw materials, suppliers, warehouses, production lines, and quality.',
    descriptionAr: 'خامات، موردين، مخازن، خطوط إنتاج، وجودة.',
    category: 'RETAIL',
    specialties: ['Food', 'Plastic', 'Metal', 'Chemical', 'Textile', 'Wood', 'Paper & Printing', 'Packaging', 'Beverages', 'Household Goods'],
    themeActivityId: 'factories',
    recommendedModules: [
      rec('inventory', 'Raw materials and finished goods tracking', 'required'),
      rec('sales', 'Order management and B2B sales', 'required'),
      rec('finance', 'Track production costs and revenue', 'recommended'),
      rec('hr', 'Worker management and shift scheduling', 'recommended'),
      rec('analytics', 'Production and sales analysis', 'recommended'),
      rec('website', 'Product catalog', 'optional'),
      rec('marketing', 'B2B promotions', 'optional'),
    ],
  },
  {
    id: 'tradeCompanies',
    categoryId: 'industrial_trade',
    title: 'Trading / Import / Export',
    titleKey: 'business.types.tradeCompanies',
    titleAr: 'تجارة / استيراد / تصدير',
    description: 'Suppliers, distributors, shipping, warehouses, import, and export.',
    descriptionAr: 'موردين، موزعين، شحن، مخازن، استيراد، وتصدير.',
    category: 'RETAIL',
    specialties: ['Import', 'Export', 'Wholesale Distribution', 'International Shipping', 'Local Shipping', 'Warehousing', 'Packaging', 'Agencies', 'E-commerce', 'General Trading'],
    themeActivityId: 'tradeCompanies',
    recommendedModules: [
      rec('inventory', 'Product catalog and warehouse management', 'required'),
      rec('sales', 'B2B orders and wholesale', 'required'),
      rec('finance', 'Track revenue, shipping costs, and expenses', 'recommended'),
      rec('crm', 'Supplier and distributor management', 'recommended'),
      rec('analytics', 'Sales and inventory analysis', 'recommended'),
      rec('website', 'Wholesale catalog', 'optional'),
      rec('marketing', 'Trade promotions', 'optional'),
    ],
  },
  {
    id: 'tourismTravel',
    categoryId: 'tourism_travel',
    title: 'Tourism & Travel',
    titleKey: 'business.types.tourismTravel',
    titleAr: 'سياحة وسفر',
    description: 'Hotels, tours, flights, travel insurance, programs, and guides.',
    descriptionAr: 'فنادق، جولات، طيران، تأمين سفر، برامج، ومرشدين.',
    category: 'SERVICE',
    specialties: ['Domestic Tours', 'International Tours', 'Umrah & Hajj', 'Hotel Bookings', 'Flight Tickets', 'Travel Insurance', 'Tour Guide', 'Car Rental', 'Family Packages', 'Honeymoon Packages'],
    themeActivityId: 'tourismTravel',
    recommendedModules: [
      rec('bookings', 'Tour, hotel, and flight bookings', 'required'),
      rec('sales', 'Booking payments and invoices', 'required'),
      rec('crm', 'Customer profiles and booking history', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Tour packages showcase', 'recommended'),
      rec('marketing', 'Seasonal travel promotions', 'recommended'),
      rec('analytics', 'Booking trends analysis', 'optional'),
    ],
  },
  {
    id: 'livestock',
    categoryId: 'livestock_fisheries',
    title: 'Livestock',
    titleKey: 'business.types.livestock',
    titleAr: 'ثروة حيوانية',
    description: 'Feed, medicines, veterinary, equipment, transport, and slaughter.',
    descriptionAr: 'أعلاف، أدوية، بيطرة، معدات، نقل، وذبح.',
    category: 'RETAIL',
    specialties: ['Poultry', 'Cattle', 'Sheep', 'Goats', 'Horses', 'Feed', 'Veterinary Medicine', 'Slaughter', 'Animal Transport', 'Farm Equipment'],
    themeActivityId: 'livestock',
    recommendedModules: [
      rec('inventory', 'Product and supply catalog', 'required'),
      rec('sales', 'Sales and POS', 'required'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Product catalog', 'optional'),
      rec('analytics', 'Sales reports', 'optional'),
    ],
  },
  {
    id: 'fisheries',
    categoryId: 'livestock_fisheries',
    title: 'Fisheries',
    titleKey: 'business.types.fisheries',
    titleAr: 'مصايد أسماك',
    description: 'Fry, feed, equipment, cooling, transport, and fish export.',
    descriptionAr: 'زراعة، أعلاف، معدات، تبريد، نقل، وتصدير أسماك.',
    category: 'RETAIL',
    specialties: ['Fish Farming', 'Fry', 'Fish Feed', 'Fishing Equipment', 'Cooling', 'Fish Transport', 'Fish Export', 'Fresh Fish', 'Shrimp', 'Seafood'],
    themeActivityId: 'fisheries',
    recommendedModules: [
      rec('inventory', 'Product and equipment catalog', 'required'),
      rec('sales', 'Sales and POS', 'required'),
      rec('finance', 'Track revenue and export costs', 'recommended'),
      rec('website', 'Product catalog', 'optional'),
      rec('analytics', 'Sales reports', 'optional'),
    ],
  },
  {
    id: 'energy',
    categoryId: 'energy',
    title: 'Energy & Electrical',
    titleKey: 'business.types.energy',
    titleAr: 'طاقة وكهرباء',
    description: 'Solar panels, batteries, generators, installation, and maintenance.',
    descriptionAr: 'ألواح شمسية، بطاريات، مولدات، تركيب، وصيانة.',
    category: 'SERVICE',
    specialties: ['Solar Energy', 'Batteries', 'Generators', 'Inverters', 'Home Electrical', 'Industrial Electrical', 'Energy Maintenance', 'Panel Installation', 'Cables & Switches', 'Grounding & Protection'],
    themeActivityId: 'energy',
    recommendedModules: [
      rec('inventory', 'Equipment catalog with specs', 'required'),
      rec('sales', 'Sales and installation contracts', 'required'),
      rec('bookings', 'Installation and maintenance appointments', 'recommended'),
      rec('hr', 'Installation team management', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Product catalog and services', 'recommended'),
      rec('crm', 'Customer profiles and service history', 'optional'),
    ],
  },
  {
    id: 'professionalServices',
    categoryId: 'professional_services',
    title: 'Professional Services',
    titleKey: 'business.types.professionalServices',
    titleAr: 'خدمات مهنية',
    description: 'Accounting, legal, translation, design, programming, consulting.',
    descriptionAr: 'محاسبة، قانوني، ترجمة، تصميم، برمجة، استشارات.',
    category: 'SERVICE',
    specialties: ['Accountant', 'Lawyer', 'Translator', 'Graphic Designer', 'Programmer', 'Financial Advisor', 'Management Consultant', 'Marketing Expert', 'Real Estate Consultant', 'Business Coach'],
    themeActivityId: 'professionalServices',
    recommendedModules: [
      rec('bookings', 'Appointment scheduling', 'required'),
      rec('sales', 'Service invoices and contracts', 'required'),
      rec('crm', 'Client management and case history', 'recommended'),
      rec('finance', 'Track income and expenses', 'recommended'),
      rec('website', 'Portfolio and service showcase', 'recommended'),
      rec('marketing', 'Promote professional services', 'optional'),
    ],
  },
  {
    id: 'homeServices',
    categoryId: 'home_services',
    title: 'Home Services',
    titleKey: 'business.types.homeServices',
    titleAr: 'خدمات منزلية',
    description: 'Plumbing, electrical, carpentry, painting, AC, cleaning, and home visits.',
    descriptionAr: 'سباكة، كهرباء، نجارة، دهان، تكييف، تنظيف، وزيارات منزلية.',
    category: 'SERVICE',
    specialties: ['Plumber', 'Electrician', 'Carpenter', 'Painter', 'AC', 'Cleaning', 'Appliance Repair', 'Furniture Assembly', 'Tank Cleaning', 'Leak Detection'],
    themeActivityId: 'homeServices',
    recommendedModules: [
      rec('bookings', 'Visit scheduling and booking management', 'required'),
      rec('sales', 'Service invoices and payment tracking', 'required'),
      rec('crm', 'Customer profiles and service history', 'recommended'),
      rec('finance', 'Track income and expenses', 'recommended'),
      rec('website', 'Service showcase and before/after gallery', 'recommended'),
      rec('hr', 'Technician management', 'optional'),
      rec('marketing', 'Promote services', 'optional'),
    ],
  },
  {
    id: 'other',
    categoryId: 'other',
    title: 'Other Business',
    titleKey: 'business.types.other',
    titleAr: 'نشاط آخر',
    description: 'Start with general modules and customize as needed.',
    descriptionAr: 'ابدأ بوحدات عامة وخصص حسب الحاجة.',
    category: 'OTHER',
    specialties: [],
    themeActivityId: 'other',
    recommendedModules: [
      rec('inventory', 'Product or service catalog', 'recommended'),
      rec('sales', 'Order and payment management', 'recommended'),
      rec('website', 'Storefront and page builder', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'optional'),
      rec('marketing', 'Promotions and offers', 'optional'),
      rec('crm', 'Customer management', 'optional'),
      rec('analytics', 'Business reports', 'optional'),
    ],
  },
  {
    id: 'clinic',
    categoryId: 'bookings',
    title: 'Clinic / Medical',
    titleKey: 'business.types.clinic',
    titleAr: 'عيادة / طبية',
    description: 'Medical clinics, dental, dermatology, and healthcare appointments.',
    descriptionAr: 'عيادات طبية، أسنان، جلدية، ومواعيد رعاية صحية.',
    category: 'SERVICE',
    specialties: ['General Practice', 'Dental', 'Dermatology', 'Pediatrics', 'Orthopedics', 'ENT', 'Eye Clinic', 'Physical Therapy', 'Mental Health', 'Nutrition'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Patient appointments and scheduling', 'required'),
      rec('sales', 'Session payments and invoices', 'required'),
      rec('crm', 'Patient records and medical history', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Clinic website with services', 'recommended'),
      rec('hr', 'Doctor and staff scheduling', 'optional'),
      rec('analytics', 'Patient flow and revenue analysis', 'optional'),
    ],
  },
  {
    id: 'salon_barber',
    categoryId: 'bookings',
    title: 'Salon / Barber',
    titleKey: 'business.types.salonBarber',
    titleAr: 'صالون / حلاقة',
    description: 'Hair, beauty, grooming services with chair/station management.',
    descriptionAr: 'شعر، تجميل، خدمات عناية مع إدارة كراسي/محطات.',
    category: 'SERVICE',
    specialties: ['Men Salon', 'Women Salon', 'Hair Styling', 'Nails', 'Makeup', 'Spa', 'Barber', 'Kids Salon', 'Bridal', 'Massage'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Appointment scheduling with chairs', 'required'),
      rec('sales', 'Service payments and POS', 'required'),
      rec('crm', 'Customer profiles and service history', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Service menu and gallery', 'recommended'),
      rec('hr', 'Stylist scheduling', 'optional'),
      rec('marketing', 'Promotions and loyalty', 'optional'),
    ],
  },
  {
    id: 'wellness_spa',
    categoryId: 'bookings',
    title: 'Wellness / Spa',
    titleKey: 'business.types.wellnessSpa',
    titleAr: 'سبا واسترخاء',
    description: 'Spa sessions, wellness treatments, and relaxation services.',
    descriptionAr: 'جلسات سبا، علاجات استرخاء، وخدمات رعاية.',
    category: 'SERVICE',
    specialties: ['Massage', 'Sauna', 'Facial', 'Aromatherapy', 'Hot Stone', 'Reflexology', 'Body Treatment', 'Couples Spa', 'Day Spa', 'Holistic Wellness'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Session booking with room management', 'required'),
      rec('sales', 'Service payments and packages', 'required'),
      rec('crm', 'Customer profiles and preferences', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Service showcase and gallery', 'recommended'),
      rec('hr', 'Therapist scheduling', 'optional'),
      rec('marketing', 'Wellness packages and promotions', 'optional'),
    ],
  },
  {
    id: 'chalets_resorts',
    categoryId: 'bookings',
    title: 'Chalets / Resorts',
    titleKey: 'business.types.chaletsResorts',
    titleAr: 'شاليهات ومنتجعات',
    description: 'Chalet, cabin, and resort bookings with unit management.',
    descriptionAr: 'حجوزات شاليهات، كبائن، ومنتجعات مع إدارة وحدات.',
    category: 'SERVICE',
    specialties: ['Chalets', 'Cabins', 'Resort Rooms', 'Pool Villas', 'Farm Stays', 'Glamping', 'Beach Resorts', 'Mountain Resorts', 'Family Resorts', 'Luxury Resorts'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Unit booking and availability calendar', 'required'),
      rec('sales', 'Booking payments and invoices', 'required'),
      rec('crm', 'Guest profiles and booking history', 'recommended'),
      rec('finance', 'Track revenue and maintenance costs', 'recommended'),
      rec('website', 'Unit showcase and booking', 'recommended'),
      rec('hr', 'Staff and housekeeping scheduling', 'optional'),
      rec('analytics', 'Occupancy and revenue analysis', 'optional'),
    ],
  },
  {
    id: 'hotels_rooms',
    categoryId: 'bookings',
    title: 'Hotels / Rooms',
    titleKey: 'business.types.hotelsRooms',
    titleAr: 'فنادق / غرف',
    description: 'Hotel rooms, suites, check-in/out, and hospitality management.',
    descriptionAr: 'غرف فنادق، أجنحة، تسجيل دخول/خروج، وإدارة ضيافة.',
    category: 'SERVICE',
    specialties: ['Budget Hotel', 'Business Hotel', 'Boutique Hotel', 'Luxury Hotel', 'Serviced Apartments', 'Guest House', 'Hostel', 'Resort Hotel', 'Airport Hotel', 'Extended Stay'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Room booking and check-in/out', 'required'),
      rec('sales', 'Booking payments and invoices', 'required'),
      rec('crm', 'Guest profiles and preferences', 'recommended'),
      rec('finance', 'Track revenue and operational costs', 'recommended'),
      rec('website', 'Room showcase and online booking', 'recommended'),
      rec('hr', 'Staff shift management', 'recommended'),
      rec('analytics', 'Occupancy rates and revenue analysis', 'recommended'),
    ],
  },
  {
    id: 'events_venues',
    categoryId: 'bookings',
    title: 'Events / Venues',
    titleKey: 'business.types.eventsVenues',
    titleAr: 'فعاليات وقاعات',
    description: 'Event halls, wedding venues, conference rooms, and party spaces.',
    descriptionAr: 'قاعات فعاليات، أعراس، مؤتمرات، ومناسبات.',
    category: 'SERVICE',
    specialties: ['Wedding Halls', 'Conference Rooms', 'Party Halls', 'Exhibition Spaces', 'Corporate Events', 'Birthday Venues', 'Outdoor Venues', 'Meeting Rooms', 'Concert Halls', 'Banquet Halls'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Venue booking and event scheduling', 'required'),
      rec('sales', 'Booking payments and catering invoices', 'required'),
      rec('crm', 'Client profiles and event history', 'recommended'),
      rec('finance', 'Track revenue and event costs', 'recommended'),
      rec('website', 'Venue showcase and gallery', 'recommended'),
      rec('hr', 'Event staff scheduling', 'recommended'),
      rec('marketing', 'Event packages and promotions', 'optional'),
    ],
  },
  {
    id: 'sports_trainers',
    categoryId: 'bookings',
    title: 'Sports / Trainers',
    titleKey: 'business.types.sportsTrainers',
    titleAr: 'رياضة ومدربين',
    description: 'Personal training, coaching sessions, and sports facility bookings.',
    descriptionAr: 'تدريب شخصي، جلسات تدريب، وحجوزات مرافق رياضية.',
    category: 'SERVICE',
    specialties: ['Personal Trainer', 'Yoga', 'Pilates', 'Martial Arts', 'Swimming', 'Tennis', 'Football', 'Basketball', 'CrossFit', 'Dance'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Session and facility booking', 'required'),
      rec('sales', 'Session payments and memberships', 'required'),
      rec('crm', 'Member profiles and progress tracking', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Service showcase', 'recommended'),
      rec('hr', 'Trainer scheduling', 'optional'),
      rec('marketing', 'Membership promotions', 'optional'),
    ],
  },
  {
    id: 'education_courses',
    categoryId: 'bookings',
    title: 'Education / Courses',
    titleKey: 'business.types.educationCourses',
    titleAr: 'تعليم ودورات',
    description: 'Courses, classes, workshops, and training sessions.',
    descriptionAr: 'دورات، فصول، ورش، وجلسات تدريب.',
    category: 'SERVICE',
    specialties: ['Language Courses', 'Computer Training', 'Professional Certification', 'Kids Classes', 'Music Lessons', 'Art Classes', 'Cooking Classes', 'Driving School', 'Tutoring', 'Online Courses'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Class scheduling and enrollment', 'required'),
      rec('sales', 'Course payments and invoices', 'required'),
      rec('crm', 'Student profiles and progress', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Course catalog and showcase', 'recommended'),
      rec('hr', 'Instructor scheduling', 'optional'),
      rec('analytics', 'Enrollment and revenue analysis', 'optional'),
    ],
  },
  {
    id: 'maintenance_services',
    categoryId: 'bookings',
    title: 'Maintenance Services',
    titleKey: 'business.types.maintenanceServices',
    titleAr: 'خدمات صيانة',
    description: 'Equipment maintenance, repair services, and scheduled visits.',
    descriptionAr: 'صيانة معدات، خدمات تصليح، وزيارات مجدولة.',
    category: 'SERVICE',
    specialties: ['AC Maintenance', 'Appliance Repair', 'Elevator Maintenance', 'Generator Maintenance', 'IT Support', 'Security Systems', 'Solar Maintenance', 'Plumbing', 'Electrical', 'General Repair'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Service call scheduling and dispatch', 'required'),
      rec('sales', 'Service invoices and contracts', 'required'),
      rec('crm', 'Customer profiles and service history', 'recommended'),
      rec('finance', 'Track revenue and costs', 'recommended'),
      rec('hr', 'Technician scheduling and assignments', 'recommended'),
      rec('website', 'Service catalog', 'optional'),
    ],
  },
  {
    id: 'general_appointments',
    categoryId: 'bookings',
    title: 'General Appointments',
    titleKey: 'business.types.generalAppointments',
    titleAr: 'مواعيد عامة',
    description: 'Any appointment-based business with flexible scheduling.',
    descriptionAr: 'أي نشاط يعتمد على المواعيد مع جدولة مرنة.',
    category: 'SERVICE',
    specialties: ['Consultations', 'Meetings', 'Sessions', 'Appointments', 'Bookings', 'Visits'],
    themeActivityId: 'restaurant',
    recommendedModules: [
      rec('bookings', 'Appointment scheduling and calendar', 'required'),
      rec('sales', 'Session payments and invoices', 'required'),
      rec('crm', 'Customer profiles and history', 'recommended'),
      rec('finance', 'Track revenue and expenses', 'recommended'),
      rec('website', 'Service showcase', 'optional'),
    ],
  },
];

export const getBusinessTypesByCategory = (categoryId: string): BusinessTypeDef[] =>
  BUSINESS_TYPES.filter((t) => t.categoryId === categoryId);

export const getBusinessTypeById = (id: string): BusinessTypeDef | undefined =>
  BUSINESS_TYPES.find((t) => t.id === id);

export const getBusinessCategoryById = (id: string): BusinessCategoryDef | undefined =>
  BUSINESS_CATEGORIES.find((c) => c.id === id);
