import { PromptSuggestion, SectorActivity, CommerceTemplate, FaqItem } from '@/nammy/types';

export const PROMPT_SUGGESTIONS: PromptSuggestion[] = [
  {
    id: 'apparel',
    query: 'أزياء وملابس',
    queryEn: 'Fashion & Apparel',
    icon: 'Shirt',
    category: 'fashion',
    aiResponse: {
      headline: 'تجهيز متجر أزياء وملابس بالذكاء الاصطناعي',
      description: 'متجر ملابس نسائية أنيق بالدفع عند الاستلام وإدارة المقاسات والألوان.',
      metric: {
        label: 'جاهزية الثيم والمقاسات',
        value: '100% تلقائي',
        change: 'جاهز للبدء فوراً',
      },
      actionText: 'بدء تهيئة متجر الأزياء',
      actionType: 'product',
      details: [
        'توليد الثيم والألوان الأنيقة المتوافقة مع هوية براندك',
        'إعداد مصفوفة المقاسات والألوان (S, M, L / ألوان متعددة)',
        'تفعيل الدفع عند الاستلام وبوابات الدفع الإلكتروني فورياً',
        'التحويل المباشر للوحة التحكم لإضافة باقي المنتجات',
      ],
    },
    aiResponseEn: {
      headline: 'AI Fashion & Boutique Setup',
      description: 'Elegant boutique store with cash on delivery and size/color matrix.',
      metric: {
        label: 'Theme & Sizing Readiness',
        value: '100% Automated',
        change: 'Ready to launch',
      },
      actionText: 'Configure Fashion Store',
      actionType: 'product',
      details: [
        'Generate bespoke luxury theme matching your brand aesthetic',
        'Configure size and color variant matrix out-of-the-box',
        'Instant activation of Cash on Delivery and online cards',
        'Seamless transition to main catalog dashboard',
      ],
    },
  },
  {
    id: 'beauty',
    query: 'تجميل وعناية',
    queryEn: 'Beauty & Skincare',
    icon: 'Sparkles',
    category: 'beauty',
    aiResponse: {
      headline: 'تجهيز متجر تجميل وعناية بالذكاء الاصطناعي',
      description: 'منتجات تجميل مع باقات وعروض ترويجية ورسائل ولاء للعملاء.',
      metric: {
        label: 'نظام الباقات والولاء',
        value: 'مفعل بالكامل',
        change: 'زيادة الطلب المتكرر',
      },
      actionText: 'بدء تهيئة متجر التجميل',
      actionType: 'discount',
      details: [
        'توليد ثيم جمالي ناعم يبرز عبوات وتفاصيل مستحضرات التجميل',
        'إعداد باقات المنتجات والعروض الترويجية الأكثر طلباً',
        'تفعيل رسائل المتابعة وحملات استرجاع وتكرار الشراء',
        'التحويل التلقائي للوحة التحكم مع كاشير مخصص للصالونات والمتاجر',
      ],
    },
    aiResponseEn: {
      headline: 'AI Beauty & Cosmetics Setup',
      description: 'Cosmetics store with curated bundles, promotional sets and loyalty CRM.',
      metric: {
        label: 'Bundles & Loyalty',
        value: 'Active',
        change: 'Boost repeat orders',
      },
      actionText: 'Configure Beauty Store',
      actionType: 'discount',
      details: [
        'Bespoke aesthetics highlighting product formulations and textures',
        'Pre-configured bundle builder for high-value sales',
        'Automated loyalty point engine and retention notifications',
        'Direct link to cloud register and centralized inventory',
      ],
    },
  },
  {
    id: 'food',
    query: 'طعام ومنتجات محلية',
    queryEn: 'Food & Local Produce',
    icon: 'Apple',
    category: 'food',
    aiResponse: {
      headline: 'تجهيز متجر طعام ومنتجات محلية بالذكاء الاصطناعي',
      description: 'طلبات يومية وتوصيل حسب المناطق ومنتجات متكررة.',
      metric: {
        label: 'نطاق التوصيل اليومي',
        value: 'تلقائي حسب الحي',
        change: 'سرعة تحضير وشحن',
      },
      actionText: 'بدء تهيئة متجر الطعام',
      actionType: 'growth',
      details: [
        'تحديد نطاقات ومناطق التوصيل ورسوم الشحن لكل حي ومحافظة',
        'إعداد قوائم الوجبات والمنتجات المتكررة ومواعيد التوصيل',
        'ربط طابعات المطبخ والأوردرات السريعة مع كاشير الكلاود',
        'النقل المباشر للوحة تحكم العمليات والتوصيل الفوري',
      ],
    },
    aiResponseEn: {
      headline: 'AI Food & Local Marketplace Setup',
      description: 'Daily recurring orders, regional zones and express dispatch.',
      metric: {
        label: 'Delivery Logistics',
        value: 'Automated by Zone',
        change: 'Express dispatch',
      },
      actionText: 'Configure Food Store',
      actionType: 'growth',
      details: [
        'Define regional dispatch zones and neighborhood delivery rates',
        'Configure daily recurring consumables and order cycles',
        'Instant cloud POS kitchen display integration',
        'Immediate onboarding into order management hub',
      ],
    },
  },
  {
    id: 'electronics',
    query: 'إلكترونيات وإكسسوارات',
    queryEn: 'Electronics & Gadgets',
    icon: 'Smartphone',
    category: 'tech',
    aiResponse: {
      headline: 'تجهيز متجر إلكترونيات وإكسسوارات بالذكاء الاصطناعي',
      description: 'أجهزة بمتغيرات وتتبع للمخزون وسريال الضمان وخدمة ما بعد البيع.',
      metric: {
        label: 'تتبع السيريال والضمان',
        value: 'فوري برقم الهيكل',
        change: 'أمان كامل للعميل',
      },
      actionText: 'بدء تهيئة متجر الإلكترونيات',
      actionType: 'product',
      details: [
        'إعداد تتبع الأرقام التسلسلية (Serial Numbers) لشهادات الضمان',
        'مزامنة المخزون بين المعرض والمستودعات بشكل لحظي',
        'نماذج متابعة الصيانة وخدمة ما بعد البيع والاستبدال',
        'تحويل كل الأجهزة فورياً للوحة المبيعات المركزية',
      ],
    },
    aiResponseEn: {
      headline: 'AI Electronics & Hardware Setup',
      description: 'Multi-spec devices, serial warranty, and after-sales support.',
      metric: {
        label: 'Serial & Warranty',
        value: 'Automated per Unit',
        change: 'Full audit trail',
      },
      actionText: 'Configure Tech Store',
      actionType: 'product',
      details: [
        'Map individual unit serial numbers to electronic warranty certificates',
        'Real-time multi-branch warehouse synchronization',
        'Integrated RMA, repair ticketing and return workflows',
        'Seamless handoff to central operational dashboard',
      ],
    },
  },
  {
    id: 'home',
    query: 'منزل ونمط حياة',
    queryEn: 'Home & Living',
    icon: 'Home',
    category: 'lifestyle',
    aiResponse: {
      headline: 'تجهيز متجر منزل ونمط حياة بالذكاء الاصطناعي',
      description: 'منتجات منزلية بأقسام منظمة وعرض بصري جذاب وتجهيز سريع.',
      metric: {
        label: 'تصنيف الأقسام',
        value: 'منظم لكل غرفة',
        change: 'تجربة تسوق سهلة',
      },
      actionText: 'بدء تهيئة متجر المنزل',
      actionType: 'growth',
      details: [
        'تنظيم الأقسام حسب غرف ومساحات المنزل وديكوراته',
        'معرض صور عالي الدقة لعرض المنتجات بأبعادها وتفاصيلها',
        'تتبع أذون التجهيز والتغليف للشحن المنزلي السريع',
        'التحويل المباشر لشاشة الإدارة والمخزون',
      ],
    },
    aiResponseEn: {
      headline: 'AI Home & Living Store Setup',
      description: 'Structured room categories, visual gallery and bulk fulfillment.',
      metric: {
        label: 'Room Categorization',
        value: 'Structured',
        change: 'High conversion',
      },
      actionText: 'Configure Home Store',
      actionType: 'growth',
      details: [
        'Organize categories by room and living spaces',
        'High-resolution imagery showcase with sizing dimensions',
        'Order packing slips and bulk courier fulfillment setup',
        'Direct onboarding into merchant catalog console',
      ],
    },
  },
  {
    id: 'accessories',
    query: 'إكسسوارات',
    queryEn: 'Accessories & Watches',
    icon: 'Watch',
    category: 'luxury',
    aiResponse: {
      headline: 'تجهيز متجر إكسسوارات ومجوهرات بالذكاء الاصطناعي',
      description: 'حقائب وساعات ومجوهرات بإطلالة أنيقة وفخامة تسويقية.',
      metric: {
        label: 'طابع الفخامة والإهداء',
        value: 'مفعل بلمسة واحدة',
        change: 'قيمة إضافية للبراند',
      },
      actionText: 'بدء تهيئة متجر الإكسسوارات',
      actionType: 'product',
      details: [
        'واجهة فاخرة مع صور مكبرة وتفاصيل القطع الثمينة',
        'خيارات التغليف الإهدائي وإرفاق كروت الإهداء للعملاء',
        'ربط مباشر مع الشحن السريع وبوابات الدفع الإلكتروني',
        'إطلاق المتجر فورياً في لوحة التحكم',
      ],
    },
    aiResponseEn: {
      headline: 'AI Luxury Accessories Setup',
      description: 'Bags, timepieces and fine jewelry presented in high luxury aesthetics.',
      metric: {
        label: 'Luxury Aesthetic',
        value: 'Activated',
        change: 'High brand perception',
      },
      actionText: 'Configure Accessories Store',
      actionType: 'product',
      details: [
        'High-contrast luxury theme with macro zoom viewing',
        'Gift packaging options and personalized card messaging',
        'Direct gateway connectivity for instant card checkout',
        'Instant deployment into cloud inventory system',
      ],
    },
  },
  {
    id: 'wholesale-retail',
    query: 'جملة وتجزئة',
    queryEn: 'Wholesale & Retail B2B',
    icon: 'Layers',
    category: 'wholesale',
    aiResponse: {
      headline: 'تجهيز منظومة جملة وتجزئة بالذكاء الاصطناعي',
      description: 'مخزون مجمّع، طلبات متكررة، أسعار شرائح، تقارير وصلاحيات فريق.',
      metric: {
        label: 'أسعار الشرائح والآجل',
        value: 'جاهزة للتشغيل',
        change: 'أتمتة أوامر الشراء',
      },
      actionText: 'بدء تهيئة منظومة الجملة',
      actionType: 'report',
      details: [
        'إعداد شرائح أسعار الجملة حسب الكمية والحد الأدنى للطلب',
        'إدارة كشوف حسابات العملاء والآجل والمدفوعات',
        'توزيع صلاحيات دقيقة للمبيعات والمستودعات والمحاسبين',
        'الانتقال الفوري للوحة التحكم المركزية',
      ],
    },
    aiResponseEn: {
      headline: 'AI Wholesale & B2B Distribution Setup',
      description: 'Volume tiered pricing, recurring POs, role permissions and audits.',
      metric: {
        label: 'Tiered Pricing Engine',
        value: 'Ready',
        change: 'Automate B2B POs',
      },
      actionText: 'Configure Wholesale Hub',
      actionType: 'report',
      details: [
        'Set multi-tier volume pricing and minimum order quantities',
        'Customer credit ledgers, statement generation and payment schedules',
        'Granular role-based permissions for dispatch and accounting',
        'Immediate setup into central enterprise headquarters',
      ],
    },
  },
];

// 7 Commercial Showcase Store Models (من طلب المستخدم نصاً)
export const COMMERCE_TEMPLATES: CommerceTemplate[] = [
  {
    id: 'apparel',
    title: 'أزياء وملابس',
    titleEn: 'Fashion & Apparel',
    subtitle: 'متجر ملابس نسائية أنيق بالدفع عند الاستلام',
    subtitleEn: 'Elegant boutique with cash on delivery and size matrix',
    icon: 'Shirt',
    badge: 'المقاسات والألوان',
    badgeEn: 'Variants Matrix',
    highlightColor: 'from-pink-500 to-rose-600',
  },
  {
    id: 'beauty',
    title: 'تجميل وعناية',
    titleEn: 'Beauty & Skincare',
    subtitle: 'منتجات تجميل مع باقات وعروض ورسائل عملاء',
    subtitleEn: 'Curated skincare bundles, promotional sets and loyalty SMS',
    icon: 'Sparkles',
    badge: 'باقات ورسائل',
    badgeEn: 'Bundles & CRM',
    highlightColor: 'from-purple-500 to-violet-600',
  },
  {
    id: 'food',
    title: 'طعام ومنتجات محلية',
    titleEn: 'Local Food & Produce',
    subtitle: 'طلبات يومية وتوصيل بالمناطق ومنتجات متكررة',
    subtitleEn: 'Daily recurring orders, regional zones and express dispatch',
    icon: 'Apple',
    badge: 'توصيل مناطقي',
    badgeEn: 'Zone Delivery',
    highlightColor: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'electronics',
    title: 'إلكترونيات وإكسسوارات',
    titleEn: 'Electronics & Tech',
    subtitle: 'أجهزة بمتغيرات ومخزون وخدمة ما بعد البيع',
    subtitleEn: 'Multi-spec devices, serial warranty, and after-sales support',
    icon: 'Smartphone',
    badge: 'الضمان والمخزون',
    badgeEn: 'Warranty & Stock',
    highlightColor: 'from-sky-500 to-blue-600',
  },
  {
    id: 'home',
    title: 'منزل ونمط حياة',
    titleEn: 'Home & Living',
    subtitle: 'منتجات منزلية بأقسام منظمة وعرض جميل',
    subtitleEn: 'Structured room categories, visual gallery and bulk fulfillment',
    icon: 'Home',
    badge: 'أقسام منظمة',
    badgeEn: 'Clean Layout',
    highlightColor: 'from-amber-500 to-orange-600',
  },
  {
    id: 'accessories',
    title: 'إكسسوارات',
    titleEn: 'Accessories & Jewelry',
    subtitle: 'حقائب وساعات ومجوهرات بإطلالة أنيقة',
    subtitleEn: 'Bags, timepieces and fine jewelry presented in high luxury aesthetics',
    icon: 'Watch',
    badge: 'فخامة وأناقة',
    badgeEn: 'Luxury Aesthetic',
    highlightColor: 'from-amber-600 to-yellow-600',
  },
  {
    id: 'wholesale-retail',
    title: 'جملة وتجزئة',
    titleEn: 'Wholesale & Retail B2B',
    subtitle: 'مخزون وطلبات متكررة وتقارير وفريق',
    subtitleEn: 'Volume tiered pricing, recurring POs, role permissions and audits',
    icon: 'Layers',
    badge: 'تقارير وفريق',
    badgeEn: 'Tiered Pricing',
    highlightColor: 'from-slate-700 to-slate-900',
  },
];

// All 12 Sectors explicitly requested by the user:
// مطاعم، تجزئة، صالونات، عيادات، سيارات، عقارات، خدمات، تعليم، رياضة، فعاليات، جملة، شركات
export const SECTOR_ACTIVITIES: SectorActivity[] = [
  {
    id: 'restaurants',
    name: 'مطاعم',
    nameEn: 'Restaurants & Cafes',
    tagline: 'أوردرات صالة وتوصيل وطابعات مطبخ',
    taglineEn: 'Dine-in tickets, kitchen display & rapid dispatch',
    icon: 'Utensils',
    description: 'إدارة الطاولات، أوردرات الصالة والتوصيل، ربط طابعات المطبخ والبار، وتكامل سريع مع تطبيقات التوصيل.',
    descriptionEn: 'Table management, dine-in and takeaway tickets, KDS sync, and delivery aggregator links.',
    categoryGroup: 'retail',
  },
  {
    id: 'retail',
    name: 'تجزئة',
    nameEn: 'Retail & Boutiques',
    tagline: 'سرعة كاشير وحركة أرفف متزامنة',
    taglineEn: 'High-speed POS and synchronized shelf velocity',
    icon: 'ShoppingCart',
    description: 'تنظيم حركة البضائع بين الأرفف والمخزن، سرعة الباركود، وتحديث فوري للمخزون مع كل فاتورة بيع.',
    descriptionEn: 'Barcode scanning, shelf-to-backroom sync, and instant automated stock deduction per receipt.',
    categoryGroup: 'retail',
  },
  {
    id: 'salons',
    name: 'صالونات',
    nameEn: 'Salons & Spas',
    tagline: 'حجوزات مواعيد ومقدمي خدمات وباقات',
    taglineEn: 'Appointment booking, stylists schedule & packages',
    icon: 'Scissors',
    description: 'جدولة مواعيد العملاء، تنظيم جدول الأخصائيين، إدارة باقات العناية، وإرسال تذكيرات آلية عبر واتساب.',
    descriptionEn: 'Online appointment calendar, staff scheduling, service packages, and automated WhatsApp reminders.',
    categoryGroup: 'service',
  },
  {
    id: 'clinics',
    name: 'عيادات',
    nameEn: 'Clinics & Healthcare',
    tagline: 'ملفات مراجعين ومواعيد وفواتير ضريبية',
    taglineEn: 'Patient records, calendar & medical invoicing',
    icon: 'Stethoscope',
    description: 'إدارة مواعيد العيادة والأطباء، سجلات المراجعين، وإصدار فواتير ضريبية إلكترونية معتمدة بدقة متناهية.',
    descriptionEn: 'Doctor schedules, patient appointment booking, and certified Phase-2 electronic tax invoicing.',
    categoryGroup: 'service',
  },
  {
    id: 'automotive',
    name: 'سيارات',
    nameEn: 'Automotive & Care',
    tagline: 'كروت تشغيل وقطع غيار وصيانة',
    taglineEn: 'Work orders, spare parts & fleet service',
    icon: 'Car',
    description: 'إصدار كروت الفحص والصيانة، تتبع قطع الغيار بالمستودع، وربط أرقام هياكل السيارات بسجل العمليات.',
    descriptionEn: 'Vehicle check-in job cards, spare parts inventory, VIN tracking, and service invoicing.',
    categoryGroup: 'service',
  },
  {
    id: 'real-estate',
    name: 'عقارات',
    nameEn: 'Real Estate & Properties',
    tagline: 'عقود إيجار ووحدات ومتابعة دفعات',
    taglineEn: 'Unit listings, tenant contracts & payment tracking',
    icon: 'Building',
    description: 'إدارة الوحدات والعقارات، متابعة مواعيد استحقاق الإيجارات، وتوثيق سندات القبض والصرف الرسمية.',
    descriptionEn: 'Property inventory, rental contract cycles, recurring payment tracking, and receipt generation.',
    categoryGroup: 'enterprise',
  },
  {
    id: 'services',
    name: 'خدمات',
    nameEn: 'Professional Services',
    tagline: 'عقود أعمال وفِرق ميدانية وتسليمات',
    taglineEn: 'Field service tickets, milestones & billing',
    icon: 'Wrench',
    description: 'إدارة طلبات الصيانة والتشغيل، جدولة الفنيين الميدانيين، وتتبع تسليم الخدمات بمحاضر استلام رقمية.',
    descriptionEn: 'Field dispatch, technician schedules, project milestone sign-offs, and service billing.',
    categoryGroup: 'service',
  },
  {
    id: 'education',
    name: 'تعليم',
    nameEn: 'Education & Academies',
    tagline: 'دورات واشتراكات وحضور وشهادات',
    taglineEn: 'Courses, student rosters, attendance & tuition',
    icon: 'GraduationCap',
    description: 'تسجيل الطلاب والمتدربين، إدارة اشتراكات المعاهد والأكاديميات، ومتابعة الأقساط والشهادات.',
    descriptionEn: 'Student enrollment, course timetables, tuition installment tracking, and digital certificates.',
    categoryGroup: 'service',
  },
  {
    id: 'sports',
    name: 'رياضة',
    nameEn: 'Sports & Fitness Clubs',
    tagline: 'اشتراكات نوادي وبوابات دخول ومدربين',
    taglineEn: 'Gym memberships, access gates & trainers',
    icon: 'Dumbbell',
    description: 'إدارة عضويات النوادي الرياضية، تتبع مدد الاشتراكات، وحجز حصص التدريب الخاصة والمدربين.',
    descriptionEn: 'Gym membership tiers, access control, renewal alerts, and private coaching session bookings.',
    categoryGroup: 'service',
  },
  {
    id: 'events',
    name: 'فعاليات',
    nameEn: 'Events & Entertainment',
    tagline: 'تذاكر رقمية ودخول ومبيعات مباشرة',
    taglineEn: 'Digital ticketing, QR gate check-in & concessions',
    icon: 'Ticket',
    description: 'حجز وبيع تذاكر الفعاليات والمؤتمرات بباركود QR، تنظيم بوابات الدخول، ومنافذ بيع المأكولات والمشروبات.',
    descriptionEn: 'QR e-ticketing, gate check-in scanning, exhibitor badges, and on-site concessions POS.',
    categoryGroup: 'retail',
  },
  {
    id: 'wholesale',
    name: 'جملة',
    nameEn: 'Wholesale & Distribution',
    tagline: 'مستودعات وطلبات كميات وفواتير مجمعة',
    taglineEn: 'Warehousing, volume tiering & bulk dispatch',
    icon: 'Truck',
    description: 'إدارة المستودعات المركزية، أسعار الكميات المتباينة، كشوف حسابات العملاء، وأذون الصرف والتسليم.',
    descriptionEn: 'Bulk tier pricing, central warehouse bin management, customer credit ledgers, and delivery notes.',
    categoryGroup: 'enterprise',
  },
  {
    id: 'enterprise',
    name: 'شركات',
    nameEn: 'Enterprise & Multi-Branch Chains',
    tagline: 'فروع متعددة وصلاحيات وتقارير مركزية',
    taglineEn: 'Multi-branch networks, granular RBAC & ERP sync',
    icon: 'Building2',
    description: 'ربط مئات الفروع بشاشة مركزية، صلاحيات دقيقة للموظفين، وتكامل مع الأنظمة المالية والمحاسبية المعتمدة.',
    descriptionEn: 'Centralized multi-store oversight, enterprise ERP integration, role permissions, and audit compliance.',
    categoryGroup: 'enterprise',
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'كيف أبدأ في استخدام المنصة؟',
    questionEn: 'How do I get started with the platform?',
    answer: 'ببساطة سجل حساباً مجانياً، اختر نشاطك التجاري، وابدأ في تشغيل نقاط البيع ومتجرك في دقائق.',
    answerEn: 'Simply register a free account, choose your business vertical, and launch your POS and store in minutes.',
  },
  {
    id: 'faq-2',
    question: 'هل الدفع مجاني للتجربة؟',
    questionEn: 'Is getting started free?',
    answer: 'نعم، تجربة مجانية بالكامل بدون أي التزام أو طلب بطاقة بنكية. نقدم خطط مرنة تتناسب مع نمو تجارتك.',
    answerEn: 'Yes, full free trial with zero obligations or credit cards. Flexible plans that scale with your growth.',
  },
  {
    id: 'faq-3',
    question: 'هل تدعمون منظومة الفاتورة والإيصال الإلكتروني لمصلحة الضرائب المصرية؟',
    questionEn: 'Do you support Egyptian Tax Authority (ETA) e-invoicing and e-receipts?',
    answer: 'نعم، متوافقة بالكامل مع منظومة الفاتورة والإيصال الإلكتروني المصرية (ETA) مع إصدار الفواتير المعتمدة ورموز الاستجابة السريعة QR المشفرة.',
    answerEn: 'Yes, fully compliant with Egyptian Tax Authority (ETA) e-invoicing and e-receipt regulations with automated tax QR codes.',
  },
  {
    id: 'faq-4',
    question: 'هل يعمل الكاشير في حال انقطاع الإنترنت في المحل؟',
    questionEn: 'Does POS work offline if internet disconnects?',
    answer: 'نعم، الكاشير يدعم وضع Offline التام. يسجل المبيعات ويطبع الفواتير بدون توقف، وبمجرد عودة الاتصال تتزامن كافة العمليات تلقائياً مع السيرفر والضرائب.',
    answerEn: 'Yes, full offline mode support. Registers log sales and print receipts seamlessly; once reconnected, transactions sync automatically.',
  },
  {
    id: 'faq-5',
    question: 'ما هي أجهزة الكاشير وطابعات الفواتير المتوافقة مع النظام؟',
    questionEn: 'What POS hardware and receipt printers are supported?',
    answer: 'يعمل على أي جهاز لديك (كمبيوتر، لابتوب، تابلت، أو موبايل)، ويدعم كافة طابعات الإيصالات الحرارية (USB / Network / Bluetooth)، وأجهزة قراءة الباركود، وأدراج النقدية.',
    answerEn: 'Runs on any device (PC, laptop, tablet, or phone) and pairs directly with thermal receipt printers, barcode scanners, and cash drawers.',
  },
  {
    id: 'faq-6',
    question: 'كيف تتم معالجة المدفوعات عبر إنستاباي ومحافظ المحمول؟',
    questionEn: 'How are InstaPay and Mobile Wallet payments handled?',
    answer: 'يوفر النظام شاشة دفع موحدة تقبل النقد، ومحافظ المحمول (فودافون كاش، اتصالات، أورنج، وي)، وإنستاباي بباركود QR فوري، مع مطابقة وتسوية نقدية دقيقة بنهاية كل شيفت.',
    answerEn: 'Unified payment screen supporting Cash, Mobile Wallets (Vodafone, Orange, Etisalat, WE), and InstaPay QR with instant shift cash reconciliation.',
  },
  {
    id: 'faq-7',
    question: 'هل يمكنني إدارة أكثر من فرع ومستودع ونقل البضائع بينها؟',
    questionEn: 'Can I manage multiple branches and stockrooms?',
    answer: 'بالتأكيد، يمكنك ربط كافة فروعك ومستودعاتك في شاشة مركزية موحدة، مع نقل البضائع بين الفروع بضغطة زر وتحديد صلاحيات دقيقة لكل كاشير ومدير.',
    answerEn: 'Absolutely, synchronize all locations under a single dashboard with 1-click inter-branch transfers and role permissions.',
  },
  {
    id: 'faq-8',
    question: 'هل أستطيع استخراج نسخة كاملة من بياناتي وتقاريري؟',
    questionEn: 'Can I export my full data and sales reports anytime?',
    answer: 'نعم، بياناتك ملكك 100%. يمكنك تصدير كشوف المبيعات، حركات المخزون، وسجلات العملاء في أي وقت بصيغ Excel أو CSV دون أي قيود.',
    answerEn: 'Yes, your data is 100% yours. Export sales records, inventory movement, and customer directories in Excel/CSV format anytime.',
  },
];

export const BEFORE_AFTER_DATA = {
  ar: {
    title: 'الفرق واضح',
    subtitle: 'الفرق اللي هتحسه من أول أسبوع',
    desc: 'نفس المحل.. بس بطريقة إدارة مختلفة تمامًا.',
    afterTitle: 'بعد نمّي',
    beforeTitle: 'قبل نمّي',
    before: [
      'دفاتر وورق وكشوف مبعثرة',
      'مش عارف المخزون خلص إمتى',
      'أرقام المبيعات متأخرة يوم أو اتنين',
      'كل فرع بيشتغل لوحده',
    ],
    after: [
      'كل حاجة مسجلة في مكان واحد',
      'المخزون يتحدث مع كل عملية بيع',
      'المبيعات قدامك أول بأول',
      'الفروع كلها تحت عينك',
    ],
  },
  en: {
    title: 'The Contrast is Clear',
    subtitle: 'The transformation you feel in week one',
    desc: 'The exact same store.. managed in an entirely modern way.',
    afterTitle: 'With Nammy',
    beforeTitle: 'Before Nammy',
    before: [
      'Scattered paper receipts and loose notebook records',
      'Unaware of when stock runs dry until customers ask',
      'Sales numbers lagging 1-2 days behind reality',
      'Every store branch operating disconnected in silos',
    ],
    after: [
      'Every single transaction synced under one unified system',
      'Inventory updates instantly with each cashier scan',
      'Real-time turnover metrics live before your eyes',
      'All store branches tracked under full central oversight',
    ],
  },
};

export const THREE_STEPS = {
  ar: [
    {
      step: '1',
      title: 'سجّل متجرك',
      desc: 'أنشئ حسابك في أقل من دقيقة واختر نوع نشاطك التجاري.',
    },
    {
      step: '2',
      title: 'صمم واجهتك',
      desc: 'استخدم مصمم الصفحات لإنشاء متجر يعكس هويتك بألوان وصور مخصصة.',
    },
    {
      step: '3',
      title: 'ابدأ البيع',
      desc: 'أضف منتجاتك، فعّل طرق الدفع، وابدأ استقبال الطلبات فوراً.',
    },
  ],
  en: [
    {
      step: '1',
      title: 'Register Your Store',
      desc: 'Create your account in under a minute and pick your business category.',
    },
    {
      step: '2',
      title: 'Design Your Brand',
      desc: 'Use the page designer to publish a storefront tailored to your identity.',
    },
    {
      step: '3',
      title: 'Start Selling',
      desc: 'Add products, activate payments, and start processing orders immediately.',
    },
  ],
};
