import { Receipt } from 'lucide-react';
import type { ModuleDef } from '../../types';

export const financeModule: ModuleDef = {
  id: 'finance',
  name: 'Finance & Invoicing',
  nameKey: 'modules.finance.name',
  nameAr: 'المالية والفواتير',
  description: 'Invoices, expenses, transactions, and financial reporting.',
  descriptionKey: 'modules.finance.description',
  descriptionAr: 'فواتير، مصروفات، معاملات، وتقارير مالية.',
  icon: Receipt,
  category: 'management',
  color: '#7C3AED',
  dependencies: ['core'],
  features: [
    { id: 'invoice', label: 'Invoices', labelAr: 'الفواتير', defaultEnabled: true },
    { id: 'revenue', label: 'Revenue', labelAr: 'الإيرادات', defaultEnabled: true },
    { id: 'expenses', label: 'Expenses', labelAr: 'المصروفات', defaultEnabled: true },
    { id: 'profits', label: 'Profits', labelAr: 'الأرباح', defaultEnabled: false },
    { id: 'taxes', label: 'Taxes', labelAr: 'الضرائب', defaultEnabled: false },
    { id: 'journal', label: 'Journal Entries', labelAr: 'القيود', defaultEnabled: false },
    { id: 'cashflow', label: 'Cash Flow', labelAr: 'التدفقات النقدية', defaultEnabled: false },
    { id: 'accounts', label: 'Accounts', labelAr: 'الحسابات', defaultEnabled: false },
    { id: 'wallets', label: 'Wallets', labelAr: 'المحافظ', defaultEnabled: false },
    { id: 'financialReports', label: 'Financial Reports', labelAr: 'التقارير المالية', defaultEnabled: true },
  ],
  pages: [
    { id: 'invoice', label: 'Invoices', route: '/business/dashboard?tab=invoice', tabId: 'invoice', existing: true },
    { id: 'expenses', label: 'Expenses', route: '/business/dashboard?tab=expenses', tabId: 'expenses', existing: true },
    { id: 'revenue', label: 'Revenue', route: '/business/dashboard?tab=revenue', tabId: 'revenue' },
    { id: 'profits', label: 'Profits', route: '/business/dashboard?tab=profits', tabId: 'profits' },
    { id: 'taxes', label: 'Taxes', route: '/business/dashboard?tab=taxes', tabId: 'taxes' },
    { id: 'journal', label: 'Journal', route: '/business/dashboard?tab=journal', tabId: 'journal' },
    { id: 'cashflow', label: 'Cash Flow', route: '/business/dashboard?tab=cashflow', tabId: 'cashflow' },
    { id: 'accounts', label: 'Accounts', route: '/business/dashboard?tab=accounts', tabId: 'accounts' },
    { id: 'wallets', label: 'Wallets', route: '/business/dashboard?tab=wallets', tabId: 'wallets' },
    { id: 'financialReports', label: 'Financial Reports', route: '/business/dashboard?tab=financialReports', tabId: 'financialReports' },
  ],
  navigation: [
    {
      id: 'finance',
      title: 'Finance',
      titleKey: 'dashboard.sections.finance',
      order: 30,
      items: [
        { id: 'invoice', label: 'Invoices', labelKey: 'business.dashboardTabs.invoice', route: '/business/dashboard?tab=invoice', tabId: 'invoice', icon: 'FileText', order: 0 },
        { id: 'expenses', label: 'Expenses', labelKey: 'business.dashboardTabs.expenses', route: '/business/dashboard?tab=expenses', tabId: 'expenses', icon: 'Wallet', order: 1 },
        { id: 'revenue', label: 'Revenue', labelKey: 'business.dashboardTabs.revenue', route: '/business/dashboard?tab=revenue', tabId: 'revenue', icon: 'TrendingUp', order: 2 },
        { id: 'profits', label: 'Profits', labelKey: 'business.dashboardTabs.profits', route: '/business/dashboard?tab=profits', tabId: 'profits', icon: 'Coins', order: 3 },
        { id: 'taxes', label: 'Taxes', labelKey: 'business.dashboardTabs.taxes', route: '/business/dashboard?tab=taxes', tabId: 'taxes', icon: 'Receipt', order: 4 },
        { id: 'journal', label: 'Journal', labelKey: 'business.dashboardTabs.journal', route: '/business/dashboard?tab=journal', tabId: 'journal', icon: 'FileText', order: 5 },
        { id: 'cashflow', label: 'Cash Flow', labelKey: 'business.dashboardTabs.cashflow', route: '/business/dashboard?tab=cashflow', tabId: 'cashflow', icon: 'TrendingUp', order: 6 },
        { id: 'accounts', label: 'Accounts', labelKey: 'business.dashboardTabs.accounts', route: '/business/dashboard?tab=accounts', tabId: 'accounts', icon: 'Briefcase', order: 7 },
        { id: 'wallets', label: 'Wallets', labelKey: 'business.dashboardTabs.wallets', route: '/business/dashboard?tab=wallets', tabId: 'wallets', icon: 'Wallet', order: 8 },
        { id: 'financialReports', label: 'Financial Reports', labelKey: 'business.dashboardTabs.financialReports', route: '/business/dashboard?tab=financialReports', tabId: 'financialReports', icon: 'BarChart3', order: 9 },
      ],
    },
  ],
  dashboardWidgets: [
    { id: 'revenue_summary', label: 'Revenue Summary', labelKey: 'modules.finance.widgetRevenue', component: 'RevenueSummary', order: 6, size: 'medium' },
    { id: 'expense_breakdown', label: 'Expense Breakdown', labelKey: 'modules.finance.widgetExpenses', component: 'ExpenseBreakdown', order: 7, size: 'medium' },
  ],
  permissions: [
    { id: 'finance.view', label: 'View Financial Data' },
    { id: 'finance.manage', label: 'Manage Invoices & Expenses' },
  ],
  settingsSections: [
    { id: 'finance', label: 'Finance Settings', labelKey: 'dashboard.settings.finance' },
    { id: 'tax', label: 'Tax Settings', labelKey: 'dashboard.settings.tax' },
  ],
  defaultEnabled: false,
  optional: true,
  estimatedSetupMinutes: 8,
};
