import { Calendar } from 'lucide-react';
import type { ModuleDef } from '../../types';

export const bookingsModule: ModuleDef = {
  id: 'bookings',
  name: 'Bookings & Reservations',
  nameKey: 'modules.bookings.name',
  nameAr: 'الحجوزات والمواعيد',
  description: 'Appointment scheduling, service providers, room management, and booking calendar.',
  descriptionKey: 'modules.bookings.description',
  descriptionAr: 'جدولة المواعيد، مقدمو الخدمة، إدارة الغرف، وتقويم الحجوزات.',
  icon: Calendar,
  category: 'operations',
  color: '#0891B2',
  dependencies: ['core'],
  features: [
    { id: 'reservations', label: 'Booking Calendar & Dashboard', labelAr: 'الحجوزات', defaultEnabled: true },
    { id: 'providers', label: 'Service Providers / Staff', labelAr: 'مقدمو الخدمة', defaultEnabled: true },
    { id: 'services', label: 'Services Catalog', labelAr: 'الخدمات', defaultEnabled: true },
    { id: 'rooms', label: 'Rooms / Chairs / Units', labelAr: 'الغرف / الوحدات', defaultEnabled: true },
    { id: 'patient_records', label: 'Customer/Patient Records', labelAr: 'سجلات العملاء', defaultEnabled: true },
    { id: 'appointments', label: 'Appointments', labelAr: 'المواعيد', defaultEnabled: true },
    { id: 'calendar', label: 'Calendar', labelAr: 'التقويم', defaultEnabled: true },
    { id: 'doctors', label: 'Doctors', labelAr: 'الأطباء', defaultEnabled: false },
    { id: 'bookingConfirm', label: 'Booking Confirmation', labelAr: 'التأكيد', defaultEnabled: false },
    { id: 'bookingCancel', label: 'Booking Cancellation', labelAr: 'الإلغاء', defaultEnabled: false },
    { id: 'bookingReminder', label: 'Booking Reminders', labelAr: 'التذكير', defaultEnabled: false },
    { id: 'activity_inventory', label: 'Activity-Specific Inventory', labelAr: 'مخزون النشاط', defaultEnabled: false },
    { id: 'restaurant_tables', label: 'Restaurant Table Management', labelAr: 'إدارة طاولات المطعم', defaultEnabled: false },
  ],
  pages: [
    { id: 'reservations', label: 'Reservations', route: '/business/dashboard?tab=reservations', tabId: 'reservations', existing: true },
    { id: 'providers', label: 'Providers', route: '/business/dashboard?tab=providers', tabId: 'providers', existing: true },
    { id: 'services', label: 'Services', route: '/business/dashboard?tab=services', tabId: 'services', existing: true },
    { id: 'activity_rooms', label: 'Rooms / Units', route: '/business/dashboard?tab=activityRooms', tabId: 'activityRooms', existing: true },
    { id: 'activity_patients', label: 'Customer Records', route: '/business/dashboard?tab=activityPatients', tabId: 'activityPatients', existing: true },
    { id: 'activity_inventory', label: 'Activity Inventory', route: '/business/dashboard?tab=activityInventory', tabId: 'activityInventory', existing: true },
    { id: 'restaurant_tables', label: 'Restaurant Tables', route: '/business/dashboard?tab=restaurantTables', tabId: 'restaurantTables', existing: true },
    { id: 'appointments', label: 'Appointments', route: '/business/dashboard?tab=appointments', tabId: 'appointments' },
    { id: 'calendar', label: 'Calendar', route: '/business/dashboard?tab=calendar', tabId: 'calendar' },
    { id: 'rooms', label: 'Rooms', route: '/business/dashboard?tab=rooms', tabId: 'rooms' },
    { id: 'doctors', label: 'Doctors', route: '/business/dashboard?tab=doctors', tabId: 'doctors' },
    { id: 'bookingConfirm', label: 'Booking Confirm', route: '/business/dashboard?tab=bookingConfirm', tabId: 'bookingConfirm' },
    { id: 'bookingCancel', label: 'Booking Cancel', route: '/business/dashboard?tab=bookingCancel', tabId: 'bookingCancel' },
    { id: 'bookingReminder', label: 'Booking Reminder', route: '/business/dashboard?tab=bookingReminder', tabId: 'bookingReminder' },
  ],
  navigation: [
    {
      id: 'booking_management',
      title: 'Booking Management',
      titleKey: 'dashboard.sections.bookingManagement',
      order: 15,
      items: [
        { id: 'reservations', label: 'Reservations', labelKey: 'business.dashboardTabs.reservations', route: '/business/dashboard?tab=reservations', tabId: 'reservations', icon: 'Calendar', order: 0 },
        { id: 'providers', label: 'Providers', labelKey: 'business.dashboardTabs.providers', route: '/business/dashboard?tab=providers', tabId: 'providers', icon: 'Users', order: 1 },
        { id: 'services', label: 'Services', labelKey: 'business.dashboardTabs.services', route: '/business/dashboard?tab=services', tabId: 'services', icon: 'ListChecks', order: 2 },
        { id: 'activity_rooms', label: 'Rooms / Units', labelKey: 'business.dashboardTabs.activityRooms', route: '/business/dashboard?tab=activityRooms', tabId: 'activityRooms', icon: 'Store', order: 3 },
        { id: 'activity_patients', label: 'Customer Records', labelKey: 'business.dashboardTabs.activityPatients', route: '/business/dashboard?tab=activityPatients', tabId: 'activityPatients', icon: 'FileText', order: 4 },
        { id: 'appointments', label: 'Appointments', labelKey: 'business.dashboardTabs.appointments', route: '/business/dashboard?tab=appointments', tabId: 'appointments', icon: 'CalendarCheck', order: 5 },
        { id: 'calendar', label: 'Calendar', labelKey: 'business.dashboardTabs.calendar', route: '/business/dashboard?tab=calendar', tabId: 'calendar', icon: 'Calendar', order: 6 },
        { id: 'rooms', label: 'Rooms', labelKey: 'business.dashboardTabs.rooms', route: '/business/dashboard?tab=rooms', tabId: 'rooms', icon: 'Building2', order: 7 },
        { id: 'doctors', label: 'Doctors', labelKey: 'business.dashboardTabs.doctors', route: '/business/dashboard?tab=doctors', tabId: 'doctors', icon: 'Stethoscope', order: 8 },
        { id: 'bookingConfirm', label: 'Booking Confirm', labelKey: 'business.dashboardTabs.bookingConfirm', route: '/business/dashboard?tab=bookingConfirm', tabId: 'bookingConfirm', icon: 'CalendarCheck', order: 9 },
        { id: 'bookingCancel', label: 'Booking Cancel', labelKey: 'business.dashboardTabs.bookingCancel', route: '/business/dashboard?tab=bookingCancel', tabId: 'bookingCancel', icon: 'CalendarX', order: 10 },
        { id: 'bookingReminder', label: 'Booking Reminder', labelKey: 'business.dashboardTabs.bookingReminder', route: '/business/dashboard?tab=bookingReminder', tabId: 'bookingReminder', icon: 'AlarmClock', order: 11 },
      ],
    },
  ],
  dashboardWidgets: [
    { id: 'upcoming_bookings', label: 'Upcoming Bookings', labelKey: 'modules.bookings.widgetUpcoming', component: 'UpcomingBookings', order: 11, size: 'large' },
    { id: 'provider_schedule', label: 'Provider Schedule', labelKey: 'modules.bookings.widgetSchedule', component: 'ProviderSchedule', order: 12, size: 'medium' },
  ],
  permissions: [
    { id: 'bookings.view', label: 'View Bookings' },
    { id: 'bookings.manage', label: 'Manage Bookings' },
    { id: 'bookings.providers', label: 'Manage Providers' },
  ],
  settingsSections: [
    { id: 'bookings', label: 'Booking Settings', labelKey: 'dashboard.settings.bookings' },
    { id: 'booking_activity', label: 'Activity Type', labelKey: 'dashboard.settings.bookingActivity' },
  ],
  defaultEnabled: false,
  optional: true,
  estimatedSetupMinutes: 15,
};
