ALTER TABLE feedback DROP COLUMN IF EXISTS order_id;
ALTER TABLE feedback DROP COLUMN IF EXISTS type;
ALTER TABLE feedback DROP COLUMN IF EXISTS title;
ALTER TABLE feedback DROP COLUMN IF EXISTS comment;
ALTER TABLE feedback DROP COLUMN IF EXISTS updated_at;