import { Package } from 'lucide-react';
import type { ModuleDef } from '../../types';

export const inventoryModule: ModuleDef = {
  id: 'inventory',
  name: 'Inventory & Products',
  nameKey: 'modules.inventory.name',
  nameAr: 'المخزون والمنتجات',
  description: 'Manage products, categories, stock levels, variants, and suppliers.',
  descriptionKey: 'modules.inventory.description',
  descriptionAr: 'إدارة المنتجات، الفئات، مستويات المخزون، المتغيرات، والموردين.',
  icon: Package,
  category: 'operations',
  color: '#16A34A',
  dependencies: ['core'],
  features: [
    { id: 'products', label: 'Products', labelAr: 'المنتجات', defaultEnabled: true },
    { id: 'categories', label: 'Categories', labelAr: 'الفئات', defaultEnabled: true },
    { id: 'variants', label: 'Variants', labelAr: 'المتغيرات', defaultEnabled: false },
    { id: 'warehouses', label: 'Warehouses', labelAr: 'المخازن', defaultEnabled: false },
    { id: 'stocktake', label: 'Stocktake', labelAr: 'الجرد', defaultEnabled: false },
    { id: 'suppliers', label: 'Suppliers', labelAr: 'الموردين', defaultEnabled: false },
    { id: 'purchaseOrders', label: 'Purchase Orders', labelAr: 'أوامر الشراء', defaultEnabled: false },
    { id: 'transfers', label: 'Transfers', labelAr: 'النقل بين المخازن', defaultEnabled: false },
    { id: 'barcode', label: 'Barcode', labelAr: 'الباركود', defaultEnabled: false },
    { id: 'qrCode', label: 'QR Code', labelAr: 'QR Code', defaultEnabled: false },
    { id: 'stockTracking', label: 'Stock Tracking', labelAr: 'تتبع الكميات', defaultEnabled: false },
    { id: 'lowStockAlerts', label: 'Low Stock Alerts', labelAr: 'تنبيهات النفاد', defaultEnabled: false },
  ],
  pages: [
    { id: 'products', label: 'Products', route: '/business/dashboard?tab=products', tabId: 'products', existing: true },
    { id: 'categories', label: 'Categories', route: '/business/dashboard?tab=categories', tabId: 'categories' },
    { id: 'variants', label: 'Variants', route: '/business/dashboard?tab=variants', tabId: 'variants' },
    { id: 'warehouses', label: 'Warehouses', route: '/business/dashboard?tab=warehouses', tabId: 'warehouses' },
    { id: 'stocktake', label: 'Stocktake', route: '/business/dashboard?tab=stocktake', tabId: 'stocktake' },
    { id: 'suppliers', label: 'Suppliers', route: '/business/dashboard?tab=suppliers', tabId: 'suppliers' },
    { id: 'purchaseOrders', label: 'Purchase Orders', route: '/business/dashboard?tab=purchaseOrders', tabId: 'purchaseOrders' },
    { id: 'transfers', label: 'Transfers', route: '/business/dashboard?tab=transfers', tabId: 'transfers' },
    { id: 'barcode', label: 'Barcode', route: '/business/dashboard?tab=barcode', tabId: 'barcode' },
    { id: 'qrCode', label: 'QR Code', route: '/business/dashboard?tab=qrCode', tabId: 'qrCode' },
    { id: 'stockTracking', label: 'Stock Tracking', route: '/business/dashboard?tab=stockTracking', tabId: 'stockTracking' },
    { id: 'lowStockAlerts', label: 'Low Stock Alerts', route: '/business/dashboard?tab=lowStockAlerts', tabId: 'lowStockAlerts' },
  ],
  navigation: [
    {
      id: 'inventory',
      title: 'Inventory',
      titleKey: 'dashboard.sections.inventory',
      order: 20,
      items: [
        { id: 'products', label: 'Products', labelKey: 'business.dashboardTabs.inventory', route: '/business/dashboard?tab=products', tabId: 'products', icon: 'Package', order: 0 },
        { id: 'categories', label: 'Categories', labelKey: 'business.dashboardTabs.categories', route: '/business/dashboard?tab=categories', tabId: 'categories', icon: 'Tag', order: 1 },
        { id: 'variants', label: 'Variants', labelKey: 'business.dashboardTabs.variants', route: '/business/dashboard?tab=variants', tabId: 'variants', icon: 'ListChecks', order: 2 },
        { id: 'warehouses', label: 'Warehouses', labelKey: 'business.dashboardTabs.warehouses', route: '/business/dashboard?tab=warehouses', tabId: 'warehouses', icon: 'Warehouse', order: 3 },
        { id: 'stocktake', label: 'Stocktake', labelKey: 'business.dashboardTabs.stocktake', route: '/business/dashboard?tab=stocktake', tabId: 'stocktake', icon: 'ClipboardList', order: 4 },
        { id: 'suppliers', label: 'Suppliers', labelKey: 'business.dashboardTabs.suppliers', route: '/business/dashboard?tab=suppliers', tabId: 'suppliers', icon: 'Truck', order: 5 },
        { id: 'purchaseOrders', label: 'Purchase Orders', labelKey: 'business.dashboardTabs.purchaseOrders', route: '/business/dashboard?tab=purchaseOrders', tabId: 'purchaseOrders', icon: 'FileText', order: 6 },
        { id: 'transfers', label: 'Transfers', labelKey: 'business.dashboardTabs.transfers', route: '/business/dashboard?tab=transfers', tabId: 'transfers', icon: 'ArrowLeftRight', order: 7 },
        { id: 'barcode', label: 'Barcode', labelKey: 'business.dashboardTabs.barcode', route: '/business/dashboard?tab=barcode', tabId: 'barcode', icon: 'ScanLine', order: 8 },
        { id: 'qrCode', label: 'QR Code', labelKey: 'business.dashboardTabs.qrCode', route: '/business/dashboard?tab=qrCode', tabId: 'qrCode', icon: 'QrCode', order: 9 },
        { id: 'stockTracking', label: 'Stock Tracking', labelKey: 'business.dashboardTabs.stockTracking', route: '/business/dashboard?tab=stockTracking', tabId: 'stockTracking', icon: 'Package', order: 10 },
        { id: 'lowStockAlerts', label: 'Low Stock Alerts', labelKey: 'business.dashboardTabs.lowStockAlerts', route: '/business/dashboard?tab=lowStockAlerts', tabId: 'lowStockAlerts', icon: 'Bell', order: 11 },
      ],
    },
  ],
  dashboardWidgets: [
    { id: 'product_count', label: 'Product Count', labelKey: 'modules.inventory.widgetProductCount', component: 'ProductCount', order: 4, size: 'small' },
    { id: 'low_stock', label: 'Low Stock Alerts', labelKey: 'modules.inventory.widgetLowStock', component: 'LowStockAlerts', order: 5, size: 'medium' },
  ],
  permissions: [
    { id: 'inventory.view', label: 'View Products' },
    { id: 'inventory.manage', label: 'Manage Products' },
    { id: 'inventory.stock', label: 'Manage Stock' },
  ],
  settingsSections: [
    { id: 'inventory', label: 'Inventory Settings', labelKey: 'dashboard.settings.inventory' },
  ],
  defaultEnabled: true,
  optional: true,
  estimatedSetupMinutes: 10,
};
