/**
 * ينسخ ملفات الفونتات woff2 من مجلد التمب إلى public/fonts لكل تطبيق
 * ويولّد ملف fonts.css يحتوي @font-face لكل فونت.
 * الاستخدام: node scripts/install-fonts.mjs <sourceDir>
 */
import fs from 'fs';
import path from 'path';
import os from 'os';

const srcDir = process.argv[2] || path.join(os.tmpdir(), 'gwfh');
const APPS = ['apps/business', 'apps/marketplace-next', 'apps/dashboard-web'];
const ROOT = process.cwd();

const FAMILY_MAP = {
  alexandria: 'Alexandria',
  cairo: 'Cairo',
  tajawal: 'Tajawal',
  amiri: 'Amiri',
  almarai: 'Almarai',
  'ibm-plex-sans-arabic': 'IBM Plex Sans Arabic',
};

const files = [];
for (const dir of fs.readdirSync(srcDir)) {
  const full = path.join(srcDir, dir);
  if (!fs.statSync(full).isDirectory()) continue;
  for (const f of fs.readdirSync(full)) {
    if (f.endsWith('.woff2')) files.push({ dir, file: f });
  }
}

let css = '/* Self-hosted fonts - generated by scripts/install-fonts.mjs */\n';
for (const { dir, file } of files) {
  const family = FAMILY_MAP[dir];
  if (!family) continue;
  const m = file.match(/-(\d+|regular)\.woff2$/);
  const weight = m ? (m[1] === 'regular' ? '400' : m[1]) : '400';
  for (const app of APPS) {
    const destDir = path.join(ROOT, app, 'public', 'fonts');
    fs.mkdirSync(destDir, { recursive: true });
    fs.copyFileSync(path.join(srcDir, dir, file), path.join(destDir, file));
  }
  css += `\n@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n}\n`;
}

for (const app of APPS) {
  fs.writeFileSync(path.join(ROOT, app, 'public', 'fonts', 'fonts.css'), css);
}

console.log(`Installed ${files.length} font files into ${APPS.length} apps and generated fonts.css`);
