import { getBusinessActivityById, getBusinessActivityThemePatch, BUSINESS_ACTIVITIES } from './businessActivityCatalog';

export type ActivityPreviewProduct = {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  category: string;
};

export type ActivityPreviewData = {
  marqueeOffers: string[];
  aboutTitle: string;
  aboutText: string;
  aboutImage: string;
  storyTitle: string;
  storyText: string;
  storyImage: string;
  highlightedTitle: string;
  ctaLabel: string;
  products: ActivityPreviewProduct[];
  categories: string[];
  defaultShopName: string;
  defaultShopDescription: string;
  bannerImage: string;
  productPlaceholderImage: string;
  productsTabLabel: string;
  galleryTabLabel: string;
  infoTabLabel: string;
  showAllLabel: string;
  footerDescription: string;
};

const UNSPLASH_FOOD = 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400';
const UNSPLASH_FOOD2 = 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400';
const UNSPLASH_FASHION = 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=400';
const UNSPLASH_FABRIC = 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400';

const PREVIEW_DATA: Record<string, ActivityPreviewData> = {
  restaurant: {
    marqueeOffers: ['🚚 توصيل مجاني للمناطق القريبة!', '🔥 خصم 15% على طلبك الأول!', '⭐ وجبات اليوم مميزة!'],
    aboutTitle: 'من نحن ومطبخنا',
    aboutText: 'نقدم أشهى الأطباق بمكونات طازجة ووصفات أصلية لتجربة طعام لا تُنسى.',
    aboutImage: UNSPLASH_FOOD,
    storyTitle: 'خدماتنا وعروضنا',
    storyText: 'استمتع بتجربة طعم متكاملة مع خيارات توصيل سريعة وعروض يومية على وجباتك المفضلة.',
    storyImage: UNSPLASH_FOOD2,
    highlightedTitle: 'أبرز الأطباق',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'r1', name: 'وجبة مشاوي مشكلة', description: 'مشاوي بلدي + أرز + سلطة', price: 180, imageUrl: '', category: 'وجبات رئيسية' },
      { id: 'r2', name: 'برجر لحم أنجوس', description: 'برجر 200جم + بطاطس + مشروب', price: 120, imageUrl: '', category: 'وجبات سريعة' },
      { id: 'r3', name: 'بيتزا مارجريتا', description: 'عجينة طازجة + جبنة موتزاريلا', price: 95, imageUrl: '', category: 'بيتزا' },
      { id: 'r4', name: 'كباب حلة', description: 'لحم بتلو + صلصة خاصة', price: 160, imageUrl: '', category: 'وجبات رئيسية' },
      { id: 'r5', name: 'سلطة سيزر', description: 'خس + دجاج مشوي + صوص خاص', price: 65, imageUrl: '', category: 'مقبلات' },
      { id: 'r6', name: 'شوربة عدس', description: 'شوربة عدس بلدي ساخنة', price: 35, imageUrl: '', category: 'مقبلات' },
    ],
    categories: ['الكل', 'وجبات رئيسية', 'وجبات سريعة', 'بيتزا', 'مقبلات'],
    defaultShopName: 'مطعم الذواقة',
    defaultShopDescription: 'أكل بيتي أصيل بنكهة مصرية',
    bannerImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    productsTabLabel: 'القائمة',
    galleryTabLabel: 'صور الأطباق',
    infoTabLabel: 'معلومات المطعم',
    showAllLabel: 'عرض كل الأطباق',
    footerDescription: 'نقدم أشهى الأطباق بمكونات طازجة ووصفات أصلية',
  },
  grocery: {
    marqueeOffers: ['🛒 عروض أسبوعية على جميع الأقسام!', '🚚 توصيل مجاني للطلبات فوق 200ج!', '⭐ منتجات طازجة يومياً!'],
    aboutTitle: 'بقالتنا ومنتجاتنا',
    aboutText: 'كل احتياجاتك اليومية من بقالة وخضار ومعلبات بأسعار تنافسية وجودة مضمونة.',
    aboutImage: 'https://images.unsplash.com/photo-1542838132-92c53300491b?w=400',
    storyTitle: 'خدمات التوصيل والعروض',
    storyText: 'اطلب احتياجاتك من المنزل واستمتع بتوصيل سريع وعروض توفير أسبوعية.',
    storyImage: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'أضف للسلة',
    products: [
      { id: 'g1', name: 'زيت عافية 1 لتر', description: 'زيت ذرة مكرر', price: 65, imageUrl: '', category: 'زيوت وسمن' },
      { id: 'g2', name: 'أرز مصري 5 كجم', description: 'أرز مصري فاخر', price: 120, imageUrl: '', category: 'حبوب' },
      { id: 'g3', name: 'سكر 1 كجم', description: 'سكر أبيض ناعم', price: 28, imageUrl: '', category: 'حبوب' },
      { id: 'g4', name: 'شاي العروسة 250جم', description: 'شاي أحمر فاخر', price: 45, imageUrl: '', category: 'مشروبات' },
      { id: 'g5', name: 'علبة تونة 185جم', description: 'تونة قطع في زيت', price: 35, imageUrl: '', category: 'معلبات' },
      { id: 'g6', name: 'مكرونة 400جم', description: 'مكرونة رقم 1', price: 18, imageUrl: '', category: 'حبوب' },
    ],
    categories: ['الكل', 'زيوت وسمن', 'حبوب', 'مشروبات', 'معلبات'],
    defaultShopName: 'بقالة الخير',
    defaultShopDescription: 'كل احتياجاتك اليومية في مكان واحد',
    bannerImage: 'https://images.unsplash.com/photo-1542838132-92c53300491b?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'كل احتياجاتك اليومية بأسعار تنافسية وجودة مضمونة',
  },
  fashion: {
    marqueeOffers: ['👗 تشكيلة جديدة وصلت!', '🚚 شحن مجاني لكافة المحافظات!', '⭐ خصم 20% على الكوليكشن الجديد!'],
    aboutTitle: 'من نحن وعلامتنا',
    aboutText: 'نقدم أحدث صيحات الموضة بجودة عالية وأسعار تنافسية لجميع أفراد الأسرة.',
    aboutImage: UNSPLASH_FASHION,
    storyTitle: 'مجموعاتنا وعروضنا',
    storyText: 'استمتع بتجربة تسوق متكاملة مع تشكيلات موسمية وخيارات تبديل سهلة وتوصيل سريع.',
    storyImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400',
    highlightedTitle: 'أبرز القطع',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'f1', name: 'قميص قطن رجالي', description: 'قطن 100% - مقاسات متعددة', price: 250, imageUrl: '', category: 'ملابس رجالي' },
      { id: 'f2', name: 'فستان سهرة', description: 'تصميم أنيق - ألوان متعددة', price: 650, imageUrl: '', category: 'ملابس حريمي' },
      { id: 'f3', name: 'بنطلون جينز', description: 'جينز عالي الجودة - مقاسات', price: 320, imageUrl: '', category: 'ملابس رجالي' },
      { id: 'f4', name: 'بلوزة كاجوال', description: 'خامة مريحة - ألوان', price: 180, imageUrl: '', category: 'ملابس حريمي' },
      { id: 'f5', name: 'تيشيرت أطفال', description: 'قطن ناعم - رسومات', price: 95, imageUrl: '', category: 'ملابس أطفال' },
      { id: 'f6', name: 'حذاء رياضي', description: 'حذاء جري مريح', price: 450, imageUrl: '', category: 'أحذية' },
    ],
    categories: ['الكل', 'ملابس رجالي', 'ملابس حريمي', 'ملابس أطفال', 'أحذية'],
    defaultShopName: 'بوتيك الأناقة',
    defaultShopDescription: 'موضة لكل الأذواق',
    bannerImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل القطع',
    footerDescription: 'أحدث صيحات الموضة بجودة عالية وأسعار تنافسية',
  },
  fabricStore: {
    marqueeOffers: ['🧵 أقمشة جديدة وصلت!', '✂️ تفصيل حسب المقاس!', '⭐ خصم على شراء بالمتر!'],
    aboutTitle: 'أقمشتنا وخاماتنا',
    aboutText: 'تشكيلة واسعة من الأقمشة والخامات للملابس والمفروشات بأجود الأنواع.',
    aboutImage: UNSPLASH_FABRIC,
    storyTitle: 'خدمات التفصيل والطلبات',
    storyText: 'نوفر خدمة التفصيل حسب المقاس والبيع بالمتر والرولات مع عروض على الكميات.',
    storyImage: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400',
    highlightedTitle: 'أبرز الأقمشة',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'fb1', name: 'قماش قطن بالمتر', description: 'قطن مصري - عرض 150سم', price: 45, imageUrl: '', category: 'أقمشة ملابس' },
      { id: 'fb2', name: 'قماش لينين', description: 'لينين طبيعي فاخر', price: 85, imageUrl: '', category: 'أقمشة ملابس' },
      { id: 'fb3', name: 'قماش مخمل', description: 'مخمل ناعم - ألوان', price: 120, imageUrl: '', category: 'أقمشة مفروشات' },
      { id: 'fb4', name: 'باترون جاهز', description: 'باترونات تفصيل مقاسات', price: 25, imageUrl: '', category: 'باترونات' },
      { id: 'fb5', name: 'قماش حرير صناعي', description: 'حرير صناعي - عرض 140سم', price: 55, imageUrl: '', category: 'أقمشة ملابس' },
      { id: 'fb6', name: 'خيطان وأزرار', description: 'إكسسوارات خياطة متنوعة', price: 15, imageUrl: '', category: 'إكسسوارات' },
    ],
    categories: ['الكل', 'أقمشة ملابس', 'أقمشة مفروشات', 'باترونات', 'إكسسوارات'],
    defaultShopName: 'محل الأقمشة',
    defaultShopDescription: 'كل أنواع الأقمشة والخامات',
    bannerImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400',
    productsTabLabel: 'الأقمشة والخامات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل الأقمشة',
    footerDescription: 'تشكيلة واسعة من الأقمشة والخامات بأجود الأنواع',
  },
  homeTextiles: {
    marqueeOffers: ['🛏️ تشكيلة مفروشات جديدة!', '🚚 تركيب وتوصيل مجاني!', '⭐ خصم على أطقم السرير!'],
    aboutTitle: 'مفروشاتنا وتشكيلاتنا',
    aboutText: 'مفروشات وسجاد وستائر بأرقى الخامات وأحدث التصميمات لمنزل أنيق.',
    aboutImage: 'https://images.unsplash.com/photo-1586086009783-9d2c0c0c0c0c?w=400',
    storyTitle: 'خدمات التفصيل والتركيب',
    storyText: 'نوفر تفصيل الستائر والمفروشات حسب المقاس مع خدمة التركيب في المنزل.',
    storyImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400',
    highlightedTitle: 'أبرز المفروشات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'ht1', name: 'طقم ملايات سرير', description: 'قطن مصري - كينج', price: 350, imageUrl: '', category: 'ملايات' },
      { id: 'ht2', name: 'سجاد غرفة معيشة', description: 'سجاد عجمي - مقاس 2x3', price: 850, imageUrl: '', category: 'سجاد' },
      { id: 'ht3', name: 'ستارة شيفون', description: 'شيفون - تفصيل حسب المقاس', price: 120, imageUrl: '', category: 'ستائر' },
      { id: 'ht4', name: 'لحاف قطني', description: 'لحاف قطن - مقاس كينج', price: 280, imageUrl: '', category: 'لحاف ومخدات' },
      { id: 'ht5', name: 'مخدة طبية', description: 'مخدة طبية - قطن', price: 85, imageUrl: '', category: 'لحاف ومخدات' },
      { id: 'ht6', name: 'مفرش طاولة', description: 'مفرش قطني - تطريز', price: 65, imageUrl: '', category: 'مفارش' },
    ],
    categories: ['الكل', 'ملايات', 'سجاد', 'ستائر', 'لحاف ومخدات', 'مفارش'],
    defaultShopName: 'مفروشات الراحة',
    defaultShopDescription: 'مفروشات وستائر لكل بيت',
    bannerImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المفروشات',
    footerDescription: 'مفروشات وسجاد وستائر بأرقى الخامات',
  },
  curtainsBlinds: {
    marqueeOffers: ['🪟 ستائر بلاك أوت وصلت!', '📏 قياس وتركيب مجاني!', '⭐ خصم على الستائر المفصلة!'],
    aboutTitle: 'ستائرنا وتفصيلنا',
    aboutText: 'ستائر بلاك أوت وشيفون ورول بكل المقاسات مع خدمة القياس والتركيب.',
    aboutImage: 'https://images.unsplash.com/photo-1586086009783-9d2c0c0c0c0c?w=400',
    storyTitle: 'خدمات التركيب والصيانة',
    storyText: 'نوفر خدمة قياس الشبابيك والتفصيل حسب المقاس والتركيب الاحترافي.',
    storyImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400',
    highlightedTitle: 'أبرز الستائر',
    ctaLabel: 'اطلب قياس',
    products: [
      { id: 'cb1', name: 'ستارة بلاك أوت', description: 'حجب ضوء 100% - بالمتر', price: 85, imageUrl: '', category: 'بلاك أوت' },
      { id: 'cb2', name: 'ستارة شيفون', description: 'شيفون ناعم - بالمتر', price: 45, imageUrl: '', category: 'شيفون' },
      { id: 'cb3', name: 'ستارة رول', description: 'رول كهربائي/يدوي', price: 350, imageUrl: '', category: 'ستائر رول' },
      { id: 'cb4', name: 'قضبان ستائر', description: 'قضبان معدنية - كل المقاسات', price: 65, imageUrl: '', category: 'إكسسوارات' },
      { id: 'cb5', name: 'ستارة رأسية', description: 'شرائح رأسية - PVC', price: 120, imageUrl: '', category: 'ستائر رأسية' },
      { id: 'cb6', name: 'كرانيش تركيب', description: 'كرانيش خشب/ألوميتال', price: 35, imageUrl: '', category: 'إكسسوارات' },
    ],
    categories: ['الكل', 'بلاك أوت', 'شيفون', 'ستائر رول', 'ستائر رأسية', 'إكسسوارات'],
    defaultShopName: 'ستائر النخبة',
    defaultShopDescription: 'ستائر وبراقع بكل المقاسات',
    bannerImage: 'https://images.unsplash.com/photo-1586086009783-9d2c0c0c0c0c?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1586086009783-9d2c0c0c0c0c?w=400',
    productsTabLabel: 'الستائر',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل الستائر',
    footerDescription: 'ستائر بلاك أوت وشيفون ورول بكل المقاسات',
  },
  sofasUpholstery: {
    marqueeOffers: ['🛋️ تنجيد وتجديد الكنب!', '📏 تصنيع حسب المقاس!', '⭐ ضمان على التنجيد!'],
    aboutTitle: 'كنبنا وتنجيدنا',
    aboutText: 'تصنيع وتنجيد الكنب والانتريهات بأرقى الأقمشة وأفضل التصميمات.',
    aboutImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
    storyTitle: 'خدمات الإصلاح والتجديد',
    storyText: 'نوفر خدمة تغيير أقمشة الكنب وإصلاح وتجديد الأثاث القديم ليصبح كالجديد.',
    storyImage: 'https://images.unsplash.com/photo-1567538096630-e0c55bd63714?w=400',
    highlightedTitle: 'أبرز الموديلات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'su1', name: 'انتريه 3+2+1', description: 'تنجيد قطن - تصنيع', price: 12000, imageUrl: '', category: 'انتريهات' },
      { id: 'su2', name: 'كنب ركنة', description: 'ركنة L - تخزين', price: 8500, imageUrl: '', category: 'ركنات' },
      { id: 'su3', name: 'كرسي سينجل', description: 'كرسي مفرد - تنجيد', price: 1800, imageUrl: '', category: 'كراسي' },
      { id: 'su4', name: 'تغيير قماش كنب', description: 'تجديد - قماش حسب الطلب', price: 2500, imageUrl: '', category: 'خدمات' },
      { id: 'su5', name: 'وسائد تنجيد', description: 'وسائد ديكور - ألوان', price: 120, imageUrl: '', category: 'إكسسوارات' },
      { id: 'su6', name: 'كنب مكتبي', description: 'كنب مكتب - جلد', price: 4500, imageUrl: '', category: 'كنب مكتبي' },
    ],
    categories: ['الكل', 'انتريهات', 'ركنات', 'كراسي', 'خدمات', 'إكسسوارات'],
    defaultShopName: 'كنب الراحة',
    defaultShopDescription: 'تصنيع وترجيد الكنب',
    bannerImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1567538096630-e0c55bd63714?w=400',
    productsTabLabel: 'التصميمات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل الموديلات',
    footerDescription: 'تصنيع وتنجيد الكنب والانتريهات بأرقى الأقمشة',
  },
  mattressesBedding: {
    marqueeOffers: ['🛏️ مراتب طبية بضمان!', '🚚 توصيل وتركيب مجاني!', '⭐ خصم على أطقم الملايات!'],
    aboutTitle: 'مراتبنا ومستلزماتنا',
    aboutText: 'مراتب طبية واسفنج وطبيعي بكل المقاسات مع ملايات ومفارش عالية الجودة.',
    aboutImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400',
    storyTitle: 'خدماتنا وضماناتنا',
    storyText: 'نوفر مراتب بدرجات راحة مختلفة مع ضمان وخدمة توصيل وتركيب مجانية.',
    storyImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400',
    highlightedTitle: 'أبرز المراتب',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'mb1', name: 'مرتبة طبية كينج', description: 'ميموري فوم - ضمان 10 سنوات', price: 3500, imageUrl: '', category: 'مراتب طبية' },
      { id: 'mb2', name: 'مرتبة اسفنج كوين', description: 'اسفنج عالي الكثافة', price: 1800, imageUrl: '', category: 'مراتب اسفنج' },
      { id: 'mb3', name: 'طقم ملايات كينج', description: 'قطن مصري - 4 قطع', price: 280, imageUrl: '', category: 'ملايات' },
      { id: 'mb4', name: 'مخدة طبية', description: 'ميموري فوم - قطن', price: 120, imageUrl: '', category: 'مخدات' },
      { id: 'mb5', name: 'لحاف قطني كينج', description: 'قطن طبيعي - خفيف', price: 220, imageUrl: '', category: 'لحاف' },
      { id: 'mb6', name: 'واقي مرتبة', description: 'واقي ماء - كوين', price: 95, imageUrl: '', category: 'إكسسوارات' },
    ],
    categories: ['الكل', 'مراتب طبية', 'مراتب اسفنج', 'ملايات', 'مخدات', 'لحاف'],
    defaultShopName: 'مراتب الراحة',
    defaultShopDescription: 'مراتب ومستلزمات نوم',
    bannerImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المراتب',
    footerDescription: 'مراتب طبية واسفنج وطبيعي بكل المقاسات',
  },
  furniture: {
    marqueeOffers: ['🪑 تشكيلة أثاث جديدة!', '🚚 توصيل وتركيب مجاني!', '⭐ تصنيع حسب الطلب!'],
    aboutTitle: 'معرضنا وتصنيعنا',
    aboutText: 'أثاث وغرف كاملة بتصاميم عصرية وخامات فاخرة مع خدمة التركيب.',
    aboutImage: 'https://images.unsplash.com/photo-1567538096630-e0c55bd63714?w=400',
    storyTitle: 'خدمات التصنيع والتركيب',
    storyText: 'نوفر تصنيع الأثاث حسب الطلب وتوصيل وتركيب احترافي لكل المنتجات.',
    storyImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
    highlightedTitle: 'أبرز القطع',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'fr1', name: 'غرفة نوم كاملة', description: 'سرير + كومودينو + تسريحة', price: 15000, imageUrl: '', category: 'غرف نوم' },
      { id: 'fr2', name: 'غرفة معيشة', description: 'طاولة + كنب + وحدة تلفزيون', price: 12000, imageUrl: '', category: 'غرف معيشة' },
      { id: 'fr3', name: 'مكتب كمبيوتر', description: 'مكتب خشبي - تصميم عصري', price: 1800, imageUrl: '', category: 'مكاتب' },
      { id: 'fr4', name: 'مطبخ خشب', description: 'تصنيع حسب المقاس', price: 25000, imageUrl: '', category: 'مطابخ' },
      { id: 'fr5', name: 'طاولة سفرة', description: 'خشب زان - 6 كراسي', price: 4500, imageUrl: '', category: 'غرف معيشة' },
      { id: 'fr6', name: 'وحدة تلفزيون', description: 'خشب MDF - تصميم حديث', price: 2200, imageUrl: '', category: 'غرف معيشة' },
    ],
    categories: ['الكل', 'غرف نوم', 'غرف معيشة', 'مكاتب', 'مطابخ'],
    defaultShopName: 'معرض الأثاث',
    defaultShopDescription: 'أثاث وديكور لكل بيت',
    bannerImage: 'https://images.unsplash.com/photo-1567538096630-e0c55bd63714?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
    productsTabLabel: 'القطع',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المعرض',
    showAllLabel: 'عرض كل القطع',
    footerDescription: 'أثاث وغرف كاملة بتصاميم عصرية وخامات فاخرة',
  },
  homeGoods: {
    marqueeOffers: ['🏠 مستلزمات منزل جديدة!', '🚚 توصيل سريع!', '⭐ ضمان على جميع المنتجات!'],
    aboutTitle: 'منتجاتنا وأقسامنا',
    aboutText: 'كل ما يحتاجه منزلك من أدوات مطبخ وأجهزة صغيرة ومستلزمات تنظيم وتنظيف.',
    aboutImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    storyTitle: 'خدماتنا وضماناتنا',
    storyText: 'نوفر ضمان واستبدال على جميع المنتجات مع خدمة توصيل سريعة لكل المناطق.',
    storyImage: 'https://images.unsplash.com/photo-1556909114-44e3e9399a2e?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'أضف للسلة',
    products: [
      { id: 'hg1', name: 'طقم أواني طهي', description: '10 قطع - ستانلس ستيل', price: 850, imageUrl: '', category: 'أدوات مطبخ' },
      { id: 'hg2', name: 'خلاط كهربائي', description: '500 واط - 3 سرعات', price: 450, imageUrl: '', category: 'أجهزة صغيرة' },
      { id: 'hg3', name: 'طقم تخزين طعام', description: '12 علبة - بلاستيك غذائي', price: 180, imageUrl: '', category: 'تنظيم' },
      { id: 'hg4', name: 'مكنسة كهربائية', description: '1800 واط - بدون كيس', price: 1200, imageUrl: '', category: 'تنظيف' },
      { id: 'hg5', name: 'طقم سكاكين', description: '6 سكاكين + حامل', price: 320, imageUrl: '', category: 'أدوات مطبخ' },
      { id: 'hg6', name: 'منظم أدراج', description: 'منظم قابل للتعديل', price: 85, imageUrl: '', category: 'تنظيم' },
    ],
    categories: ['الكل', 'أدوات مطبخ', 'أجهزة صغيرة', 'تنظيم', 'تنظيف'],
    defaultShopName: 'مستلزمات المنزل',
    defaultShopDescription: 'كل ما يحتاجه منزلك',
    bannerImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1556909114-44e3e9399a2e?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'كل ما يحتاجه منزلك من أدوات وأجهزة بضمان',
  },
  goldJewelry: {
    marqueeOffers: ['💎 تشكيلة ذهب جديدة!', '✨ مصنعية مخفضة هذا الشهر!', '⭐ ضمان على جميع المشغولات!'],
    aboutTitle: 'مشغولاتنا وعياراتنا',
    aboutText: 'ذهب عيار 18 و21 و24 وألماس وأطقم بأرقى التصاميم وأفضل المصنعية.',
    aboutImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400',
    storyTitle: 'خدماتنا وضماناتنا',
    storyText: 'نوفر صيانة وتلميع وتفصيل حسب الطلب مع ضمان الأوزان والعيارات.',
    storyImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400',
    highlightedTitle: 'أبرز المشغولات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'gj1', name: 'طقم ذهب عيار 18', description: 'عقد + حلق + خاتم - 15جم', price: 18000, imageUrl: '', category: 'أطقم' },
      { id: 'gj2', name: 'خاتم ألماس', description: 'ألماس طبيعي - عيار 18', price: 25000, imageUrl: '', category: 'خواتم' },
      { id: 'gj3', name: 'دبل ذهب', description: 'زوج خواتم - عيار 21', price: 12000, imageUrl: '', category: 'دبل' },
      { id: 'gj4', name: 'سبيكة ذهب', description: 'سبيكة 50جم - عيار 24', price: 65000, imageUrl: '', category: 'سبائك' },
      { id: 'gj5', name: 'حلق ذهب', description: 'حلق ذهب - عيار 18', price: 5500, imageUrl: '', category: 'حلق' },
      { id: 'gj6', name: 'جنيه ذهب', description: 'جنيه ذهب - عيار 21', price: 8500, imageUrl: '', category: 'جنيهات' },
    ],
    categories: ['الكل', 'أطقم', 'خواتم', 'دبل', 'سبائك', 'حلق'],
    defaultShopName: 'مجوهرات النخبة',
    defaultShopDescription: 'ذهب ومجوهرات بأرقى التصاميم',
    bannerImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400',
    productsTabLabel: 'المشغولات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المشغولات',
    footerDescription: 'ذهب وألماس وأطقم بأرقى التصاميم وأفضل المصنعية',
  },
  silverAccessories: {
    marqueeOffers: ['✨ فضة عيار 925!', '🎁 تغليف هدايا مجاني!', '⭐ نقش أسماء مجاني!'],
    aboutTitle: 'فضتنا وإكسسواراتنا',
    aboutText: 'فضة عيار 925 وإكسسوارات وهدايا بتصاميم أنيقة وأسعار مناسبة.',
    aboutImage: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
    storyTitle: 'خدماتنا الخاصة',
    storyText: 'نوفر نقش الأسماء وتغليف الهدايا وتصليح وتعديل المقاسات.',
    storyImage: 'https://images.unsplash.com/photo-1535632066927-b778d64cea5d?w=400',
    highlightedTitle: 'أبرز القطع',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'sa1', name: 'سوار فضة 925', description: 'فضة استرليني - تصميم', price: 350, imageUrl: '', category: 'أساور' },
      { id: 'sa2', name: 'خاتم فضة', description: 'فضة 925 - حجر كريستال', price: 180, imageUrl: '', category: 'خواتم' },
      { id: 'sa3', name: 'سلسال فضة', description: 'سلسال - فضة 925', price: 250, imageUrl: '', category: 'سلاسل' },
      { id: 'sa4', name: 'حلق فضة', description: 'حلق نسائي - فضة', price: 150, imageUrl: '', category: 'حلق' },
      { id: 'sa5', name: 'دبلة فضة', description: 'زوج خواتم - فضة 925', price: 220, imageUrl: '', category: 'دبل' },
      { id: 'sa6', name: 'تعليقة فضة', description: 'تعليقة - تصميم حديث', price: 95, imageUrl: '', category: 'تعليقات' },
    ],
    categories: ['الكل', 'أساور', 'خواتم', 'سلاسل', 'حلق', 'دبل'],
    defaultShopName: 'فضة الأناقة',
    defaultShopDescription: 'فضة وإكسسوارات وهدايا',
    bannerImage: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1535632066927-b778d64cea5d?w=400',
    productsTabLabel: 'القطع',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل القطع',
    footerDescription: 'فضة عيار 925 وإكسسوارات وهدايا بتصاميم أنيقة',
  },
  watchesGifts: {
    marqueeOffers: ['⌚ ساعات ماركات أصلية!', '🎁 أطقم هدايا فاخرة!', '⭐ ضمان وكفالة!'],
    aboutTitle: 'ساعاتنا وهدايانا',
    aboutText: 'ساعات ماركات عالمية وعطور وأطقم هدايا فاخرة بضمان أصلي.',
    aboutImage: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400',
    storyTitle: 'خدماتنا وضماناتنا',
    storyText: 'نوفر ضمان أصلي وصيانة وقطع غيار وسيور وبطاريات لكل الساعات.',
    storyImage: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'wg1', name: 'ساعة رجالي كلاسيك', description: 'ماركة عالمية - ضمان', price: 1800, imageUrl: '', category: 'ساعات رجالي' },
      { id: 'wg2', name: 'ساعة حريمي', description: 'تصميم أنيق - كريستال', price: 1500, imageUrl: '', category: 'ساعات حريمي' },
      { id: 'wg3', name: 'طقم هدايا فاخر', description: 'ساعة + عطر + علبة', price: 2500, imageUrl: '', category: 'أطقم هدايا' },
      { id: 'wg4', name: 'عطر فرنسي 100مل', description: 'عطر أصلي - للرجال', price: 850, imageUrl: '', category: 'عطور' },
      { id: 'wg5', name: 'ساعة رياضية', description: 'مقاومة ماء - GPS', price: 2200, imageUrl: '', category: 'ساعات رجالي' },
      { id: 'wg6', name: 'سير ساعة', description: 'سير جلد أصلي', price: 120, imageUrl: '', category: 'إكسسوارات' },
    ],
    categories: ['الكل', 'ساعات رجالي', 'ساعات حريمي', 'أطقم هدايا', 'عطور'],
    defaultShopName: 'ساعات الهدايا',
    defaultShopDescription: 'ساعات وهدايا فاخرة',
    bannerImage: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'ساعات ماركات عالمية وعطور وأطقم هدايا فاخرة',
  },
  realEstate: {
    marqueeOffers: ['🏠 شقق وفلل للبيع والإيجار!', '📍 معاينات مجانية!', '⭐ أفضل العروض العقارية!'],
    aboutTitle: 'عقاراتنا وعروضنا',
    aboutText: 'شقق وفلل ومحلات للبيع والإيجار في أفضل المناطق بأسعار تنافسية.',
    aboutImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400',
    storyTitle: 'خدماتنا العقارية',
    storyText: 'نوفر خدمات الوساطة العقارية والمعاينات والاستشارات المجانية.',
    storyImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400',
    highlightedTitle: 'أبرز العقارات',
    ctaLabel: 'تفاصيل',
    products: [
      { id: 're1', name: 'شقة 180م - التجمع', description: '3 غرف + ريسبشن + حمامين', price: 2500000, imageUrl: '', category: 'شقق للبيع' },
      { id: 're2', name: 'فيلا 400م - الشيخ زايد', description: 'فيلا مستقلة + حديقة', price: 8500000, imageUrl: '', category: 'فلل للبيع' },
      { id: 're3', name: 'شقة 120م إيجار - مدينة نصر', description: '2 غرف + ريسبشن - تشطيب سوبر', price: 12000, imageUrl: '', category: 'شقق للإيجار' },
      { id: 're4', name: 'محل تجاري 50م', description: 'محل على طريق رئيسي', price: 1800000, imageUrl: '', category: 'محلات' },
      { id: 're5', name: 'مكتب إداري 80م', description: 'مكتب - تشطيب كامل', price: 900000, imageUrl: '', category: 'إداري' },
      { id: 're6', name: 'شقة 150م - المعادي', description: '3 غرف - إطلالة مميزة', price: 3200000, imageUrl: '', category: 'شقق للبيع' },
    ],
    categories: ['الكل', 'شقق للبيع', 'فلل للبيع', 'شقق للإيجار', 'محلات', 'إداري'],
    defaultShopName: 'عقارات النخبة',
    defaultShopDescription: 'بيع وإيجار عقارات',
    bannerImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400',
    productsTabLabel: 'العقارات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المكتب',
    showAllLabel: 'عرض كل العقارات',
    footerDescription: 'شقق وفلل ومحلات للبيع والإيجار بأفضل الأسعار',
  },
  lands: {
    marqueeOffers: ['📍 أراضي للبيع!', '📐 خرائط ومستندات متاحة!', '⭐ أسعار تنافسية!'],
    aboutTitle: 'أراضينا وعروضنا',
    aboutText: 'أراضي سكنية وتجارية وزراعية وصناعية بكل المساحات والمواقع.',
    aboutImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400',
    storyTitle: 'خدماتنا العقارية',
    storyText: 'نوفر خرائط ومستندات وتراخيص وخدمات تقسيط على الأراضي.',
    storyImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400',
    highlightedTitle: 'أبرز القطع',
    ctaLabel: 'تفاصيل',
    products: [
      { id: 'ln1', name: 'أرض سكنية 400م', description: 'بالعاصمة الإدارية - جاهزة', price: 1800000, imageUrl: '', category: 'أراضي سكنية' },
      { id: 'ln2', name: 'أرض تجارية 200م', description: 'الشيخ زايد - على طريق رئيسي', price: 2500000, imageUrl: '', category: 'أراضي تجارية' },
      { id: 'ln3', name: 'أرض زراعية 5 فدان', description: 'طريق الإسكندرية الصحراوي', price: 1500000, imageUrl: '', category: 'أراضي زراعية' },
      { id: 'ln4', name: 'أرض صناعية 2000م', description: 'منطقة صناعية - مرافق كاملة', price: 3200000, imageUrl: '', category: 'أراضي صناعية' },
      { id: 'ln5', name: 'أرض استثمارية 1000م', description: 'موقع مميز - عائد مرتفع', price: 4500000, imageUrl: '', category: 'أراضي استثمارية' },
      { id: 'ln6', name: 'أرض سكنية 300م', description: 'التجمع الخامس - جاهزة', price: 1350000, imageUrl: '', category: 'أراضي سكنية' },
    ],
    categories: ['الكل', 'أراضي سكنية', 'أراضي تجارية', 'أراضي زراعية', 'أراضي صناعية'],
    defaultShopName: 'أراضي الاستثمار',
    defaultShopDescription: 'أراضي للبيع والإيجار',
    bannerImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400',
    productsTabLabel: 'القطع',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المكتب',
    showAllLabel: 'عرض كل القطع',
    footerDescription: 'أراضي سكنية وتجارية وزراعية وصناعية بكل المساحات',
  },
  contractors: {
    marqueeOffers: ['🔨 مقاولات وتشطيبات!', '📋 مقايسات مجانية!', '⭐ ضمان على الأعمال!'],
    aboutTitle: 'خدماتنا ومقاولاتنا',
    aboutText: 'مقاولات وتشطيبات وتصميم داخلي بأفضل الخامات وأدق التفاصيل.',
    aboutImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400',
    storyTitle: 'خدماتنا ومقايساتنا',
    storyText: 'نوفر مقايسات مجانية وإشراف هندسي وفرق متخصصة لكل الأعمال.',
    storyImage: 'https://images.unsplash.com/photo-1541888946335-18c1e6965b0a?w=400',
    highlightedTitle: 'أبرز الخدمات',
    ctaLabel: 'اطلب مقايسة',
    products: [
      { id: 'ct1', name: 'تشطيب شقة 150م', description: 'تشطيب سوبر لوكس - كامل', price: 250000, imageUrl: '', category: 'تشطيب شقق' },
      { id: 'ct2', name: 'تشطيب فيلا 400م', description: 'تشطيب كامل + ديكور', price: 650000, imageUrl: '', category: 'تشطيب فلل' },
      { id: 'ct3', name: 'تصميم داخلي', description: 'تصميم 3D + تنفيذ', price: 85000, imageUrl: '', category: 'تصميم داخلي' },
      { id: 'ct4', name: 'أعمال كهرباء', description: 'تمديدات كهرباء كاملة', price: 35000, imageUrl: '', category: 'كهرباء' },
      { id: 'ct5', name: 'أعمال سباكة', description: 'سباكة كاملة + صحي', price: 28000, imageUrl: '', category: 'سباكة' },
      { id: 'ct6', name: 'دهانات وديكور', description: 'دهانات + جبس بورد', price: 22000, imageUrl: '', category: 'دهانات' },
    ],
    categories: ['الكل', 'تشطيب شقق', 'تشطيب فلل', 'تصميم داخلي', 'كهرباء', 'سباكة'],
    defaultShopName: 'مقاولات التشطيب',
    defaultShopDescription: 'مقاولات وتشطيبات وديكور',
    bannerImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1541888946335-18c1e6965b0a?w=400',
    productsTabLabel: 'الخدمات',
    galleryTabLabel: 'أعمالنا',
    infoTabLabel: 'معلومات الشركة',
    showAllLabel: 'عرض كل الخدمات',
    footerDescription: 'مقاولات وتشطيبات وتصميم داخلي بأفضل الخامات',
  },
  building_supplies: {
    marqueeOffers: ['🧱 مواد بناء بأسعار جملة!', '🚚 توريد ونقل مجاني!', '⭐ خصم على الكميات!'],
    aboutTitle: 'موادنا ومنتجاتنا',
    aboutText: 'أسمنت وحديد ودهانات ومواد بناء بكل الأنواع بأسعار جملة وتجزئة.',
    aboutImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    storyTitle: 'خدمات التوريد والنقل',
    storyText: 'نوفر توريد ونقل المواد لمواقع البناء بأسعار تنافسية وسرعة في التوصيل.',
    storyImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'أضف للسلة',
    products: [
      { id: 'bs1', name: 'أسمنت بورتلاندي 50كجم', description: 'أسمنت عادي - مقاوم', price: 95, imageUrl: '', category: 'أسمنت' },
      { id: 'bs2', name: 'حديد تسليح طن', description: 'حديد عالي المقاومة - 12مل', price: 28000, imageUrl: '', category: 'حديد' },
      { id: 'bs3', name: 'دهان بلاستيك 4كجم', description: 'دهان داخلي - أبيض', price: 180, imageUrl: '', category: 'دهانات' },
      { id: 'bs4', name: 'بلاط سيراميك م²', description: 'بلاط أرضيات - 60x60', price: 65, imageUrl: '', category: 'بلاط وسيراميك' },
      { id: 'bs5', name: 'مواد عزل م²', description: 'عزل مائي وحراري', price: 45, imageUrl: '', category: 'مواد عزل' },
      { id: 'bs6', name: 'خشب MDF لوح', description: 'MDF - 18مم - 244x122سم', price: 350, imageUrl: '', category: 'خشب' },
    ],
    categories: ['الكل', 'أسمنت', 'حديد', 'دهانات', 'بلاط وسيراميك', 'مواد عزل'],
    defaultShopName: 'مواد البناء',
    defaultShopDescription: 'مواد بناء ودهانات',
    bannerImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'أسمنت وحديد ودهانات ومواد بناء بأسعار جملة وتجزئة',
  },
  carShowroom: {
    marqueeOffers: ['🚗 سيارات جديدة ومستعملة!', '💰 تقسيط وتمويل متاح!', '⭐ تجارب قيادة مجانية!'],
    aboutTitle: 'معرضنا وسياراتنا',
    aboutText: 'سيارات جديدة ومستعملة بضمان وشفافية كاملة مع خدمات تقسيط وتمويل.',
    aboutImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=400',
    storyTitle: 'خدماتنا وضماناتنا',
    storyText: 'نوفر تجارب قيادة ومعاينات فنية وخدمات تمويل وتقسيط وضمان على السيارات.',
    storyImage: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400',
    highlightedTitle: 'أبرز السيارات',
    ctaLabel: 'تفاصيل',
    products: [
      { id: 'cs1', name: 'تويوتا كورولا 2024', description: 'جديدة - 1600سي سي - أوتوماتيك', price: 650000, imageUrl: '', category: 'سيارات جديدة' },
      { id: 'cs2', name: 'هيونداي توسان 2023', description: 'مستعملة - 25000كم - فل أوبشن', price: 780000, imageUrl: '', category: 'سيارات مستعملة' },
      { id: 'cs3', name: 'كيا سيراتو 2024', description: 'جديدة - 1600سي سي - مانيوال', price: 580000, imageUrl: '', category: 'سيارات جديدة' },
      { id: 'cs4', name: 'نيسان صني 2022', description: 'مستعملة - 30000كم - أوتوماتيك', price: 420000, imageUrl: '', category: 'سيارات مستعملة' },
      { id: 'cs5', name: 'تويوتا يارس 2024', description: 'جديدة - 1300سي سي - أوتوماتيك', price: 480000, imageUrl: '', category: 'سيارات جديدة' },
      { id: 'cs6', name: 'شيفروليه أوبترا 2023', description: 'مستعملة - 15000كم - فل', price: 520000, imageUrl: '', category: 'سيارات مستعملة' },
    ],
    categories: ['الكل', 'سيارات جديدة', 'سيارات مستعملة'],
    defaultShopName: 'معرض السيارات',
    defaultShopDescription: 'سيارات بيع وتقسيط',
    bannerImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400',
    productsTabLabel: 'السيارات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المعرض',
    showAllLabel: 'عرض كل السيارات',
    footerDescription: 'سيارات جديدة ومستعملة بضمان وشفافية كاملة',
  },
  auto_services: {
    marqueeOffers: ['🔧 صيانة سيارات احترافية!', '⏰ مواعيد منزلية!', '⭐ باقات صيانة بأسعار خاصة!'],
    aboutTitle: 'ورشتنا وخدماتنا',
    aboutText: 'ميكانيكا وكهرباء وسمكرة ودهان وصيانة دورية بفنيين متخصصين.',
    aboutImage: 'https://images.unsplash.com/photo-1632823471565-1ecdf5c6da77?w=400',
    storyTitle: 'خدماتنا وباقاتنا',
    storyText: 'نوفر صيانة دورية وفحص شامل وباقات صيانة بأسعار مخفضة وخدمات منزلية.',
    storyImage: 'https://images.unsplash.com/photo-1486758539027-9f0b09db5b3a?w=400',
    highlightedTitle: 'أبرز الخدمات',
    ctaLabel: 'احجز موعد',
    products: [
      { id: 'as1', name: 'صيانة دورية كاملة', description: 'زيت + فلتر + فحص شامل', price: 850, imageUrl: '', category: 'صيانة دورية' },
      { id: 'as2', name: 'فحص وتشخيص كمبيوتر', description: 'فحص إلكتروني شامل', price: 250, imageUrl: '', category: 'فحص' },
      { id: 'as3', name: 'سمكرة ودهان باب', description: 'سمكرة + دهان كامل', price: 1200, imageUrl: '', category: 'سمكرة ودهان' },
      { id: 'as4', name: 'تغيير زيت محرك', description: 'زيت + فلتر - جميع الأنواع', price: 350, imageUrl: '', category: 'صيانة دورية' },
      { id: 'as5', name: 'تكييف سيارة', description: 'شحن تكييف + فحص', price: 450, imageUrl: '', category: 'تكييف' },
      { id: 'as6', name: 'بطارية سيارة', description: 'بطارية جديدة - ضمان', price: 850, imageUrl: '', category: 'بطاريات' },
    ],
    categories: ['الكل', 'صيانة دورية', 'فحص', 'سمكرة ودهان', 'تكييف', 'بطاريات'],
    defaultShopName: 'ورشة السيارات',
    defaultShopDescription: 'صيانة وورش سيارات',
    bannerImage: 'https://images.unsplash.com/photo-1632823471565-1ecdf5c6da77?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1486758539027-9f0b09db5b3a?w=400',
    productsTabLabel: 'الخدمات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات الورشة',
    showAllLabel: 'عرض كل الخدمات',
    footerDescription: 'ميكانيكا وكهرباء وسمكرة ودهان وصيانة دورية',
  },
  auto_parts: {
    marqueeOffers: ['⚙️ قطع غيار أصلية!', '🚚 توصيل سريع!', '⭐ ضمان على القطع!'],
    aboutTitle: 'قطعنا وإكسسواراتنا',
    aboutText: 'قطع غيار أصلية وتجارية وإطارات وبطاريات وزيوت بكل الموديلات.',
    aboutImage: 'https://images.unsplash.com/photo-1632823469928-45f8e8c0e8a0?w=400',
    storyTitle: 'خدماتنا وضماناتنا',
    storyText: 'نوفر قطع غيار متوافقة مع جميع الموديلات مع خدمة تركيب وضمان.',
    storyImage: 'https://images.unsplash.com/photo-1486262715619-67ee85b12fed?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'أضف للسلة',
    products: [
      { id: 'ap1', name: 'فلتر زيت', description: 'فلتر زيت أصلي - جميع الموديلات', price: 65, imageUrl: '', category: 'فلاتر' },
      { id: 'ap2', name: 'إطار 195/65 R15', description: 'إطار جديد - ضمان', price: 850, imageUrl: '', category: 'إطارات' },
      { id: 'ap3', name: 'بطارية 70 أمبير', description: 'بطارية - ضمان سنة', price: 950, imageUrl: '', category: 'بطاريات' },
      { id: 'ap4', name: 'زيت محرك 5W-30', description: 'زيت صناعي - 4 لتر', price: 280, imageUrl: '', category: 'زيوت' },
      { id: 'ap5', name: 'فلتر هواء', description: 'فلتر هواء أصلي', price: 85, imageUrl: '', category: 'فلاتر' },
      { id: 'ap6', name: 'توصيلات أمامي', description: 'توصيلات - أصلية', price: 450, imageUrl: '', category: 'قطع ميكانيكا' },
    ],
    categories: ['الكل', 'فلاتر', 'إطارات', 'بطاريات', 'زيوت', 'قطع ميكانيكا'],
    defaultShopName: 'قطع الغيار',
    defaultShopDescription: 'قطع غيار وإطارات وإكسسوارات',
    bannerImage: 'https://images.unsplash.com/photo-1632823469928-45f8e8c0e8a0?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1486262715619-67ee85b12fed?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'قطع غيار أصلية وتجارية وإطارات وبطاريات وزيوت',
  },
  agri_supplies: {
    marqueeOffers: ['🌱 بذور وشتلات جديدة!', '🚚 توصيل للمزارع!', '⭐ عروض على الأسمدة!'],
    aboutTitle: 'منتجاتنا الزراعية',
    aboutText: 'بذور وشتلات وأسمدة ومبيدات ومستلزمات زراعية بكل الأنواع.',
    aboutImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    storyTitle: 'خدماتنا وإرشاداتنا',
    storyText: 'نوفر إرشادات زراعية ومستلزمات لكل المواسم مع خدمة توصيل للمزارع.',
    storyImage: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'أضف للسلة',
    products: [
      { id: 'ag1', name: 'بذور طماطم هجين', description: 'بذور عالية الإنتاجية - 10جم', price: 45, imageUrl: '', category: 'بذور' },
      { id: 'ag2', name: 'شتلة مانجو', description: 'شتلة مطعمة - جاهزة للزراعة', price: 35, imageUrl: '', category: 'شتلات' },
      { id: 'ag3', name: 'سماد نيتروجين 50كجم', description: 'سماد مركب - NPK', price: 280, imageUrl: '', category: 'أسمدة' },
      { id: 'ag4', name: 'مبيد حشري 1 لتر', description: 'مبيد آفات - آمن', price: 150, imageUrl: '', category: 'مبيدات' },
      { id: 'ag5', name: 'خرطوم ري 50م', description: 'خرطوم ري بالتنقيط', price: 120, imageUrl: '', category: 'ري' },
      { id: 'ag6', name: 'تربة زراعية شيكارة', description: 'تربة عضوية - 25كجم', price: 65, imageUrl: '', category: 'تربة' },
    ],
    categories: ['الكل', 'بذور', 'شتلات', 'أسمدة', 'مبيدات', 'ري'],
    defaultShopName: 'مستلزمات زراعية',
    defaultShopDescription: 'بذور وأسمدة ومستلزمات',
    bannerImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'بذور وشتلات وأسمدة ومبيدات ومستلزمات زراعية',
  },
  nurseries_landscaping: {
    marqueeOffers: ['🌿 نباتات داخلية وخارجية!', '🌳 تصميم حدائق!', '⭐ صيانة دورية متاحة!'],
    aboutTitle: 'مشتلنا وخدماتنا',
    aboutText: 'نباتات داخلية وخارجية وأشجار ونجيلة وتصميم وصيانة حدائق.',
    aboutImage: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400',
    storyTitle: 'خدمات التنسيق والصيانة',
    storyText: 'نوفر تصميم حدائق وتركيب شبكات ري وصيانة دورية للنباتات والحدائق.',
    storyImage: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400',
    highlightedTitle: 'أبرز النباتات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'nl1', name: 'نبتة داخلية - بوتس', description: 'نبتة زينة - أصيص 20سم', price: 85, imageUrl: '', category: 'نباتات داخلية' },
      { id: 'nl2', name: 'أشجار زينة', description: 'شجرة - طول 1.5م', price: 350, imageUrl: '', category: 'أشجار' },
      { id: 'nl3', name: 'نجيلة طبيعية م²', description: 'نجيلة - زراعة وتركيب', price: 45, imageUrl: '', category: 'نجيلة' },
      { id: 'nl4', name: 'تصميم حديقة', description: 'تصميم + تنفيذ - م²', price: 250, imageUrl: '', category: 'تصميم حدائق' },
      { id: 'nl5', name: 'صيانة حديقة شهرية', description: 'اشتراك صيانة - شهري', price: 350, imageUrl: '', category: 'صيانة' },
      { id: 'nl6', name: 'شبكة ري بالتنقيط', description: 'تركيب + مواد - م²', price: 85, imageUrl: '', category: 'ري' },
    ],
    categories: ['الكل', 'نباتات داخلية', 'أشجار', 'نجيلة', 'تصميم حدائق', 'صيانة'],
    defaultShopName: 'مشتل الزينة',
    defaultShopDescription: 'نباتات وتنسيق حدائق',
    bannerImage: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400',
    productsTabLabel: 'النباتات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المشتل',
    showAllLabel: 'عرض كل النباتات',
    footerDescription: 'نباتات داخلية وخارجية وتصميم وصيانة حدائق',
  },
  serviceCompanies: {
    marqueeOffers: ['🏢 خدمات شركات متكاملة!', '📋 عقود سنوية بأسعار خاصة!', '⭐ فرق متخصصة!'],
    aboutTitle: 'خدماتنا وباقاتنا',
    aboutText: 'صيانة وتنظيف وأمن ونقل وإدارة مرافق وخدمات عقارية للشركات والأفراد.',
    aboutImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
    storyTitle: 'عقودنا وخدماتنا',
    storyText: 'نوفر عقود سنوية واشتراكات شهرية وفرق متخصصة لكل الخدمات.',
    storyImage: 'https://images.unsplash.com/photo-1497366811353-678077373537?w=400',
    highlightedTitle: 'أبرز الخدمات',
    ctaLabel: 'اطلب خدمة',
    products: [
      { id: 'sc1', name: 'صيانة عامة شهرية', description: 'اشتراك - زيارات شهرية', price: 1500, imageUrl: '', category: 'صيانة عامة' },
      { id: 'sc2', name: 'تنظيف مكتب', description: 'تنظيف كامل - مرة أسبوعياً', price: 800, imageUrl: '', category: 'تنظيف' },
      { id: 'sc3', name: 'خدمة أمن وحراسة', description: 'حارس - 12 ساعة', price: 2500, imageUrl: '', category: 'أمن وحراسة' },
      { id: 'sc4', name: 'نقل أثاث مكتب', description: 'نقل + تغليف + تركيب', price: 3500, imageUrl: '', category: 'نقل ورفع' },
      { id: 'sc5', name: 'إدارة مرافق', description: 'عقد سنوي - شامل', price: 12000, imageUrl: '', category: 'إدارة مرافق' },
      { id: 'sc6', name: 'تعقيم وآفات', description: 'تعقيم شامل - ضمان', price: 650, imageUrl: '', category: 'تعقيم' },
    ],
    categories: ['الكل', 'صيانة عامة', 'تنظيف', 'أمن وحراسة', 'نقل ورفع', 'إدارة مرافق'],
    defaultShopName: 'شركة خدمات',
    defaultShopDescription: 'خدمات شركات وأفراد',
    bannerImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1497366811353-678077373537?w=400',
    productsTabLabel: 'الخدمات',
    galleryTabLabel: 'أعمالنا',
    infoTabLabel: 'معلومات الشركة',
    showAllLabel: 'عرض كل الخدمات',
    footerDescription: 'صيانة وتنظيف وأمن ونقل وإدارة مرافق للشركات والأفراد',
  },
  individualTechnicians: {
    marqueeOffers: ['🔧 معلم وفني محترف!', '🏠 زيارات منزلية!', '⭐ ضمان على الشغل!'],
    aboutTitle: 'مهاراتنا وخدماتنا',
    aboutText: 'سباك وكهربائي ونجار ونقاش وتكييف وفني أجهزة منزلية بزيارات منزلية.',
    aboutImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400',
    storyTitle: 'خدماتنا ومناطق العمل',
    storyText: 'نوفر زيارات منزلية برسوم معروفة وضمان على جميع الأعمال.',
    storyImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    highlightedTitle: 'أبرز الخدمات',
    ctaLabel: 'احجز زيارة',
    products: [
      { id: 'it1', name: 'كهربائي منزلي', description: 'إصلاح + تركيب - زيارة', price: 150, imageUrl: '', category: 'كهرباء' },
      { id: 'it2', name: 'سباك منزلي', description: 'إصلاح + تركيب - زيارة', price: 120, imageUrl: '', category: 'سباكة' },
      { id: 'it3', name: 'نجار منزلي', description: 'إصلاح أثاث + تركيب', price: 180, imageUrl: '', category: 'نجارة' },
      { id: 'it4', name: 'نقاش ودهانات', description: 'دهان غرفة - كامل', price: 350, imageUrl: '', category: 'دهانات' },
      { id: 'it5', name: 'صيانة تكييف', description: 'تنظيف + شحن + إصلاح', price: 250, imageUrl: '', category: 'تكييف' },
      { id: 'it6', name: 'صيانة غسالة', description: 'إصلاح + قطع غيار', price: 200, imageUrl: '', category: 'أجهزة منزلية' },
    ],
    categories: ['الكل', 'كهرباء', 'سباكة', 'نجارة', 'دهانات', 'تكييف'],
    defaultShopName: 'معلم فني',
    defaultShopDescription: 'فنيين وخدمات منزلية',
    bannerImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    productsTabLabel: 'الخدمات',
    galleryTabLabel: 'أعمالنا',
    infoTabLabel: 'معلومات الفني',
    showAllLabel: 'عرض كل الخدمات',
    footerDescription: 'سباك وكهربائي ونجار ونقاش وتكييف بزيارات منزلية',
  },
  workshops: {
    marqueeOffers: ['🔨 ورش تصنيع وإصلاح!', '📐 تصنيع حسب الطلب!', '⭐ خامات أصلية!'],
    aboutTitle: 'ورشتنا وأعمالنا',
    aboutText: 'نجارة وحدادة وألوميتال وزجاج وتصنيع حسب الطلب وإصلاح المعدات.',
    aboutImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400',
    storyTitle: 'خدماتنا وطلباتنا',
    storyText: 'نوفر تصنيع حسب الطلب وإصلاح وقطع غيار بأفضل الخامات.',
    storyImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    highlightedTitle: 'أبرز الأعمال',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'ws1', name: 'تصنيع كنب حسب الطلب', description: 'تصميم + تصنيع + تركيب', price: 8000, imageUrl: '', category: 'تصنيع' },
      { id: 'ws2', name: 'حدادة أبواب', description: 'باب حديد - تصميم', price: 2500, imageUrl: '', category: 'حدادة' },
      { id: 'ws3', name: 'ألوميتال شبابيك', description: 'ألوميتال - تركيب', price: 1200, imageUrl: '', category: 'ألوميتال' },
      { id: 'ws4', name: 'زجاج ومرايا', description: 'زجاج - قص وتركيب', price: 350, imageUrl: '', category: 'زجاج' },
      { id: 'ws5', name: 'إصلاح معدات', description: 'صيانة - تشخيص + إصلاح', price: 200, imageUrl: '', category: 'إصلاح' },
      { id: 'ws6', name: 'أعمال ستانلس', description: 'ستانلس - تصنيع', price: 1500, imageUrl: '', category: 'ستانلس' },
    ],
    categories: ['الكل', 'تصنيع', 'حدادة', 'ألوميتال', 'زجاج', 'إصلاح'],
    defaultShopName: 'الورشة',
    defaultShopDescription: 'ورش تصنيع وإصلاح',
    bannerImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400',
    productsTabLabel: 'الخدمات',
    galleryTabLabel: 'أعمالنا',
    infoTabLabel: 'معلومات الورشة',
    showAllLabel: 'عرض كل الخدمات',
    footerDescription: 'نجارة وحدادة وألوميتال وزجاج وتصنيع حسب الطلب',
  },
  electronics: {
    marqueeOffers: ['📱 موبايلات ولابتوبات!', '🔧 صيانة وضمان!', '⭐ عروض على الإكسسوارات!'],
    aboutTitle: 'منتجاتنا وخدماتنا',
    aboutText: 'موبايلات ولابتوب وتابلت وإكسسوارات وصيانة وضمان على كل الأجهزة.',
    aboutImage: 'https://images.unsplash.com/photo-1498049794561-673ee4ac08fb?w=400',
    storyTitle: 'خدمات الصيانة والضمان',
    storyText: 'نوفر صيانة أصلية وضمان وقطع غيار أصلية لكل الأجهزة.',
    storyImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'أضف للسلة',
    products: [
      { id: 'el1', name: 'موبايل سامسونج A55', description: '256جم - 8 رام - 5G', price: 8500, imageUrl: '', category: 'موبايلات' },
      { id: 'el2', name: 'لابتوب HP', description: 'i7 - 16 رام - 512 SSD', price: 22000, imageUrl: '', category: 'لابتوب' },
      { id: 'el3', name: 'تابلت سامسونج', description: '11 إنش - 128جم - WiFi', price: 6500, imageUrl: '', category: 'تابلت' },
      { id: 'el4', name: 'سماعة بلوتوث', description: 'سماعة لاسلكية - ضوضاء', price: 850, imageUrl: '', category: 'إكسسوارات' },
      { id: 'el5', name: 'شاحن سريع 65W', description: 'شاحن أصلي - Type-C', price: 350, imageUrl: '', category: 'إكسسوارات' },
      { id: 'el6', name: 'صيانة شاشة موبايل', description: 'تغيير شاشة - أصلي', price: 1200, imageUrl: '', category: 'صيانة' },
    ],
    categories: ['الكل', 'موبايلات', 'لابتوب', 'تابلت', 'إكسسوارات', 'صيانة'],
    defaultShopName: 'إلكترونيات',
    defaultShopDescription: 'موبايلات وكمبيوتر وصيانة',
    bannerImage: 'https://images.unsplash.com/photo-1498049794561-673ee4ac08fb?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'موبايلات ولابتوب وتابلت وإكسسوارات وصيانة وضمان',
  },
  health: {
    marqueeOffers: ['💊 أدوية ومستحضرات!', '🚚 توصيل أدوية مجاني!', '⭐ عروض على مكملات غذائية!'],
    aboutTitle: 'صيدليتنا ومنتجاتنا',
    aboutText: 'أدوية ومستحضرات تجميل وأجهزة طبية ومكملات غذائية بكل الأنواع.',
    aboutImage: 'https://images.unsplash.com/photo-1587854692152-cbe611db43a7?w=400',
    storyTitle: 'خدماتنا ومتابعتنا',
    storyText: 'نوفر خدمة الروشتات الإلكترونية والطلبات المتكررة وتوصيل الأدوية.',
    storyImage: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'أضف للسلة',
    products: [
      { id: 'hl1', name: 'باراسيتامول 500mg', description: '20 قرص - مسكن', price: 15, imageUrl: '', category: 'أدوية' },
      { id: 'hl2', name: 'فيتامين سي 1000mg', description: '30 قرص فوار - مكمل', price: 85, imageUrl: '', category: 'مكملات' },
      { id: 'hl3', name: 'كريم مرطب', description: 'مرطب بشرة - 50مل', price: 120, imageUrl: '', category: 'مستحضرات' },
      { id: 'hl4', name: 'جهاز ضغط', description: 'جهاز ضغط رقمي - ذراع', price: 650, imageUrl: '', category: 'أجهزة طبية' },
      { id: 'hl5', name: 'ميزان حرارة رقمي', description: 'ترمومتر رقمي', price: 45, imageUrl: '', category: 'أجهزة طبية' },
      { id: 'hl6', name: 'ماسك طبي 50 قطعة', description: 'ماسك 3 طبقات', price: 35, imageUrl: '', category: 'مستحضرات' },
    ],
    categories: ['الكل', 'أدوية', 'مكملات', 'مستحضرات', 'أجهزة طبية'],
    defaultShopName: 'صيدلية',
    defaultShopDescription: 'أدوية ومستحضرات وأجهزة طبية',
    bannerImage: 'https://images.unsplash.com/photo-1587854692152-cbe611db43a7?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات الصيدلية',
    showAllLabel: 'عرض كل المنتجات',
    footerDescription: 'أدوية ومستحضرات تجميل وأجهزة طبية ومكملات غذائية',
  },
  other: {
    marqueeOffers: ['🎉 عروض مميزة!', '🚚 توصيل سريع!', '⭐ جودة مضمونة!'],
    aboutTitle: 'من نحن',
    aboutText: 'نقدم أفضل المنتجات والخدمات لعملائنا بجودة عالية وأسعار تنافسية.',
    aboutImage: UNSPLASH_FOOD,
    storyTitle: 'خدماتنا وعروضنا',
    storyText: 'استمتع بتجربة تسوق متكاملة مع خيارات دفع آمنة وتوصيل سريع.',
    storyImage: UNSPLASH_FASHION,
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'ot1', name: 'منتج 1', description: 'وصف المنتج الأول', price: 129, imageUrl: '', category: 'منتجات' },
      { id: 'ot2', name: 'منتج 2', description: 'وصف المنتج الثاني', price: 199, imageUrl: '', category: 'خدمات' },
      { id: 'ot3', name: 'منتج 3', description: 'وصف المنتج الثالث', price: 259, imageUrl: '', category: 'منتجات' },
      { id: 'ot4', name: 'منتج 4', description: 'وصف المنتج الرابع', price: 319, imageUrl: '', category: 'خدمات' },
      { id: 'ot5', name: 'منتج 5', description: 'وصف المنتج الخامس', price: 89, imageUrl: '', category: 'عام' },
      { id: 'ot6', name: 'منتج 6', description: 'وصف المنتج السادس', price: 149, imageUrl: '', category: 'عام' },
    ],
    categories: ['الكل', 'منتجات', 'خدمات', 'عام'],
    defaultShopName: 'متجري',
    defaultShopDescription: 'منتجات وخدمات متنوعة',
    bannerImage: 'https://images.unsplash.com/photo-1441986300917-64674bd4d8d8?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1441986300917-64674bd4d8d8?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المتجر',
    showAllLabel: 'عرض الكل',
    footerDescription: 'نقدم أفضل المنتجات والخدمات بجودة عالية',
  },
  factories: {
    marqueeOffers: ['🏭 خط إنتاج متكامل!', '📦 جودة وسرعة في التوريد!', '✅ خامات معتمدة ومختبرة!'],
    aboutTitle: 'مصنعنا وخطوط الإنتاج',
    aboutText: 'نقدم منتجات بجودة عالية بخطوط إنتاج حديثة وخامات معتمدة ومختبرة.',
    storyImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600',
    storyTitle: 'خدماتنا وموردينا',
    storyText: 'شبكة موردين موثوقة، مخازن organized، وتغليف ونقل يضمن وصول منتجاتك بأفضل حال.',
    aboutImage: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=600',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'f1', name: 'منتج مصنع 1', description: 'مواصفات قياسية - جودة عالية', price: 250, imageUrl: '', category: 'إنتاج' },
      { id: 'f2', name: 'منتج مصنع 2', description: 'خامات معتمدة - ضمان شامل', price: 380, imageUrl: '', category: 'إنتاج' },
      { id: 'f3', name: 'خامات صناعية', description: 'مكونات ومدخلات إنتاج', price: 150, imageUrl: '', category: 'خامات' },
      { id: 'f4', name: 'تغليف وطباعة', description: 'حلول تغليف وطباعة', price: 90, imageUrl: '', category: 'تغليف' },
      { id: 'f5', name: 'منتج مصنع 3', description: 'تصنيع حسب الطلب', price: 420, imageUrl: '', category: 'إنتاج' },
      { id: 'f6', name: 'مستلزمات إنتاج', description: 'قطع غيار وصيانة', price: 180, imageUrl: '', category: 'مستلزمات' },
    ],
    categories: ['الكل', 'إنتاج', 'خامات', 'تغليف', 'مستلزمات'],
    defaultShopName: 'مصنع النخبة',
    defaultShopDescription: 'تصنيع وتوريد بجودة عالية',
    bannerImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المصنع',
    showAllLabel: 'عرض الكل',
    footerDescription: 'نقدم منتجات مصنعية بجودة عالية وخطوط إنتاج حديثة',
  },
  tradeCompanies: {
    marqueeOffers: ['🚢 استيراد وتصدير!', '📦 شحن وتوريد سريع!', '🤝 موزعون معتمدون!'],
    aboutTitle: 'شركتنا وخدماتنا',
    aboutText: 'نقدم حلول تجارية متكاملة من الاستيراد والتصدير إلى التوزيع والشحن.',
    storyImage: 'https://images.unsplash.com/photo-1577415124269-fc1140a69e91?w=600',
    storyTitle: 'شبكتنا ولوجستياتنا',
    storyText: 'شبكة موردين وموزعين عالمية، مخازن organized، وحلول شحن براً وبحراً وجواً.',
    aboutImage: 'https://images.unsplash.com/photo-1553443861-e455c9c8e29c?w=600',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'tc1', name: 'منتج مستورد 1', description: 'جودة عالية - سعر منافس', price: 320, imageUrl: '', category: 'استيراد' },
      { id: 'tc2', name: 'منتج محلي 1', description: 'صناعة وطنية ممتازة', price: 180, imageUrl: '', category: 'محلي' },
      { id: 'tc3', name: 'منتج مستورد 2', description: 'وكيل معتمد - ضمان', price: 450, imageUrl: '', category: 'استيراد' },
      { id: 'tc4', name: 'منتج تصدير 1', description: 'تصدير عالمي - شهادات', price: 290, imageUrl: '', category: 'تصدير' },
      { id: 'tc5', name: 'منتج محلي 2', description: 'توزيع جملة', price: 130, imageUrl: '', category: 'محلي' },
      { id: 'tc6', name: 'منتج مستورد 3', description: 'نياشن وتوكيلات', price: 510, imageUrl: '', category: 'استيراد' },
    ],
    categories: ['الكل', 'استيراد', 'محلي', 'تصدير'],
    defaultShopName: 'شركة التجارة المتحدة',
    defaultShopDescription: 'استيراد تصدير وتوزيع',
    bannerImage: 'https://images.unsplash.com/photo-1577415124269-fc1140a69e91?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1553443861-e455c9c8e29c?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات الشركة',
    showAllLabel: 'عرض الكل',
    footerDescription: 'حلول تجارية متكاملة من الاستيراد والتصدير إلى التوزيع',
  },
  tourismTravel: {
    marqueeOffers: ['✈️ حجوزات طيران!', '🏨 أفضل الأسعار للفنادق!', '🏖️ برامج سياحية مميزة!'],
    aboutTitle: 'شركتنا وبرامجنا',
    aboutText: 'نقدم برامج سياحية متكاملة من حجوزات الطيران والفنادق إلى المرشدين والتنقل.',
    storyImage: 'https://images.unsplash.com/photo-1488646953012-6cbfc7e6e1b1?w=600',
    storyTitle: 'خدماتنا ورحلاتنا',
    storyText: 'برامج سياحية داخية وخارجية، تأمين سفر، تأجير سيارات ومرشد سياحي محترف.',
    aboutImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600',
    highlightedTitle: 'أبرز البرامج',
    ctaLabel: 'احجز الآن',
    products: [
      { id: 'tt1', name: 'رحلة شرم الشيخ', description: '5 أيام - فندق 5 نجوم', price: 3500, imageUrl: '', category: 'رحلات داخلية' },
      { id: 'tt2', name: 'رحلة اسطنبول', description: '7 أيام - طيران + فندق', price: 6500, imageUrl: '', category: 'رحلات خارجية' },
      { id: 'tt3', name: 'عمرة 7 أيام', description: 'تأشيرة + فندق + نقل', price: 4200, imageUrl: '', category: 'عمرة وحج' },
      { id: 'tt4', name: 'حجز فندق 5 نجوم', description: 'ليلة واحدة - إفطار', price: 850, imageUrl: '', category: 'حجوزات فنادق' },
      { id: 'tt5', name: 'تذكرة طيران', description: 'ذهاب وعودة - اقتصادي', price: 1800, imageUrl: '', category: 'تذاكر طيران' },
      { id: 'tt6', name: 'برنامج شهر عسل', description: '10 أيام - مصيف', price: 8900, imageUrl: '', category: 'رحلات خارجية' },
    ],
    categories: ['الكل', 'رحلات داخلية', 'رحلات خارجية', 'عمرة وحج', 'حجوزات فنادق', 'تذاكر طيران'],
    defaultShopName: 'وكالة السفر الذهبية',
    defaultShopDescription: 'سياحة وسفر وبرامج سياحية',
    bannerImage: 'https://images.unsplash.com/photo-1488646953012-6cbfc7e6e1b1?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400',
    productsTabLabel: 'البرامج',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات الوكالة',
    showAllLabel: 'عرض الكل',
    footerDescription: 'برامج سياحية متكاملة وحجوزات طيران وفنادق',
  },
  livestock: {
    marqueeOffers: ['🐄 أعلاف ومكملات!', '💊 أدوية بيطرية أصلية!', '🚚 نقل حيواني آمن!'],
    aboutTitle: 'مزرعتنا وخدماتنا',
    aboutText: 'نقدم أعلاف عالية الجودة، أدوية بيطرية، معدات مزارع وخدمات نقل ومذابح.',
    storyImage: 'https://images.unsplash.com/photo-1500595046743-cd271d694d60?w=600',
    storyTitle: 'منتجاتنا وخدماتنا',
    storyText: 'أعلاف متكاملة، مكملات غذائية، أدوية بيطرية معتمدة ومعدات مزارع حديثة.',
    aboutImage: 'https://images.unsplash.com/photo-1605281317014-4c54f247aff7?w=600',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'ls1', name: 'أعلاف دواجن', description: '50 كجم - علف متكامل', price: 320, imageUrl: '', category: 'أعلاف' },
      { id: 'ls2', name: 'أعلاف أبقار', description: '50 كجم - علف حلوب', price: 380, imageUrl: '', category: 'أعلاف' },
      { id: 'ls3', name: 'مكمل غذائي', description: 'فيتامينات ومعادن', price: 150, imageUrl: '', category: 'مكملات' },
      { id: 'ls4', name: 'دواء بيطري', description: 'مضاد حيوي - معتمد', price: 85, imageUrl: '', category: 'أدوية بيطرية' },
      { id: 'ls5', name: 'معدات مزرعة', description: 'حظائر ومساقي', price: 1200, imageUrl: '', category: 'معدات' },
      { id: 'ls6', name: 'أعلاف أغنام', description: '50 كجم - علف تسمين', price: 340, imageUrl: '', category: 'أعلاف' },
    ],
    categories: ['الكل', 'أعلاف', 'مكملات', 'أدوية بيطرية', 'معدات'],
    defaultShopName: 'مزرعة الأمل',
    defaultShopDescription: 'ثروة حيوانية وأعلاف وبيطري',
    bannerImage: 'https://images.unsplash.com/photo-1605281317014-4c54f247aff7?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1500595046743-cd271d694d60?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المزرعة',
    showAllLabel: 'عرض الكل',
    footerDescription: 'أعلاف وأدوية بيطرية ومعدات مزارع بجودة عالية',
  },
  fisheries: {
    marqueeOffers: ['🐟 استزراع سمكي!', '🧊 تبريد ونقل آمن!', '🚢 تصدير أسماك طازجة!'],
    aboutTitle: 'مزرعتنا السمكية',
    aboutText: 'نقدم زريعة عالية الجودة، أعلاف أسماك، معدات تبريد وخدمات تصدير.',
    storyImage: 'https://images.unsplash.com/photo-1535591273668-565e641273f7?w=600',
    storyTitle: 'منتجاتنا وخدماتنا',
    storyText: 'استزراع سمكي احترافي، زريعة معتمدة، أعلاف متكاملة وحلول تبريد ونقل.',
    aboutImage: 'https://images.unsplash.com/photo-1493106819501-66d381c1ea19?w=600',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'fs1', name: 'زريعة بلطي', description: '1000 وحدة - معتمدة', price: 450, imageUrl: '', category: 'زريعة' },
      { id: 'fs2', name: 'أعلاف أسماك', description: '25 كجم - بروتين عالي', price: 280, imageUrl: '', category: 'أعلاف' },
      { id: 'fs3', name: 'معدات استزراع', description: 'أقفاص وأنابيب', price: 1500, imageUrl: '', category: 'معدات' },
      { id: 'fs4', name: 'وحدة تبريد', description: 'ثلاجة أسماك - 500 لتر', price: 3200, imageUrl: '', category: 'تبريد' },
      { id: 'fs5', name: 'سمك طازج', description: 'بلطي طازج - كجم', price: 65, imageUrl: '', category: 'أسماك' },
      { id: 'fs6', name: 'روبيان طازج', description: 'روبيان - كجم', price: 180, imageUrl: '', category: 'أسماك' },
    ],
    categories: ['الكل', 'زريعة', 'أعلاف', 'معدات', 'تبريد', 'أسماك'],
    defaultShopName: 'مزرعة البحر المتوسط',
    defaultShopDescription: 'استزراع سمكي وتصدير',
    bannerImage: 'https://images.unsplash.com/photo-1493106819501-66d381c1ea19?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1535591273668-565e641273f7?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المزرعة',
    showAllLabel: 'عرض الكل',
    footerDescription: 'استزراع سمكي وزريعة وأعلاف وتصدير أسماك',
  },
  energy: {
    marqueeOffers: ['☀️ طاقة شمسية نظيفة!', '🔋 بطاريات وإنفرتر!', '⚡ تركيب وصيانة!'],
    aboutTitle: 'شركتنا وحلول الطاقة',
    aboutText: 'نقدم حلول طاقة متكاملة من ألواح شمسية إلى بطاريات ومولدات وتركيب وصيانة.',
    storyImage: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600',
    storyTitle: 'خدماتنا وتركيبنا',
    storyText: 'تركيب أنظمة شمسية، صيانة دورية، مولدات كهرباء وحلول تخزين طاقة احترافية.',
    aboutImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600',
    highlightedTitle: 'أبرز المنتجات',
    ctaLabel: 'اطلب الآن',
    products: [
      { id: 'en1', name: 'لوح شمسي 550W', description: 'مونو - كفاءة عالية', price: 1200, imageUrl: '', category: 'ألواح شمسية' },
      { id: 'en2', name: 'إنفرتر 5KW', description: 'هجين - ضمان 5 سنوات', price: 4500, imageUrl: '', category: 'إنفرتر' },
      { id: 'en3', name: 'بطارية ليثيوم 200Ah', description: 'تخزين طاقة - عميق', price: 3800, imageUrl: '', category: 'بطاريات' },
      { id: 'en4', name: 'مولد كهرباء 10KVA', description: 'ديزل - صامت', price: 25000, imageUrl: '', category: 'مولدات' },
      { id: 'en5', name: 'كابلات ومفاتيح', description: 'ملحقات تركيب', price: 250, imageUrl: '', category: 'ملحقات' },
      { id: 'en6', name: 'خدمة تركيب شمسي', description: 'تركيب وتشغيل كامل', price: 3000, imageUrl: '', category: 'خدمات' },
    ],
    categories: ['الكل', 'ألواح شمسية', 'إنفرتر', 'بطاريات', 'مولدات', 'ملحقات', 'خدمات'],
    defaultShopName: 'شركة الطاقة الخضراء',
    defaultShopDescription: 'طاقة شمسية وكهرباء وصيانة',
    bannerImage: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400',
    productsTabLabel: 'المنتجات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات الشركة',
    showAllLabel: 'عرض الكل',
    footerDescription: 'حلول طاقة متكاملة من ألواح شمسية إلى مولدات وتركيب وصيانة',
  },
  professionalServices: {
    marqueeOffers: ['💼 استشارات مهنية!', '📅 مواعيد مرنة!', '✅ خبرة معتمدة!'],
    aboutTitle: 'مكتبنا وخدماتنا',
    aboutText: 'نقدم خدمات مهنية متخصصة في المحاسبة، المحاماة، الترجمة، التصميم والبرمجة.',
    storyImage: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=600',
    storyTitle: 'خبراتنا وأعمالنا',
    storyText: 'فريق من الخبراء في مختلف المجالات المهنية مع سجل أعمال موثوق وشهادات معتمدة.',
    aboutImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600',
    highlightedTitle: 'أبرز الخدمات',
    ctaLabel: 'احجز استشارة',
    products: [
      { id: 'ps1', name: 'استشارة محاسبية', description: 'جلسة 60 دقيقة', price: 350, imageUrl: '', category: 'محاسبة' },
      { id: 'ps2', name: 'استشارة قانونية', description: 'مراجعة عقد - جلسة', price: 500, imageUrl: '', category: 'محاماة' },
      { id: 'ps3', name: 'ترجمة مستندات', description: 'ترجمة قانونية معتمدة', price: 120, imageUrl: '', category: 'ترجمة' },
      { id: 'ps4', name: 'تصميم هوية', description: 'لوغو + هوية بصرية', price: 800, imageUrl: '', category: 'تصميم' },
      { id: 'ps5', name: 'تطوير موقع', description: 'موقع ويب متكامل', price: 3500, imageUrl: '', category: 'برمجة' },
      { id: 'ps6', name: 'استشارة إدارية', description: 'جلسة تخطيط استراتيجي', price: 600, imageUrl: '', category: 'استشارات' },
    ],
    categories: ['الكل', 'محاسبة', 'محاماة', 'ترجمة', 'تصميم', 'برمجة', 'استشارات'],
    defaultShopName: 'مكتب الخبراء',
    defaultShopDescription: 'خدمات مهنية واستشارات',
    bannerImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=400',
    productsTabLabel: 'الخدمات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات المكتب',
    showAllLabel: 'عرض الكل',
    footerDescription: 'خدمات مهنية متخصصة واستشارات معتمدة',
  },
  homeServices: {
    marqueeOffers: ['🔧 سباك وكهربائي!', '🏠 زيارات منزلية سريعة!', '✅ ضمان على الخدمة!'],
    aboutTitle: 'خدماتنا وفريقنا',
    aboutText: 'نقدم خدمات منزلية شاملة من سباكة وكهرباء ونجارة إلى تكييف وتنظيف.',
    storyImage: 'https://images.unsplash.com/photo-1581094288338-2314dddb7dde?w=600',
    storyTitle: 'مناطق خدمتنا وأسعارنا',
    storyText: 'فنيون محترفون، مناطق خدمة واسعة، رسوم زيارة واضحة وضمان على كل خدمة.',
    aboutImage: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600',
    highlightedTitle: 'أبرز الخدمات',
    ctaLabel: 'احجز زيارة',
    products: [
      { id: 'hs1', name: 'كشف تسربات', description: 'كشف وإصلاح تسرب', price: 200, imageUrl: '', category: 'سباكة' },
      { id: 'hs2', name: 'صيانة تكييف', description: 'تنظيف وشحن فريون', price: 250, imageUrl: '', category: 'تكييف' },
      { id: 'hs3', name: 'تركيب كهرباء', description: 'تأسيس وصيانة كهرباء', price: 180, imageUrl: '', category: 'كهرباء' },
      { id: 'hs4', name: 'دهانات ونجارة', description: 'دهان وتركيب خشب', price: 350, imageUrl: '', category: 'دهانات' },
      { id: 'hs5', name: 'تنظيف منزل', description: 'تنظيف شامل - 3 ساعات', price: 150, imageUrl: '', category: 'تنظيف' },
      { id: 'hs6', name: 'صيانة أجهزة', description: 'غسالات وثلاجات', price: 220, imageUrl: '', category: 'صيانة أجهزة' },
    ],
    categories: ['الكل', 'سباكة', 'كهرباء', 'تكييف', 'دهانات', 'تنظيف', 'صيانة أجهزة'],
    defaultShopName: 'خدمات المنزل',
    defaultShopDescription: 'صيانة وخدمات منزلية',
    bannerImage: 'https://images.unsplash.com/photo-1581094288338-2314dddb7dde?w=1200',
    productPlaceholderImage: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400',
    productsTabLabel: 'الخدمات',
    galleryTabLabel: 'المعرض',
    infoTabLabel: 'معلومات الخدمة',
    showAllLabel: 'عرض الكل',
    footerDescription: 'خدمات منزلية شاملة وصيانة بفريق محترف',
  },
};

export const getActivityPreviewData = (activityId?: unknown): ActivityPreviewData => {
  const id = String(activityId || '').trim();
  const activity = getBusinessActivityById(id);
  const data = PREVIEW_DATA[id] || PREVIEW_DATA.other;

  if (activity) {
    return {
      ...data,
      defaultShopName: data.defaultShopName || activity.title,
      defaultShopDescription: data.defaultShopDescription || activity.description,
    };
  }

  return data;
};

export const getActivityThemeColors = (activityId?: unknown) => {
  const patch = getBusinessActivityThemePatch(activityId);
  return {
    primaryColor: patch.primaryColor,
    secondaryColor: patch.secondaryColor,
    headerBackgroundColor: patch.headerBackgroundColor,
    headerTextColor: patch.headerTextColor,
    footerBackgroundColor: patch.footerBackgroundColor,
    footerTextColor: patch.footerTextColor,
    pageBackgroundColor: patch.pageBackgroundColor,
  };
};
