// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type CreateCategoryParams struct {
	StoreID     string  `json:"store_id"`
	ParentID    *string `json:"parent_id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	ImageURL    *string `json:"image_url"`
	SortOrder   int32   `json:"sort_order"`
	IsActive    bool    `json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO categories (store_id, parent_id, name, slug, description, image_url, sort_order, is_active)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id, store_id, parent_id, name, slug, description, image_url, sort_order, is_active, created_at, updated_at`,
		arg.StoreID, arg.ParentID, arg.Name, arg.Slug, arg.Description, arg.ImageURL, arg.SortOrder, arg.IsActive,
	)
	var c Category
	err := row.Scan(
		&c.ID, &c.StoreID, &c.ParentID, &c.Name, &c.Slug, &c.Description, &c.ImageURL, &c.SortOrder, &c.IsActive, &c.CreatedAt, &c.UpdatedAt,
	)
	return c, err
}

type GetCategoryByIDParams struct {
	ID      string `json:"id"`
	StoreID string `json:"store_id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, parent_id, name, slug, description, image_url, sort_order, is_active, created_at, updated_at
		FROM categories WHERE id = $1 AND store_id = $2 LIMIT 1`,
		arg.ID, arg.StoreID,
	)
	var c Category
	err := row.Scan(
		&c.ID, &c.StoreID, &c.ParentID, &c.Name, &c.Slug, &c.Description, &c.ImageURL, &c.SortOrder, &c.IsActive, &c.CreatedAt, &c.UpdatedAt,
	)
	return c, err
}

type ListCategoriesByStoreParams struct {
	StoreID  string `json:"store_id"`
	IsActive bool   `json:"is_active"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListCategoriesByStore(ctx context.Context, arg ListCategoriesByStoreParams) ([]Category, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, store_id, parent_id, name, slug, description, image_url, sort_order, is_active, created_at, updated_at
		FROM categories WHERE store_id = $1 AND is_active = $2
		ORDER BY sort_order ASC, name ASC LIMIT $3 OFFSET $4`,
		arg.StoreID, arg.IsActive, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var c Category
		if err := rows.Scan(
			&c.ID, &c.StoreID, &c.ParentID, &c.Name, &c.Slug, &c.Description, &c.ImageURL, &c.SortOrder, &c.IsActive, &c.CreatedAt, &c.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, c)
	}
	return items, rows.Err()
}

type ListCategoriesByParentParams struct {
	StoreID  string  `json:"store_id"`
	ParentID *string `json:"parent_id"`
}

func (q *Queries) ListCategoriesByParent(ctx context.Context, arg ListCategoriesByParentParams) ([]Category, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, store_id, parent_id, name, slug, description, image_url, sort_order, is_active, created_at, updated_at
		FROM categories WHERE store_id = $1 AND parent_id IS NOT DISTINCT FROM $2 AND is_active = true
		ORDER BY sort_order ASC, name ASC`,
		arg.StoreID, arg.ParentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var c Category
		if err := rows.Scan(
			&c.ID, &c.StoreID, &c.ParentID, &c.Name, &c.Slug, &c.Description, &c.ImageURL, &c.SortOrder, &c.IsActive, &c.CreatedAt, &c.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, c)
	}
	return items, rows.Err()
}

type UpdateCategoryParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	ImageURL    *string `json:"image_url"`
	SortOrder   int32   `json:"sort_order"`
	IsActive    bool    `json:"is_active"`
	StoreID     string  `json:"store_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE categories SET name = $2, slug = $3, description = $4, image_url = $5, sort_order = $6, is_active = $7, updated_at = NOW()
		WHERE id = $1 AND store_id = $8
		RETURNING id, store_id, parent_id, name, slug, description, image_url, sort_order, is_active, created_at, updated_at`,
		arg.ID, arg.Name, arg.Slug, arg.Description, arg.ImageURL, arg.SortOrder, arg.IsActive, arg.StoreID,
	)
	var c Category
	err := row.Scan(
		&c.ID, &c.StoreID, &c.ParentID, &c.Name, &c.Slug, &c.Description, &c.ImageURL, &c.SortOrder, &c.IsActive, &c.CreatedAt, &c.UpdatedAt,
	)
	return c, err
}

type DeleteCategoryParams struct {
	ID      string `json:"id"`
	StoreID string `json:"store_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, `DELETE FROM categories WHERE id = $1 AND store_id = $2`, arg.ID, arg.StoreID)
	return err
}

// Product-Category linking

func (q *Queries) AddProductToCategory(ctx context.Context, productID, categoryID string) error {
	_, err := q.db.Exec(ctx, `INSERT INTO product_categories (product_id, category_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`, productID, categoryID)
	return err
}

func (q *Queries) RemoveProductFromCategory(ctx context.Context, productID, categoryID string) error {
	_, err := q.db.Exec(ctx, `DELETE FROM product_categories WHERE product_id = $1 AND category_id = $2`, productID, categoryID)
	return err
}

func (q *Queries) GetProductCategories(ctx context.Context, productID, storeID string) ([]Category, error) {
	rows, err := q.db.Query(ctx,
		`SELECT c.id, c.store_id, c.parent_id, c.name, c.slug, c.description, c.image_url, c.sort_order, c.is_active, c.created_at, c.updated_at
		FROM categories c
		JOIN product_categories pc ON pc.category_id = c.id
		WHERE pc.product_id = $1 AND c.store_id = $2`,
		productID, storeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var c Category
		if err := rows.Scan(
			&c.ID, &c.StoreID, &c.ParentID, &c.Name, &c.Slug, &c.Description, &c.ImageURL, &c.SortOrder, &c.IsActive, &c.CreatedAt, &c.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, c)
	}
	return items, rows.Err()
}
