// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type CreateMediaParams struct {
	StoreID      string  `json:"store_id"`
	UploadedBy   *string `json:"uploaded_by"`
	Purpose      string  `json:"purpose"`
	OriginalKey  string  `json:"original_key"`
	OriginalURL  string  `json:"original_url"`
	MimeType     string  `json:"mime_type"`
	FileSize     *int64  `json:"file_size"`
	Width        *int32  `json:"width"`
	Height       *int32  `json:"height"`
	LinkedType   *string `json:"linked_type"`
	LinkedID     *string `json:"linked_id"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Media, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO media (
			store_id, uploaded_by, purpose, original_key, original_url, mime_type,
			file_size, width, height, linked_type, linked_id
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
		RETURNING id, store_id, uploaded_by, purpose, original_key, original_url, mime_type,
			file_size, width, height, thumb_key, thumb_url, small_key, small_url,
			medium_key, medium_url, optimized_key, optimized_url, optimization_status,
			optimization_error, linked_type, linked_id, is_active, created_at, updated_at`,
		arg.StoreID, arg.UploadedBy, arg.Purpose, arg.OriginalKey, arg.OriginalURL, arg.MimeType,
		arg.FileSize, arg.Width, arg.Height, arg.LinkedType, arg.LinkedID,
	)
	var m Media
	err := row.Scan(
		&m.ID, &m.StoreID, &m.UploadedBy, &m.Purpose, &m.OriginalKey, &m.OriginalURL, &m.MimeType,
		&m.FileSize, &m.Width, &m.Height, &m.ThumbKey, &m.ThumbURL, &m.SmallKey, &m.SmallURL,
		&m.MediumKey, &m.MediumURL, &m.OptimizedKey, &m.OptimizedURL, &m.OptimizationStatus,
		&m.OptimizationError, &m.LinkedType, &m.LinkedID, &m.IsActive, &m.CreatedAt, &m.UpdatedAt,
	)
	return m, err
}

type GetMediaByIDParams struct {
	ID      string `json:"id"`
	StoreID string `json:"store_id"`
}

func (q *Queries) GetMediaByID(ctx context.Context, arg GetMediaByIDParams) (Media, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, uploaded_by, purpose, original_key, original_url, mime_type,
			file_size, width, height, thumb_key, thumb_url, small_key, small_url,
			medium_key, medium_url, optimized_key, optimized_url, optimization_status,
			optimization_error, linked_type, linked_id, is_active, created_at, updated_at
		FROM media WHERE id = $1 AND store_id = $2 LIMIT 1`,
		arg.ID, arg.StoreID,
	)
	var m Media
	err := row.Scan(
		&m.ID, &m.StoreID, &m.UploadedBy, &m.Purpose, &m.OriginalKey, &m.OriginalURL, &m.MimeType,
		&m.FileSize, &m.Width, &m.Height, &m.ThumbKey, &m.ThumbURL, &m.SmallKey, &m.SmallURL,
		&m.MediumKey, &m.MediumURL, &m.OptimizedKey, &m.OptimizedURL, &m.OptimizationStatus,
		&m.OptimizationError, &m.LinkedType, &m.LinkedID, &m.IsActive, &m.CreatedAt, &m.UpdatedAt,
	)
	return m, err
}

func (q *Queries) GetMediaByKey(ctx context.Context, key string) (Media, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, uploaded_by, purpose, original_key, original_url, mime_type,
			file_size, width, height, thumb_key, thumb_url, small_key, small_url,
			medium_key, medium_url, optimized_key, optimized_url, optimization_status,
			optimization_error, linked_type, linked_id, is_active, created_at, updated_at
		FROM media WHERE original_key = $1 LIMIT 1`,
		key,
	)
	var m Media
	err := row.Scan(
		&m.ID, &m.StoreID, &m.UploadedBy, &m.Purpose, &m.OriginalKey, &m.OriginalURL, &m.MimeType,
		&m.FileSize, &m.Width, &m.Height, &m.ThumbKey, &m.ThumbURL, &m.SmallKey, &m.SmallURL,
		&m.MediumKey, &m.MediumURL, &m.OptimizedKey, &m.OptimizedURL, &m.OptimizationStatus,
		&m.OptimizationError, &m.LinkedType, &m.LinkedID, &m.IsActive, &m.CreatedAt, &m.UpdatedAt,
	)
	return m, err
}

type ListMediaByStoreParams struct {
	StoreID string `json:"store_id"`
	Purpose string `json:"purpose"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListMediaByStore(ctx context.Context, arg ListMediaByStoreParams) ([]Media, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, store_id, uploaded_by, purpose, original_key, original_url, mime_type,
			file_size, width, height, thumb_key, thumb_url, small_key, small_url,
			medium_key, medium_url, optimized_key, optimized_url, optimization_status,
			optimization_error, linked_type, linked_id, is_active, created_at, updated_at
		FROM media WHERE store_id = $1 AND is_active = true AND ($2::text = '' OR purpose = $2)
		ORDER BY created_at DESC LIMIT $3 OFFSET $4`,
		arg.StoreID, arg.Purpose, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Media
	for rows.Next() {
		var m Media
		if err := rows.Scan(
			&m.ID, &m.StoreID, &m.UploadedBy, &m.Purpose, &m.OriginalKey, &m.OriginalURL, &m.MimeType,
			&m.FileSize, &m.Width, &m.Height, &m.ThumbKey, &m.ThumbURL, &m.SmallKey, &m.SmallURL,
			&m.MediumKey, &m.MediumURL, &m.OptimizedKey, &m.OptimizedURL, &m.OptimizationStatus,
			&m.OptimizationError, &m.LinkedType, &m.LinkedID, &m.IsActive, &m.CreatedAt, &m.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, m)
	}
	return items, rows.Err()
}

type UpdateMediaOptimizationParams struct {
	ID                 string  `json:"id"`
	OptimizationStatus string  `json:"optimization_status"`
	ThumbKey           *string `json:"thumb_key"`
	ThumbURL           *string `json:"thumb_url"`
	SmallKey           *string `json:"small_key"`
	SmallURL           *string `json:"small_url"`
	MediumKey          *string `json:"medium_key"`
	MediumURL          *string `json:"medium_url"`
	OptimizedKey       *string `json:"optimized_key"`
	OptimizedURL       *string `json:"optimized_url"`
	OptimizationError  *string `json:"optimization_error"`
}

func (q *Queries) UpdateMediaOptimization(ctx context.Context, arg UpdateMediaOptimizationParams) (Media, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE media SET
			optimization_status = $2,
			thumb_key = $3, thumb_url = $4,
			small_key = $5, small_url = $6,
			medium_key = $7, medium_url = $8,
			optimized_key = $9, optimized_url = $10,
			optimization_error = $11,
			updated_at = NOW()
		WHERE id = $1
		RETURNING id, store_id, uploaded_by, purpose, original_key, original_url, mime_type,
			file_size, width, height, thumb_key, thumb_url, small_key, small_url,
			medium_key, medium_url, optimized_key, optimized_url, optimization_status,
			optimization_error, linked_type, linked_id, is_active, created_at, updated_at`,
		arg.ID, arg.OptimizationStatus, arg.ThumbKey, arg.ThumbURL, arg.SmallKey, arg.SmallURL,
		arg.MediumKey, arg.MediumURL, arg.OptimizedKey, arg.OptimizedURL, arg.OptimizationError,
	)
	var m Media
	err := row.Scan(
		&m.ID, &m.StoreID, &m.UploadedBy, &m.Purpose, &m.OriginalKey, &m.OriginalURL, &m.MimeType,
		&m.FileSize, &m.Width, &m.Height, &m.ThumbKey, &m.ThumbURL, &m.SmallKey, &m.SmallURL,
		&m.MediumKey, &m.MediumURL, &m.OptimizedKey, &m.OptimizedURL, &m.OptimizationStatus,
		&m.OptimizationError, &m.LinkedType, &m.LinkedID, &m.IsActive, &m.CreatedAt, &m.UpdatedAt,
	)
	return m, err
}

type DeleteMediaParams struct {
	ID      string `json:"id"`
	StoreID string `json:"store_id"`
}

func (q *Queries) DeleteMedia(ctx context.Context, arg DeleteMediaParams) error {
	_, err := q.db.Exec(ctx, `UPDATE media SET is_active = false, updated_at = NOW() WHERE id = $1 AND store_id = $2`, arg.ID, arg.StoreID)
	return err
}
