// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"encoding/json"
	"time"
)

type StoreStatus string

const (
	StoreStatusPending   StoreStatus = "pending"
	StoreStatusActive    StoreStatus = "active"
	StoreStatusSuspended StoreStatus = "suspended"
	StoreStatusInactive  StoreStatus = "inactive"
)

type Store struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Domain    *string         `json:"domain"`
	Subdomain *string         `json:"subdomain"`
	LogoURL   *string         `json:"logo_url"`
	Status    StoreStatus     `json:"status"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type User struct {
	ID           string    `json:"id"`
	StoreID      string    `json:"store_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Product struct {
	ID          string          `json:"id"`
	StoreID     string          `json:"store_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Price       float64         `json:"price"`
	Stock       int32           `json:"stock"`
	ImageURL    *string         `json:"image_url"`
	IsActive    bool            `json:"is_active"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Category struct {
	ID          string    `json:"id"`
	StoreID     string    `json:"store_id"`
	ParentID    *string   `json:"parent_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	ImageURL    *string   `json:"image_url"`
	SortOrder   int32     `json:"sort_order"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusConfirmed  OrderStatus = "confirmed"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusShipped    OrderStatus = "shipped"
	OrderStatusDelivered  OrderStatus = "delivered"
	OrderStatusCancelled  OrderStatus = "cancelled"
	OrderStatusRefunded   OrderStatus = "refunded"
)

type Order struct {
	ID              string          `json:"id"`
	StoreID         string          `json:"store_id"`
	UserID          *string         `json:"user_id"`
	OrderNumber     string          `json:"order_number"`
	Status          OrderStatus     `json:"status"`
	Subtotal        float64         `json:"subtotal"`
	Tax             float64         `json:"tax"`
	Shipping        float64         `json:"shipping"`
	Discount        float64         `json:"discount"`
	Total           float64         `json:"total"`
	Currency        string          `json:"currency"`
	CustomerName    *string         `json:"customer_name"`
	CustomerEmail   *string         `json:"customer_email"`
	CustomerPhone   *string         `json:"customer_phone"`
	ShippingAddress json.RawMessage `json:"shipping_address"`
	BillingAddress  json.RawMessage `json:"billing_address"`
	Notes           *string         `json:"notes"`
	Metadata        json.RawMessage `json:"metadata"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type OrderItem struct {
	ID          string          `json:"id"`
	OrderID     string          `json:"order_id"`
	ProductID   *string         `json:"product_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Price       float64         `json:"price"`
	Quantity    int32           `json:"quantity"`
	Subtotal    float64         `json:"subtotal"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Media struct {
	ID                 string    `json:"id"`
	StoreID            string    `json:"store_id"`
	UploadedBy         *string   `json:"uploaded_by"`
	Purpose            string    `json:"purpose"`
	OriginalKey        string    `json:"original_key"`
	OriginalURL        string    `json:"original_url"`
	MimeType           string    `json:"mime_type"`
	FileSize           *int64    `json:"file_size"`
	Width              *int32    `json:"width"`
	Height             *int32    `json:"height"`
	ThumbKey           *string   `json:"thumb_key"`
	ThumbURL           *string   `json:"thumb_url"`
	SmallKey           *string   `json:"small_key"`
	SmallURL           *string   `json:"small_url"`
	MediumKey          *string   `json:"medium_key"`
	MediumURL          *string   `json:"medium_url"`
	OptimizedKey       *string   `json:"optimized_key"`
	OptimizedURL       *string   `json:"optimized_url"`
	OptimizationStatus string    `json:"optimization_status"`
	OptimizationError  *string   `json:"optimization_error"`
	LinkedType         *string   `json:"linked_type"`
	LinkedID           *string   `json:"linked_id"`
	IsActive           bool      `json:"is_active"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}
