// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"
)

type CreateOrderParams struct {
	StoreID         string          `json:"store_id"`
	UserID          *string         `json:"user_id"`
	OrderNumber     string          `json:"order_number"`
	Status          OrderStatus     `json:"status"`
	Subtotal        float64         `json:"subtotal"`
	Tax             float64         `json:"tax"`
	Shipping        float64         `json:"shipping"`
	Discount        float64         `json:"discount"`
	Total           float64         `json:"total"`
	Currency        string          `json:"currency"`
	CustomerName    *string         `json:"customer_name"`
	CustomerEmail   *string         `json:"customer_email"`
	CustomerPhone   *string         `json:"customer_phone"`
	ShippingAddress json.RawMessage `json:"shipping_address"`
	BillingAddress  json.RawMessage `json:"billing_address"`
	Notes           *string         `json:"notes"`
	Metadata        json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO orders (
			store_id, user_id, order_number, status,
			subtotal, tax, shipping, discount, total, currency,
			customer_name, customer_email, customer_phone,
			shipping_address, billing_address, notes, metadata
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
		RETURNING id, store_id, user_id, order_number, status, subtotal, tax, shipping, discount, total, currency,
			customer_name, customer_email, customer_phone, shipping_address, billing_address, notes, metadata, created_at, updated_at`,
		arg.StoreID, arg.UserID, arg.OrderNumber, arg.Status,
		arg.Subtotal, arg.Tax, arg.Shipping, arg.Discount, arg.Total, arg.Currency,
		arg.CustomerName, arg.CustomerEmail, arg.CustomerPhone,
		arg.ShippingAddress, arg.BillingAddress, arg.Notes, arg.Metadata,
	)
	var o Order
	err := row.Scan(
		&o.ID, &o.StoreID, &o.UserID, &o.OrderNumber, &o.Status, &o.Subtotal, &o.Tax, &o.Shipping, &o.Discount, &o.Total, &o.Currency,
		&o.CustomerName, &o.CustomerEmail, &o.CustomerPhone, &o.ShippingAddress, &o.BillingAddress, &o.Notes, &o.Metadata, &o.CreatedAt, &o.UpdatedAt,
	)
	return o, err
}

type GetOrderByIDParams struct {
	ID      string `json:"id"`
	StoreID string `json:"store_id"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, user_id, order_number, status, subtotal, tax, shipping, discount, total, currency,
			customer_name, customer_email, customer_phone, shipping_address, billing_address, notes, metadata, created_at, updated_at
		FROM orders WHERE id = $1 AND store_id = $2 LIMIT 1`,
		arg.ID, arg.StoreID,
	)
	var o Order
	err := row.Scan(
		&o.ID, &o.StoreID, &o.UserID, &o.OrderNumber, &o.Status, &o.Subtotal, &o.Tax, &o.Shipping, &o.Discount, &o.Total, &o.Currency,
		&o.CustomerName, &o.CustomerEmail, &o.CustomerPhone, &o.ShippingAddress, &o.BillingAddress, &o.Notes, &o.Metadata, &o.CreatedAt, &o.UpdatedAt,
	)
	return o, err
}

type GetOrderByNumberParams struct {
	OrderNumber string `json:"order_number"`
	StoreID     string `json:"store_id"`
}

func (q *Queries) GetOrderByNumber(ctx context.Context, arg GetOrderByNumberParams) (Order, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, user_id, order_number, status, subtotal, tax, shipping, discount, total, currency,
			customer_name, customer_email, customer_phone, shipping_address, billing_address, notes, metadata, created_at, updated_at
		FROM orders WHERE order_number = $1 AND store_id = $2 LIMIT 1`,
		arg.OrderNumber, arg.StoreID,
	)
	var o Order
	err := row.Scan(
		&o.ID, &o.StoreID, &o.UserID, &o.OrderNumber, &o.Status, &o.Subtotal, &o.Tax, &o.Shipping, &o.Discount, &o.Total, &o.Currency,
		&o.CustomerName, &o.CustomerEmail, &o.CustomerPhone, &o.ShippingAddress, &o.BillingAddress, &o.Notes, &o.Metadata, &o.CreatedAt, &o.UpdatedAt,
	)
	return o, err
}

type ListOrdersByStoreParams struct {
	StoreID string `json:"store_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListOrdersByStore(ctx context.Context, arg ListOrdersByStoreParams) ([]Order, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, store_id, user_id, order_number, status, subtotal, tax, shipping, discount, total, currency,
			customer_name, customer_email, customer_phone, shipping_address, billing_address, notes, metadata, created_at, updated_at
		FROM orders WHERE store_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3`,
		arg.StoreID, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var o Order
		if err := rows.Scan(
			&o.ID, &o.StoreID, &o.UserID, &o.OrderNumber, &o.Status, &o.Subtotal, &o.Tax, &o.Shipping, &o.Discount, &o.Total, &o.Currency,
			&o.CustomerName, &o.CustomerEmail, &o.CustomerPhone, &o.ShippingAddress, &o.BillingAddress, &o.Notes, &o.Metadata, &o.CreatedAt, &o.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, o)
	}
	return items, rows.Err()
}

type ListOrdersByStatusParams struct {
	StoreID string      `json:"store_id"`
	Status  OrderStatus `json:"status"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, store_id, user_id, order_number, status, subtotal, tax, shipping, discount, total, currency,
			customer_name, customer_email, customer_phone, shipping_address, billing_address, notes, metadata, created_at, updated_at
		FROM orders WHERE store_id = $1 AND status = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4`,
		arg.StoreID, arg.Status, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var o Order
		if err := rows.Scan(
			&o.ID, &o.StoreID, &o.UserID, &o.OrderNumber, &o.Status, &o.Subtotal, &o.Tax, &o.Shipping, &o.Discount, &o.Total, &o.Currency,
			&o.CustomerName, &o.CustomerEmail, &o.CustomerPhone, &o.ShippingAddress, &o.BillingAddress, &o.Notes, &o.Metadata, &o.CreatedAt, &o.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, o)
	}
	return items, rows.Err()
}

type UpdateOrderStatusParams struct {
	ID      string      `json:"id"`
	Status  OrderStatus `json:"status"`
	StoreID string      `json:"store_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE orders SET status = $2, updated_at = NOW() WHERE id = $1 AND store_id = $3
		RETURNING id, store_id, user_id, order_number, status, subtotal, tax, shipping, discount, total, currency,
			customer_name, customer_email, customer_phone, shipping_address, billing_address, notes, metadata, created_at, updated_at`,
		arg.ID, arg.Status, arg.StoreID,
	)
	var o Order
	err := row.Scan(
		&o.ID, &o.StoreID, &o.UserID, &o.OrderNumber, &o.Status, &o.Subtotal, &o.Tax, &o.Shipping, &o.Discount, &o.Total, &o.Currency,
		&o.CustomerName, &o.CustomerEmail, &o.CustomerPhone, &o.ShippingAddress, &o.BillingAddress, &o.Notes, &o.Metadata, &o.CreatedAt, &o.UpdatedAt,
	)
	return o, err
}

func (q *Queries) CountOrdersByStore(ctx context.Context, storeID string) (int64, error) {
	row := q.db.QueryRow(ctx, `SELECT COUNT(*) FROM orders WHERE store_id = $1`, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateOrderItemParams struct {
	OrderID     string          `json:"order_id"`
	ProductID   *string         `json:"product_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Price       float64         `json:"price"`
	Quantity    int32           `json:"quantity"`
	Subtotal    float64         `json:"subtotal"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO order_items (order_id, product_id, name, description, price, quantity, subtotal, metadata)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id, order_id, product_id, name, description, price, quantity, subtotal, metadata, created_at`,
		arg.OrderID, arg.ProductID, arg.Name, arg.Description, arg.Price, arg.Quantity, arg.Subtotal, arg.Metadata,
	)
	var oi OrderItem
	err := row.Scan(
		&oi.ID, &oi.OrderID, &oi.ProductID, &oi.Name, &oi.Description, &oi.Price, &oi.Quantity, &oi.Subtotal, &oi.Metadata, &oi.CreatedAt,
	)
	return oi, err
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, order_id, product_id, name, description, price, quantity, subtotal, metadata, created_at
		FROM order_items WHERE order_id = $1 ORDER BY created_at ASC`,
		orderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var oi OrderItem
		if err := rows.Scan(
			&oi.ID, &oi.OrderID, &oi.ProductID, &oi.Name, &oi.Description, &oi.Price, &oi.Quantity, &oi.Subtotal, &oi.Metadata, &oi.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, oi)
	}
	return items, rows.Err()
}
