// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"
)

type CreateProductParams struct {
	StoreID     string          `json:"store_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Price       float64         `json:"price"`
	Stock       int32           `json:"stock"`
	ImageURL    *string         `json:"image_url"`
	IsActive    bool            `json:"is_active"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO products (store_id, name, description, price, stock, image_url, is_active, metadata)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id, store_id, name, description, price, stock, image_url, is_active, metadata, created_at, updated_at`,
		arg.StoreID, arg.Name, arg.Description, arg.Price, arg.Stock, arg.ImageURL, arg.IsActive, arg.Metadata,
	)
	var p Product
	err := row.Scan(
		&p.ID, &p.StoreID, &p.Name, &p.Description, &p.Price, &p.Stock, &p.ImageURL, &p.IsActive, &p.Metadata, &p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

type GetProductByIDParams struct {
	ID      string `json:"id"`
	StoreID string `json:"store_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, name, description, price, stock, image_url, is_active, metadata, created_at, updated_at
		FROM products WHERE id = $1 AND store_id = $2 LIMIT 1`,
		arg.ID, arg.StoreID,
	)
	var p Product
	err := row.Scan(
		&p.ID, &p.StoreID, &p.Name, &p.Description, &p.Price, &p.Stock, &p.ImageURL, &p.IsActive, &p.Metadata, &p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

type ListProductsByStoreParams struct {
	StoreID  string `json:"store_id"`
	IsActive bool   `json:"is_active"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListProductsByStore(ctx context.Context, arg ListProductsByStoreParams) ([]Product, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, store_id, name, description, price, stock, image_url, is_active, metadata, created_at, updated_at
		FROM products WHERE store_id = $1 AND is_active = $2
		ORDER BY created_at DESC LIMIT $3 OFFSET $4`,
		arg.StoreID, arg.IsActive, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var p Product
		if err := rows.Scan(
			&p.ID, &p.StoreID, &p.Name, &p.Description, &p.Price, &p.Stock, &p.ImageURL, &p.IsActive, &p.Metadata, &p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

type UpdateProductParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Price       float64         `json:"price"`
	Stock       int32           `json:"stock"`
	ImageURL    *string         `json:"image_url"`
	IsActive    bool            `json:"is_active"`
	Metadata    json.RawMessage `json:"metadata"`
	StoreID     string          `json:"store_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE products SET name = $2, description = $3, price = $4, stock = $5, image_url = $6, is_active = $7, metadata = $8, updated_at = NOW()
		WHERE id = $1 AND store_id = $9
		RETURNING id, store_id, name, description, price, stock, image_url, is_active, metadata, created_at, updated_at`,
		arg.ID, arg.Name, arg.Description, arg.Price, arg.Stock, arg.ImageURL, arg.IsActive, arg.Metadata, arg.StoreID,
	)
	var p Product
	err := row.Scan(
		&p.ID, &p.StoreID, &p.Name, &p.Description, &p.Price, &p.Stock, &p.ImageURL, &p.IsActive, &p.Metadata, &p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

type DeleteProductParams struct {
	ID      string `json:"id"`
	StoreID string `json:"store_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, `DELETE FROM products WHERE id = $1 AND store_id = $2`, arg.ID, arg.StoreID)
	return err
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, email, password_hash, role, is_active, created_at, updated_at FROM users WHERE id = $1 LIMIT 1`,
		id,
	)
	var u User
	err := row.Scan(&u.ID, &u.StoreID, &u.Email, &u.PasswordHash, &u.Role, &u.IsActive, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}
