// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	GetStoreByID(ctx context.Context, id string) (Store, error)
	GetStoreBySlug(ctx context.Context, slug string) (Store, error)
	GetStoreByDomain(ctx context.Context, domain string) (Store, error)
	UpdateStoreStatus(ctx context.Context, arg UpdateStoreStatusParams) (Store, error)
	ListStores(ctx context.Context, arg ListStoresParams) ([]Store, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	ListProductsByStore(ctx context.Context, arg ListProductsByStoreParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	ListCategoriesByStore(ctx context.Context, arg ListCategoriesByStoreParams) ([]Category, error)
	ListCategoriesByParent(ctx context.Context, arg ListCategoriesByParentParams) ([]Category, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	AddProductToCategory(ctx context.Context, productID, categoryID string) error
	RemoveProductFromCategory(ctx context.Context, productID, categoryID string) error
	GetProductCategories(ctx context.Context, productID, storeID string) ([]Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error)
	GetOrderByNumber(ctx context.Context, arg GetOrderByNumberParams) (Order, error)
	ListOrdersByStore(ctx context.Context, arg ListOrdersByStoreParams) ([]Order, error)
	ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	CountOrdersByStore(ctx context.Context, storeID string) (int64, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	GetOrderItems(ctx context.Context, orderID string) ([]OrderItem, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Media, error)
	GetMediaByID(ctx context.Context, arg GetMediaByIDParams) (Media, error)
	GetMediaByKey(ctx context.Context, key string) (Media, error)
	ListMediaByStore(ctx context.Context, arg ListMediaByStoreParams) ([]Media, error)
	UpdateMediaOptimization(ctx context.Context, arg UpdateMediaOptimizationParams) (Media, error)
	DeleteMedia(ctx context.Context, arg DeleteMediaParams) error
}

var _ Querier = (*Queries)(nil)
