// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"
)

type CreateStoreParams struct {
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Domain    *string         `json:"domain"`
	Subdomain *string         `json:"subdomain"`
	LogoURL   *string         `json:"logo_url"`
	Status    StoreStatus     `json:"status"`
	Settings  json.RawMessage `json:"settings"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO stores (name, slug, domain, subdomain, logo_url, status, settings)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id, name, slug, domain, subdomain, logo_url, status, settings, created_at, updated_at`,
		arg.Name, arg.Slug, arg.Domain, arg.Subdomain, arg.LogoURL, arg.Status, arg.Settings,
	)
	var s Store
	err := row.Scan(
		&s.ID, &s.Name, &s.Slug, &s.Domain, &s.Subdomain, &s.LogoURL, &s.Status, &s.Settings, &s.CreatedAt, &s.UpdatedAt,
	)
	return s, err
}

func (q *Queries) GetStoreByID(ctx context.Context, id string) (Store, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, name, slug, domain, subdomain, logo_url, status, settings, created_at, updated_at FROM stores WHERE id = $1 LIMIT 1`,
		id,
	)
	var s Store
	err := row.Scan(
		&s.ID, &s.Name, &s.Slug, &s.Domain, &s.Subdomain, &s.LogoURL, &s.Status, &s.Settings, &s.CreatedAt, &s.UpdatedAt,
	)
	return s, err
}

func (q *Queries) GetStoreBySlug(ctx context.Context, slug string) (Store, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, name, slug, domain, subdomain, logo_url, status, settings, created_at, updated_at FROM stores WHERE slug = $1 LIMIT 1`,
		slug,
	)
	var s Store
	err := row.Scan(
		&s.ID, &s.Name, &s.Slug, &s.Domain, &s.Subdomain, &s.LogoURL, &s.Status, &s.Settings, &s.CreatedAt, &s.UpdatedAt,
	)
	return s, err
}

func (q *Queries) GetStoreByDomain(ctx context.Context, domain string) (Store, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, name, slug, domain, subdomain, logo_url, status, settings, created_at, updated_at FROM stores WHERE domain = $1 OR subdomain = $1 LIMIT 1`,
		domain,
	)
	var s Store
	err := row.Scan(
		&s.ID, &s.Name, &s.Slug, &s.Domain, &s.Subdomain, &s.LogoURL, &s.Status, &s.Settings, &s.CreatedAt, &s.UpdatedAt,
	)
	return s, err
}

type UpdateStoreStatusParams struct {
	ID     string      `json:"id"`
	Status StoreStatus `json:"status"`
}

func (q *Queries) UpdateStoreStatus(ctx context.Context, arg UpdateStoreStatusParams) (Store, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE stores SET status = $2, updated_at = NOW() WHERE id = $1
		RETURNING id, name, slug, domain, subdomain, logo_url, status, settings, created_at, updated_at`,
		arg.ID, arg.Status,
	)
	var s Store
	err := row.Scan(
		&s.ID, &s.Name, &s.Slug, &s.Domain, &s.Subdomain, &s.LogoURL, &s.Status, &s.Settings, &s.CreatedAt, &s.UpdatedAt,
	)
	return s, err
}

type ListStoresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStores(ctx context.Context, arg ListStoresParams) ([]Store, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, name, slug, domain, subdomain, logo_url, status, settings, created_at, updated_at FROM stores ORDER BY created_at DESC LIMIT $1 OFFSET $2`,
		arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var s Store
		if err := rows.Scan(
			&s.ID, &s.Name, &s.Slug, &s.Domain, &s.Subdomain, &s.LogoURL, &s.Status, &s.Settings, &s.CreatedAt, &s.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
