// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type CreateUserParams struct {
	StoreID      string `json:"store_id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO users (store_id, email, password_hash, role, is_active)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, store_id, email, password_hash, role, is_active, created_at, updated_at`,
		arg.StoreID, arg.Email, arg.PasswordHash, arg.Role, arg.IsActive,
	)
	var u User
	err := row.Scan(
		&u.ID, &u.StoreID, &u.Email, &u.PasswordHash, &u.Role, &u.IsActive, &u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

type GetUserByEmailParams struct {
	StoreID string `json:"store_id"`
	Email   string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, store_id, email, password_hash, role, is_active, created_at, updated_at FROM users WHERE store_id = $1 AND email = $2 LIMIT 1`,
		arg.StoreID, arg.Email,
	)
	var u User
	err := row.Scan(
		&u.ID, &u.StoreID, &u.Email, &u.PasswordHash, &u.Role, &u.IsActive, &u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}
