// Activity data for signup — inlined from @ray-eg/shared businessActivityCatalog
export type ActivityButtonDef = {
  id: string;
  label: string;
  description?: string;
};

export type BusinessActivityDef = {
  id: string;
  title: string;
  description: string;
  category: string;
  primaryModuleLabel: string;
  secondaryModuleLabel: string;
  privateButtons: ActivityButtonDef[];
  specialties: string[];
};

export type BusinessActivityGroupDef = {
  id: string;
  title: string;
  description: string;
  icon: string;
  category: string;
  activities: BusinessActivityDef[];
};

const makeButton = (id: string, label: string): ActivityButtonDef => ({ id, label });

export const BUSINESS_ACTIVITY_GROUPS: BusinessActivityGroupDef[] = [
  {
    id: 'food_market',
    title: 'مطاعم وأغذية ومحلات تموين',
    description: 'مطاعم، كافيهات، بقالة، سوبر ماركت، عطارة، مخابز وحلويات.',
    icon: 'م',
    category: 'RESTAURANT',
    activities: [
      {
        id: 'restaurant',
        title: 'مطعم / كافيه',
        description: 'منيو، طاولات، طلبات، دليفري، عروض ووجبات.',
        category: 'RESTAURANT',
        primaryModuleLabel: 'المنيو والأقسام',
        secondaryModuleLabel: 'الطاولات والقاعات',
        privateButtons: [
          makeButton('tables', 'الطاولات والقاعات'),
          makeButton('table_bookings', 'حجز الطاولات'),
        ],
        specialties: ['مطعم عائلي', 'كافيه', 'مطعم وجبات سريعة', 'مطعم مشويات', 'مطعم سمك', 'مطعم صحي/دايت', 'كشك Street Food', 'بوفيه مفتوح', 'مخبوزات وحلويات', 'مطعم حلال/كوشر'],
      },
      {
        id: 'grocery',
        title: 'سوبر ماركت / بقالة / عطارة',
        description: 'منتجات يومية، أقسام، مخزون سريع، عروض وتموين.',
        category: 'FOOD',
        primaryModuleLabel: 'الأقسام والبضائع',
        secondaryModuleLabel: 'الموردون والمخزون',
        privateButtons: [
          makeButton('fresh_sections', 'الأقسام الطازجة'),
          makeButton('suppliers', 'الموردون'),
          makeButton('expiry_batches', 'الصلاحيات والتشغيلات'),
          makeButton('bundle_offers', 'باقات التوفير'),
        ],
        specialties: ['سوبر ماركت', 'بقالة', 'عطارة وأعشاب', 'خضار وفاكهة', 'معلبات', 'ألبان وأسماك', 'مخبوزات', 'تموين المنازل', 'بقالة أونلاين', 'أغراض جملة'],
      },
    ],
  },
  {
    id: 'fashion_home',
    title: 'ملابس ومفروشات وأثاث وديكور',
    description: 'ملابس، أحذية، أقمشة، ستائر، كنب، مفروشات، سجاد، أثاث، ديكور ومستلزمات المنزل.',
    icon: 'ف',
    category: 'FASHION',
    activities: [
      {
        id: 'fashion',
        title: 'ملابس / أحذية / إكسسوارات',
        description: 'مقاسات، ألوان، موديلات، مواسم، عروض وتبديل.',
        category: 'FASHION',
        primaryModuleLabel: 'المقاسات والألوان',
        secondaryModuleLabel: 'الموديلات والمواسم',
        privateButtons: [
          makeButton('sizes_colors', 'المقاسات والألوان'),
          makeButton('collections', 'الكوليكشنات'),
          makeButton('try_exchange', 'التبديل والاسترجاع'),
          makeButton('tailoring', 'تفصيل وتعديلات'),
        ],
        specialties: ['ملابس رجالي', 'ملابس حريمي', 'ملابس أطفال', 'أحذية', 'إكسسوارات', 'شنط', 'ملابس رياضية', 'ملابس أفراح', 'ملابس أحجام كبيرة', 'أزياء محجبات'],
      },
      {
        id: 'homeTextiles',
        title: 'مفروشات وسجاد وستائر',
        description: 'مقاسات، خامات، تفصيل، تركيب، كتالوجات ومعرض صور.',
        category: 'RETAIL',
        primaryModuleLabel: 'المقاسات والخامات',
        secondaryModuleLabel: 'التفصيل والتركيب',
        privateButtons: [
          makeButton('measurements', 'المقاسات والقياسات'),
          makeButton('fabric_catalog', 'كتالوج الخامات'),
          makeButton('installation', 'خدمات التركيب'),
          makeButton('custom_orders', 'طلبات التفصيل'),
        ],
        specialties: ['سجاد', 'ستائر', 'مفروشات', 'لحاف ومدافئ', 'مناشف', 'أغطية كنب', 'سجاد صلاة', 'خيام', 'مفارش طعام', 'تلبيسات أرضيات'],
      },
      {
        id: 'fabricStore',
        title: 'أقمشة وخامات وتفصيل',
        description: 'أقمشة ملابس ومفروشات، خامات، باترونات، تفصيل وطلبات مترية.',
        category: 'FASHION',
        primaryModuleLabel: 'كتالوج الأقمشة',
        secondaryModuleLabel: 'التفصيل والطلبات المترية',
        privateButtons: [
          makeButton('fabric_types', 'أنواع الأقمشة والخامات'),
          makeButton('meter_pricing', 'سعر المتر والقصات'),
          makeButton('patterns_tailoring', 'باترونات وتفصيل'),
          makeButton('wholesale_rolls', 'رولات وجملة'),
        ],
        specialties: ['أقمشة ملابس', 'أقمشة مفروشات', 'خيام وستائر', 'تطريز', 'تفصيل ملابس', 'تفصيل أفراح', 'باترونات', 'خيامية', 'قماش بالمتر', 'رولات جملة'],
      },
      {
        id: 'curtainsBlinds',
        title: 'ستاير وبرقع وبلاك أوت',
        description: 'ستائر، بلاك أوت، شيفون، قضبان، قياسات، تفصيل وتركيب.',
        category: 'RETAIL',
        primaryModuleLabel: 'أنواع الستائر',
        secondaryModuleLabel: 'القياسات والتركيب',
        privateButtons: [
          makeButton('curtain_catalog', 'كتالوج الستائر'),
          makeButton('window_measurements', 'مقاسات الشبابيك'),
          makeButton('rails_accessories', 'قضبان وإكسسوارات'),
          makeButton('installation_visits', 'زيارات التركيب'),
        ],
        specialties: ['ستائر شيفون', 'بلاك أوت', 'ستائر رول', 'ستائر رأسية', 'برقع', 'قضبان وكرانيش', 'ستائر أبواب', 'ستائر مطبخ', 'خيام', 'تلبيس نوافذ'],
      },
      {
        id: 'sofasUpholstery',
        title: 'كنب وانتريهات وتنجيد',
        description: 'كنب، انتريهات، ركنات، تنجيد، تغيير أقمشة، صيانة وتصنيع حسب المقاس.',
        category: 'SERVICE',
        primaryModuleLabel: 'موديلات الكنب والركنات',
        secondaryModuleLabel: 'التنجيد والصيانة',
        privateButtons: [
          makeButton('sofa_models', 'موديلات الكنب والركنات'),
          makeButton('upholstery_fabrics', 'أقمشة التنجيد'),
          makeButton('custom_sizes', 'تصنيع بمقاسات خاصة'),
          makeButton('repair_renewal', 'إصلاح وتجديد'),
        ],
        specialties: ['كنب', 'انتريهات', 'ركنات', 'تنجيد', 'تغيير قماش', 'إصلاح كراسي', 'تصنيع حسب الطلب', 'وسائد', 'كنب مكتبي', 'صيانة أثاث'],
      },
      {
        id: 'mattressesBedding',
        title: 'مراتب وملايات ومستلزمات نوم',
        description: 'مراتب، مخدات، ملايات، لحاف، مفارش وحماية مراتب.',
        category: 'RETAIL',
        primaryModuleLabel: 'المراتب والمقاسات',
        secondaryModuleLabel: 'الملايات والمفارش',
        privateButtons: [
          makeButton('mattress_sizes', 'مقاسات المراتب'),
          makeButton('bedding_sets', 'أطقم ملايات ومفارش'),
          makeButton('pillows_duvets', 'مخدات ولحاف'),
          makeButton('comfort_levels', 'درجات الراحة والضمان'),
        ],
        specialties: ['مراتب طبية', 'مراتب اسفنج', 'مراتب طبيعية', 'ملايات قطن', 'لحاف', 'مخدات', 'واقي مرتبة', 'مفارش', 'أطقم سرير', 'بياضات فندقية'],
      },
      {
        id: 'furniture',
        title: 'أثاث / معارض / ديكور',
        description: 'معارض أثاث، غرف، ديكور، تصنيع، تسليم وتركيب.',
        category: 'SERVICE',
        primaryModuleLabel: 'المعارض والغرف',
        secondaryModuleLabel: 'التصنيع والتركيب',
        privateButtons: [
          makeButton('showroom_sets', 'غرف ومعروضات'),
          makeButton('custom_furniture', 'تصنيع حسب الطلب'),
          makeButton('delivery_installation', 'التوصيل والتركيب'),
          makeButton('materials_finishes', 'الخامات والتشطيبات'),
        ],
        specialties: ['غرف نوم', 'غرف معيشة', 'مكاتب', 'مطابخ', 'أثاث خارجي', 'أثاث فنادق', 'ديكور داخلي', 'تصنيع حسب الطلب', 'معارض أثاث', 'تركيب أثاث'],
      },
      {
        id: 'homeGoods',
        title: 'مستلزمات المنزل',
        description: 'أدوات منزلية، أجهزة صغيرة، تنظيم، تنظيف ومطبخ.',
        category: 'RETAIL',
        primaryModuleLabel: 'أقسام المنزل',
        secondaryModuleLabel: 'الضمان والاستبدال',
        privateButtons: [
          makeButton('home_sections', 'أقسام المنزل'),
          makeButton('warranty', 'الضمان والاستبدال'),
          makeButton('kitchen_tools', 'أدوات المطبخ'),
          makeButton('cleaning_tools', 'أدوات التنظيف'),
        ],
        specialties: ['أدوات مطبخ', 'أواني', 'تنظيف', 'تنظيم', 'أجهزة صغيرة', 'إكسسوارات منزل', 'ديكورات', 'حمام', 'مستلزمات أطفال', 'منظمات'],
      },
    ],
  },
  {
    id: 'jewelry_luxury',
    title: 'دهب ومجوهرات وساعات وهدايا',
    description: 'محلات دهب، فضة، مجوهرات، ساعات، إكسسوارات فاخرة، هدايا وتغليف.',
    icon: 'د',
    category: 'RETAIL',
    activities: [
      {
        id: 'goldJewelry',
        title: 'محلات دهب ومجوهرات',
        description: 'ذهب، ألماس، أطقم، سبائك، عيارات، مصنعية، صيانة وتلميع.',
        category: 'RETAIL',
        primaryModuleLabel: 'المشغولات والعيارات',
        secondaryModuleLabel: 'المصنعية والخدمات',
        privateButtons: [
          makeButton('karats_pricing', 'العيارات وسعر الجرام'),
          makeButton('craftsmanship', 'المصنعية والتلميع'),
          makeButton('custom_design', 'تصميم حسب الطلب'),
          makeButton('buyback_tradein', 'الشراء والاستبدال'),
        ],
        specialties: ['ذهب عيار 21', 'ذهب عيار 18', 'ذهب عيار 24', 'ألماس', 'أطقم زفاف', 'سبائك', 'مشغولات يدوية', 'تلميع وصيانة', 'إكسسوارات ذهب', 'غوايش'],
      },
      {
        id: 'silverAccessories',
        title: 'فضة وإكسسوارات',
        description: 'فضة، إكسسوارات، أحجار كريمة، سلاسل، خواتم وتصاميم.',
        category: 'RETAIL',
        primaryModuleLabel: 'الإكسسوارات والتصاميم',
        secondaryModuleLabel: 'الأحجار والصيانة',
        privateButtons: [
          makeButton('silver_types', 'أنواع الفضة'),
          makeButton('gemstones', 'الأحجار الكريمة'),
          makeButton('custom_pieces', 'تصاميم حسب الطلب'),
          makeButton('cleaning_repair', 'تنظيف وصيانة'),
        ],
        specialties: ['فضة 925', 'سلاسل', 'خواتم', 'أقراط', 'أساور', 'أحجار كريمة', 'إكسسوارات رجالي', 'إكسسوارات حريمي', 'تيشيرتات فضية', 'تحف فضية'],
      },
      {
        id: 'watchesGifts',
        title: 'ساعات وهدايا فاخرة',
        description: 'ساعات، هدايا، تغليف، بطاريات، صيانة وضمان.',
        category: 'RETAIL',
        primaryModuleLabel: 'الساعات والماركات',
        secondaryModuleLabel: 'الهدايا والتغليف',
        privateButtons: [
          makeButton('watch_brands', 'ماركات الساعات'),
          makeButton('battery_repair', 'بطاريات وصيانة'),
          makeButton('gift_wrapping', 'تغليف هدايا'),
          makeButton('warranty_service', 'خدمات الضمان'),
        ],
        specialties: ['ساعات رجالي', 'ساعات حريمي', 'ساعات أطفال', 'ساعات ذكية', 'ساعات كلاسيك', 'هدايا', 'تغليف', 'إكسسوارات ساعات', 'صيانة ساعات', 'بطاريات'],
      },
    ],
  },
  {
    id: 'real_estate',
    title: 'عقارات وأراضي ومقاولات',
    description: 'عقارات، أراضي، مقاولات، تشطيبات، مواد بناء وأدوات.',
    icon: 'ع',
    category: 'RETAIL',
    activities: [
      {
        id: 'realEstate',
        title: 'عقارات بيع وإيجار',
        description: 'شقق، فيلات، محلات، إيجار، بيع، إدارة عقارات.',
        category: 'RETAIL',
        primaryModuleLabel: 'العقارات والوحدات',
        secondaryModuleLabel: 'البيع والإيجار',
        privateButtons: [
          makeButton('property_listings', 'قائمة العقارات'),
          makeButton('rental_contracts', 'عقود الإيجار'),
          makeButton('property_management', 'إدارة العقارات'),
          makeButton('virtual_tours', 'جولات افتراضية'),
        ],
        specialties: ['شقق', 'فيلات', 'محلات', 'أراضي', 'عمارات', 'إيجار', 'بيع', 'إدارة عقارات', 'تأجير مفروش', 'عقارات تجارية'],
      },
      {
        id: 'lands',
        title: 'أراضي وبيع وشراء',
        description: 'أراضي زراعية، سكنية، تجارية، تقسيمات وبيع وشراء.',
        category: 'RETAIL',
        primaryModuleLabel: 'الأراضي والقطع',
        secondaryModuleLabel: 'البيع والشراء',
        privateButtons: [
          makeButton('land_listings', 'قائمة الأراضي'),
          makeButton('land_divisions', 'التقسيمات'),
          makeButton('land_surveying', 'المساحة'),
          makeButton('land_investment', 'استثمار أراضي'),
        ],
        specialties: ['أراضي زراعية', 'أراضي سكنية', 'أراضي تجارية', 'أراضي صناعية', 'تقسيمات', 'استثمار', 'مزارع', 'استراحات', 'بركسات', 'أراضي بناء'],
      },
      {
        id: 'contractors',
        title: 'مقاولات وتشطيبات',
        description: 'مقاولات، تشطيبات، ترميمات، أعمال جبس، دهانات وسباكة.',
        category: 'SERVICE',
        primaryModuleLabel: 'المقاولات والمشاريع',
        secondaryModuleLabel: 'التشطيبات والترميم',
        privateButtons: [
          makeButton('projects', 'المشاريع'),
          makeButton('finishing', 'التشطيبات'),
          makeButton('renovation', 'الترميمات'),
          makeButton('materials', 'الخامات'),
        ],
        specialties: ['مقاولات عامة', 'تشطيبات', 'دهانات', 'جبس', 'سباكة', 'كهرباء', 'سيراميك', 'باركيه', 'ترميمات', 'تشطيب سوبر لوكس'],
      },
      {
        id: 'building_supplies',
        title: 'مواد بناء وأدوات',
        description: 'أسمنت، طوب، حديد، خشب، أدوات بناء، سباكة وكهرباء.',
        category: 'RETAIL',
        primaryModuleLabel: 'مواد البناء',
        secondaryModuleLabel: 'الأدوات والإكسسوارات',
        privateButtons: [
          makeButton('cement_blocks', 'أسمنت وطوب'),
          makeButton('steel_iron', 'حديد تسليح'),
          makeButton('wood_panels', 'أخشاب وألواح'),
          makeButton('tools', 'أدوات بناء'),
        ],
        specialties: ['أسمنت', 'طوب', 'حديد', 'خشب', 'أدوات', 'سباكة', 'كهرباء', 'دهانات', 'سيراميك', 'مواد عزل'],
      },
    ],
  },
  {
    id: 'vehicles',
    title: 'سيارات وورش وقطع غيار',
    description: 'معارض سيارات، ورش صيانة، قطع غيار، إكسسوارات وخدمات.',
    icon: 'س',
    category: 'RETAIL',
    activities: [
      {
        id: 'carShowroom',
        title: 'معارض سيارات',
        description: 'بيع وشراء سيارات، تقسيط، تبديل، ضمان وتمويل.',
        category: 'RETAIL',
        primaryModuleLabel: 'السيارات والمعروضات',
        secondaryModuleLabel: 'البيع والتمويل',
        privateButtons: [
          makeButton('car_listings', 'قائمة السيارات'),
          makeButton('financing', 'التقسيط والتمويل'),
          makeButton('trade_in', 'التبديل'),
          makeButton('warranty', 'الضمان'),
        ],
        specialties: ['سيارات جديدة', 'سيارات مستعملة', 'تقسيط', 'تبديل', 'تمويل', 'ضمان', 'إكسسوارات سيارات', 'تأمين', 'فحص فني', 'نقل ملكية'],
      },
      {
        id: 'auto_services',
        title: 'ورشة وصيانة سيارات',
        description: 'صيانة، زيت، فلاتر، تيل، بطاريات، كمبيوتر وتكييف.',
        category: 'SERVICE',
        primaryModuleLabel: 'الصيانة والخدمات',
        secondaryModuleLabel: 'البطاريات والكمبيوتر',
        privateButtons: [
          makeButton('maintenance', 'الصيانة الدورية'),
          makeButton('oil_filters', 'زيت وفلاتر'),
          makeButton('brakes_battery', 'تيل وبطاريات'),
          makeButton('diagnostics', 'فحص كمبيوتر'),
        ],
        specialties: ['صيانة عامة', 'زيت وفلاتر', 'تيل فرامل', 'بطاريات', 'تكييف سيارات', 'كمبيوتر سيارات', 'كهرباء سيارات', 'سمكرة ودهان', 'عفشة', 'موتور'],
      },
      {
        id: 'auto_parts',
        title: 'قطع غيار سيارات',
        description: 'قطع غيار، فلاتر، زيت، تيل، بطاريات وإكسسوارات.',
        category: 'RETAIL',
        primaryModuleLabel: 'قطع الغيار',
        secondaryModuleLabel: 'الفلاتر والزيوت',
        privateButtons: [
          makeButton('parts_catalog', 'كتالوج القطع'),
          makeButton('filters_oil', 'فلاتر وزيوت'),
          makeButton('brakes_battery', 'تيل وبطاريات'),
          makeButton('accessories', 'إكسسوارات'),
        ],
        specialties: ['قطع غيار', 'فلاتر', 'زيوت', 'تيل', 'بطاريات', 'إكسسوارات', 'كاوتش', 'شمعات', 'بوجيهات', 'حساسات'],
      },
    ],
  },
  {
    id: 'agriculture',
    title: 'زراعة وثروة حيوانية وسمكية',
    description: 'مستلزمات زراعية، مشاتل، ثروة حيوانية، ثروة سمكية وطاقة.',
    icon: 'ز',
    category: 'RETAIL',
    activities: [
      {
        id: 'agri_supplies',
        title: 'مستلزمات زراعية',
        description: 'بذور، أسمدة، مبيدات، أدوات زراعية وحصاد.',
        category: 'RETAIL',
        primaryModuleLabel: 'المستلزمات الزراعية',
        secondaryModuleLabel: 'الأدوات والحصاد',
        privateButtons: [
          makeButton('seeds', 'البذور'),
          makeButton('fertilizers', 'الأسمدة'),
          makeButton('pesticides', 'المبيدات'),
          makeButton('tools', 'الأدوات الزراعية'),
        ],
        specialties: ['بذور', 'أسمدة', 'مبيدات', 'أدوات', 'حصاد', 'ري', 'صوبات', 'تقاوي', 'مبيدات حشرية', 'مبيدات فطرية'],
      },
      {
        id: 'nurseries_landscaping',
        title: 'مشتل وتنسيق حدائق',
        description: 'مشتل، نباتات، تنسيق حدائق، أشجار، ورود وري.',
        category: 'SERVICE',
        primaryModuleLabel: 'النباتات والأشجار',
        secondaryModuleLabel: 'التنسيق والري',
        privateButtons: [
          makeButton('plants', 'النباتات'),
          makeButton('landscaping', 'تنسيق حدائق'),
          makeButton('irrigation', 'أنظمة الري'),
          makeButton('maintenance', 'الصيانة'),
        ],
        specialties: ['نباتات زينة', 'أشجار', 'ورود', 'تنسيق', 'ري', 'صيانة حدائق', 'عشب صناعي', 'نباتات داخلية', 'بوكيهات', 'تحويطات'],
      },
      {
        id: 'livestock',
        title: 'ثروة حيوانية',
        description: 'ماشية، أغنام، دواجن، أعلاف، بيطرية وخدمات.',
        category: 'RETAIL',
        primaryModuleLabel: 'الماشية والأعلاف',
        secondaryModuleLabel: 'الخدمات البيطرية',
        privateButtons: [
          makeButton('livestock', 'الماشية'),
          makeButton('feed', 'الأعلاف'),
          makeButton('veterinary', 'الخدمات البيطرية'),
          makeButton('equipment', 'المعدات'),
        ],
        specialties: ['ماشية', 'أغنام', 'دواجن', 'أعلاف', 'بيطرة', 'حظائر', 'مناحل', 'أرانب', 'حمام', 'مزارع'],
      },
      {
        id: 'fisheries',
        title: 'ثروة سمكية',
        description: 'أسماك، مزارع سمكية، شباك، قوارب، ثلج وتعبئة.',
        category: 'RETAIL',
        primaryModuleLabel: 'الأسماك والمزارع',
        secondaryModuleLabel: 'الشباك والمعدات',
        privateButtons: [
          makeButton('fish_farms', 'مزارع سمكية'),
          makeButton('nets', 'الشباك'),
          makeButton('boats', 'القوارب'),
          makeButton('packing', 'التعبئة والثلج'),
        ],
        specialties: ['أسماك طازجة', 'مزارع سمكية', 'شباك', 'قوارب', 'ثلج', 'تعبئة', 'روبيان', 'كافيار', 'تونة', 'أسماك بحر'],
      },
      {
        id: 'energy',
        title: 'طاقة ومحطات',
        description: 'طاقة شمسية، طاقة رياح، محطات، بطاريات وخدمات.',
        category: 'SERVICE',
        primaryModuleLabel: 'الطاقة والمحطات',
        secondaryModuleLabel: 'البطاريات والخدمات',
        privateButtons: [
          makeButton('solar', 'طاقة شمسية'),
          makeButton('wind', 'طاقة رياح'),
          makeButton('batteries', 'بطاريات'),
          makeButton('maintenance', 'صيانة'),
        ],
        specialties: ['طاقة شمسية', 'طاقة رياح', 'محطات', 'بطاريات', 'صيانة', 'تركيب', 'ألواح', 'إنفرتر', 'كابلات', 'تأريض'],
      },
    ],
  },
  {
    id: 'services',
    title: 'خدمات وشركات وورش',
    description: 'شركات خدمات، فنيين، ورش، خدمات مهنية وخدمات منزلية.',
    icon: 'خ',
    category: 'SERVICE',
    activities: [
      {
        id: 'serviceCompanies',
        title: 'شركات خدمات',
        description: 'شركات خدمات، تنظيف، صيانة، أمن، نقل وتخزين.',
        category: 'SERVICE',
        primaryModuleLabel: 'الخدمات والعقود',
        secondaryModuleLabel: 'الموظفون والمعدات',
        privateButtons: [
          makeButton('services', 'الخدمات'),
          makeButton('contracts', 'العقود'),
          makeButton('staff', 'الموظفون'),
          makeButton('equipment', 'المعدات'),
        ],
        specialties: ['تنظيف', 'صيانة', 'أمن', 'نقل', 'تخزين', 'شحن', 'خدمات مكتبية', 'استشارات', 'تدريب', 'إدارة'],
      },
      {
        id: 'individualTechnicians',
        title: 'فنيين مستقلين',
        description: 'فنيين، صنايعية، محترفين، خدمات منزلية وورش.',
        category: 'SERVICE',
        primaryModuleLabel: 'الخدمات الفنية',
        secondaryModuleLabel: 'الأدوات والمعدات',
        privateButtons: [
          makeButton('services', 'الخدمات'),
          makeButton('tools', 'الأدوات'),
          makeButton('booking', 'الحجوزات'),
          makeButton('reviews', 'التقييمات'),
        ],
        specialties: ['كهربائي', 'سباك', 'نجار', 'حداد', 'دهان', 'تكييف', 'تبريد', 'صيانة أجهزة', 'صيانة موبايل', 'تركيب'],
      },
      {
        id: 'workshops',
        title: 'ورش صناعية',
        description: 'ورش تصنيع، إنتاج، تشغيل، صيانة وخدمات.',
        category: 'SERVICE',
        primaryModuleLabel: 'المنتجات والتصنيع',
        secondaryModuleLabel: 'التشغيل والصيانة',
        privateButtons: [
          makeButton('production', 'التصنيع'),
          makeButton('machines', 'الماكينات'),
          makeButton('maintenance', 'الصيانة'),
          makeButton('orders', 'الطلبات'),
        ],
        specialties: ['تصنيع', 'إنتاج', 'تشغيل', 'صيانة', 'ماكينات', 'مصنع', 'ورشة', 'حديد', 'ألمنيوم', 'بلاستيك'],
      },
    ],
  },
  {
    id: 'electronics_health',
    title: 'إلكترونيات وصحة',
    description: 'كمبيوترات، موبايلات، إلكترونيات، صيدلية، مستحضرات وصحة.',
    icon: 'إ',
    category: 'RETAIL',
    activities: [
      {
        id: 'electronics',
        title: 'كمبيوترات وموبايلات',
        description: 'موبايلات، لابتوب، إكسسوارات، صيانة، شاشات وضمان.',
        category: 'RETAIL',
        primaryModuleLabel: 'المنتجات والإكسسوارات',
        secondaryModuleLabel: 'الصيانة والضمان',
        privateButtons: [
          makeButton('phones', 'موبايلات'),
          makeButton('laptops', 'لابتوب'),
          makeButton('accessories', 'إكسسوارات'),
          makeButton('repair', 'صيانة'),
        ],
        specialties: ['موبايلات', 'لابتوب', 'تابلت', 'شاشات', 'إكسسوارات', 'شواحن', 'سماعات', 'كابلات', 'صيانة', 'ضمان'],
      },
      {
        id: 'health',
        title: 'صيدلية / مستحضرات',
        description: 'أدوية، مستحضرات، عناية، طبية، أدوات ومعدات.',
        category: 'RETAIL',
        primaryModuleLabel: 'الأدوية والمستحضرات',
        secondaryModuleLabel: 'الأدوات الطبية',
        privateButtons: [
          makeButton('medicines', 'الأدوية'),
          makeButton('cosmetics', 'المستحضرات'),
          makeButton('medical_tools', 'الأدوات الطبية'),
          makeButton('supplies', 'المستلزمات'),
        ],
        specialties: ['أدوية', 'مستحضرات تجميل', 'عناية', 'طبية', 'أدوات', 'مستلزمات', 'مكملات', 'عطور', 'أعشاب', 'مستحضرات أطفال'],
      },
    ],
  },
  {
    id: 'bookings',
    title: 'حجوزات ومواعيد',
    description: 'صالونات، عيادات، رياضة، تذاكر وخدمات بالحجز.',
    icon: 'ح',
    category: 'SERVICE',
    activities: [
      {
        id: 'bookings',
        title: 'حجوزات ومواعيد',
        description: 'صالونات، عيادات، رياضة، تذاكر وخدمات بالحجز.',
        category: 'SERVICE',
        primaryModuleLabel: 'الحجوزات',
        secondaryModuleLabel: 'المواعيد',
        privateButtons: [
          makeButton('salon_barber', 'صالون وحلاقة'),
          makeButton('clinic', 'عيادة'),
          makeButton('gym', 'جيم'),
          makeButton('tickets', 'تذاكر'),
        ],
        specialties: ['صالون', 'حلاقة', 'عيادة', 'جيم', 'تذاكر', 'سبا', 'مساج', 'تجميل', 'أسنان', 'جلدية'],
      },
    ],
  },
  {
    id: 'factories',
    title: 'مصانع وإنتاج',
    description: 'مصانع، إنتاج، تشغيل، خامات، منتجات وخدمات.',
    icon: 'م',
    category: 'RETAIL',
    activities: [
      {
        id: 'factories',
        title: 'مصانع وإنتاج',
        description: 'مصانع، إنتاج، تشغيل، خامات، منتجات وخدمات.',
        category: 'RETAIL',
        primaryModuleLabel: 'المنتجات والإنتاج',
        secondaryModuleLabel: 'الخامات والتشغيل',
        privateButtons: [
          makeButton('production', 'الإنتاج'),
          makeButton('materials', 'الخامات'),
          makeButton('machines', 'الماكينات'),
          makeButton('orders', 'الطلبات'),
        ],
        specialties: ['مصنع', 'إنتاج', 'تشغيل', 'خامات', 'منتجات', 'ماكينات', 'حديد', 'بلاستيك', 'ألمنيوم', 'تغليف'],
      },
    ],
  },
  {
    id: 'trade_companies',
    title: 'شركات تجارية',
    description: 'شركات تجارية، استيراد، تصدير، توزيع وخدمات.',
    icon: 'ت',
    category: 'RETAIL',
    activities: [
      {
        id: 'tradeCompanies',
        title: 'شركات تجارية',
        description: 'شركات تجارية، استيراد، تصدير، توزيع وخدمات.',
        category: 'RETAIL',
        primaryModuleLabel: 'المنتجات والتجارة',
        secondaryModuleLabel: 'الاستيراد والتصدير',
        privateButtons: [
          makeButton('products', 'المنتجات'),
          makeButton('import_export', 'استيراد وتصدير'),
          makeButton('distribution', 'التوزيع'),
          makeButton('contracts', 'العقود'),
        ],
        specialties: ['استيراد', 'تصدير', 'توزيع', 'تجارة', 'عقود', 'شحن', 'تخليص', 'وكلاء', 'توريدات', 'جملة'],
      },
    ],
  },
  {
    id: 'tourism_travel',
    title: 'سياحة وسفر',
    description: 'سياحة، سفر، فنادق، رحلات، تذاكر وخدمات.',
    icon: 'س',
    category: 'SERVICE',
    activities: [
      {
        id: 'tourismTravel',
        title: 'سياحة وسفر',
        description: 'سياحة، سفر، فنادق، رحلات، تذاكر وخدمات.',
        category: 'SERVICE',
        primaryModuleLabel: 'الرحلات والفنادق',
        secondaryModuleLabel: 'التذاكر والخدمات',
        privateButtons: [
          makeButton('tours', 'الرحلات'),
          makeButton('hotels', 'الفنادق'),
          makeButton('tickets', 'التذاكر'),
          makeButton('visa', 'تأشيرات'),
        ],
        specialties: ['رحلات', 'فنادق', 'تذاكر', 'طيران', 'تأشيرات', 'عمرة', 'حج', 'مناسك', 'تأمين سفر', 'تأجير سيارات'],
      },
    ],
  },
  {
    id: 'professional_services',
    title: 'خدمات مهنية',
    description: 'خدمات مهنية، استشارات، محاماة، محاسبة، تدريب وخدمات.',
    icon: 'ه',
    category: 'SERVICE',
    activities: [
      {
        id: 'professionalServices',
        title: 'خدمات مهنية',
        description: 'خدمات مهنية، استشارات، محاماة، محاسبة، تدريب وخدمات.',
        category: 'SERVICE',
        primaryModuleLabel: 'الخدمات المهنية',
        secondaryModuleLabel: 'الاستشارات',
        privateButtons: [
          makeButton('consulting', 'استشارات'),
          makeButton('legal', 'قانوني'),
          makeButton('accounting', 'محاسبة'),
          makeButton('training', 'تدريب'),
        ],
        specialties: ['استشارات', 'محاماة', 'محاسبة', 'تدريب', 'تسويق', 'إدارة', 'قانوني', 'مالي', 'ضرائب', 'تأسيس شركات'],
      },
    ],
  },
  {
    id: 'home_services',
    title: 'خدمات منزلية',
    description: 'خدمات منزلية، تنظيف، صيانة، طبخ، رعاية وخدمات.',
    icon: 'م',
    category: 'SERVICE',
    activities: [
      {
        id: 'homeServices',
        title: 'خدمات منزلية',
        description: 'خدمات منزلية، تنظيف، صيانة، طبخ، رعاية وخدمات.',
        category: 'SERVICE',
        primaryModuleLabel: 'الخدمات المنزلية',
        secondaryModuleLabel: 'الصيانة والرعاية',
        privateButtons: [
          makeButton('cleaning', 'تنظيف'),
          makeButton('maintenance', 'صيانة'),
          makeButton('cooking', 'طبخ'),
          makeButton('care', 'رعاية'),
        ],
        specialties: ['تنظيف', 'صيانة', 'طبخ', 'رعاية', 'تركيب', 'صيانة أجهزة', 'تنظيف منازل', 'تنظيف مكاتب', 'رعاية أطفال', 'رعاية مسنين'],
      },
    ],
  },
  {
    id: 'other',
    title: 'أخرى',
    description: 'أنشطة أخرى غير مصنفة.',
    icon: 'أ',
    category: 'RETAIL',
    activities: [
      {
        id: 'other',
        title: 'أخرى',
        description: 'أنشطة أخرى غير مصنفة.',
        category: 'RETAIL',
        primaryModuleLabel: 'المنتجات',
        secondaryModuleLabel: 'الخدمات',
        privateButtons: [],
        specialties: [],
      },
    ],
  },
];

export const BUSINESS_ACTIVITIES = BUSINESS_ACTIVITY_GROUPS.flatMap((group) =>
  group.activities.map((activity) => ({ ...activity, groupId: group.id, groupTitle: group.title })),
);

export type ActivityWithGroup = (typeof BUSINESS_ACTIVITIES)[number];

export const groupAccentColors: Record<string, string> = {
  food_market: 'from-orange-600 to-amber-500',
  fashion_home: 'from-pink-600 to-rose-400',
  jewelry_luxury: 'from-yellow-600 to-amber-400',
  real_estate: 'from-emerald-600 to-teal-500',
  vehicles: 'from-red-600 to-orange-500',
  agriculture: 'from-green-600 to-lime-500',
  services: 'from-cyan-600 to-blue-500',
  electronics_health: 'from-blue-600 to-indigo-500',
  bookings: 'from-sky-600 to-cyan-500',
  other: 'from-slate-600 to-slate-400',
};
