import { Megaphone } from 'lucide-react';
import type { ModuleDef } from '../../types';

export const marketingModule: ModuleDef = {
  id: 'marketing',
  name: 'Marketing & Promotions',
  nameKey: 'modules.marketing.name',
  nameAr: 'التسويق والعروض',
  description: 'Promotions, discount campaigns, marketing tools, and abandoned cart recovery.',
  descriptionKey: 'modules.marketing.description',
  descriptionAr: 'عروض، حملات خصم، أدوات تسويق، واسترداد السلات المتروكة.',
  icon: Megaphone,
  category: 'growth',
  color: '#EA580C',
  dependencies: ['core'],
  features: [
    { id: 'promotions', label: 'Promotions', labelAr: 'العروض', defaultEnabled: true },
    { id: 'marketing', label: 'Marketing Center', labelAr: 'مركز التسويق', defaultEnabled: true },
    { id: 'campaigns', label: 'Campaigns', labelAr: 'الحملات', defaultEnabled: false },
    { id: 'coupons', label: 'Coupons', labelAr: 'الكوبونات', defaultEnabled: false },
    { id: 'discounts', label: 'Discounts', labelAr: 'الخصومات', defaultEnabled: false },
    { id: 'messages', label: 'Messages', labelAr: 'الرسائل', defaultEnabled: false },
    { id: 'emailCampaigns', label: 'Email Campaigns', labelAr: 'البريد الإلكتروني', defaultEnabled: false },
    { id: 'pushNotifications', label: 'Push Notifications', labelAr: 'الإشعارات الفورية', defaultEnabled: false },
    { id: 'smsCampaigns', label: 'SMS Campaigns', labelAr: 'حملات الرسائل النصية', defaultEnabled: false },
    { id: 'loyaltyPrograms', label: 'Loyalty Programs', labelAr: 'برامج الولاء', defaultEnabled: false },
    { id: 'seasonalOffers', label: 'Seasonal Offers', labelAr: 'العروض الموسمية', defaultEnabled: false },
  ],
  pages: [
    { id: 'promotions', label: 'Promotions', route: '/business/dashboard?tab=promotions', tabId: 'promotions', existing: true },
    { id: 'marketing', label: 'Marketing Center', route: '/business/dashboard?tab=marketing', tabId: 'marketing', existing: true },
    { id: 'campaigns', label: 'Campaigns', route: '/business/dashboard?tab=campaigns', tabId: 'campaigns' },
    { id: 'coupons', label: 'Coupons', route: '/business/dashboard?tab=coupons', tabId: 'coupons' },
    { id: 'discounts', label: 'Discounts', route: '/business/dashboard?tab=discounts', tabId: 'discounts' },
    { id: 'messages', label: 'Messages', route: '/business/dashboard?tab=messages', tabId: 'messages' },
    { id: 'emailCampaigns', label: 'Email Campaigns', route: '/business/dashboard?tab=emailCampaigns', tabId: 'emailCampaigns' },
    { id: 'pushNotifications', label: 'Push Notifications', route: '/business/dashboard?tab=pushNotifications', tabId: 'pushNotifications' },
    { id: 'smsCampaigns', label: 'SMS Campaigns', route: '/business/dashboard?tab=smsCampaigns', tabId: 'smsCampaigns' },
    { id: 'loyaltyPrograms', label: 'Loyalty Programs', route: '/business/dashboard?tab=loyaltyPrograms', tabId: 'loyaltyPrograms' },
    { id: 'seasonalOffers', label: 'Seasonal Offers', route: '/business/dashboard?tab=seasonalOffers', tabId: 'seasonalOffers' },
  ],
  navigation: [
    {
      id: 'marketing',
      title: 'Marketing',
      titleKey: 'dashboard.sections.marketing',
      order: 35,
      items: [
        { id: 'promotions', label: 'Promotions', labelKey: 'business.dashboardTabs.promotions', route: '/business/dashboard?tab=promotions', tabId: 'promotions', icon: 'Megaphone', order: 0 },
        { id: 'marketing', label: 'Marketing Center', labelKey: 'business.dashboardTabs.marketing', route: '/business/dashboard?tab=marketing', tabId: 'marketing', icon: 'Megaphone', order: 1 },
        { id: 'campaigns', label: 'Campaigns', labelKey: 'business.dashboardTabs.campaigns', route: '/business/dashboard?tab=campaigns', tabId: 'campaigns', icon: 'Megaphone', order: 2 },
        { id: 'coupons', label: 'Coupons', labelKey: 'business.dashboardTabs.coupons', route: '/business/dashboard?tab=coupons', tabId: 'coupons', icon: 'Ticket', order: 3 },
        { id: 'discounts', label: 'Discounts', labelKey: 'business.dashboardTabs.discounts', route: '/business/dashboard?tab=discounts', tabId: 'discounts', icon: 'Percent', order: 4 },
        { id: 'messages', label: 'Messages', labelKey: 'business.dashboardTabs.messages', route: '/business/dashboard?tab=messages', tabId: 'messages', icon: 'MessageSquare', order: 5 },
        { id: 'emailCampaigns', label: 'Email Campaigns', labelKey: 'business.dashboardTabs.emailCampaigns', route: '/business/dashboard?tab=emailCampaigns', tabId: 'emailCampaigns', icon: 'Mail', order: 6 },
        { id: 'pushNotifications', label: 'Push Notifications', labelKey: 'business.dashboardTabs.pushNotifications', route: '/business/dashboard?tab=pushNotifications', tabId: 'pushNotifications', icon: 'Smartphone', order: 7 },
        { id: 'smsCampaigns', label: 'SMS Campaigns', labelKey: 'business.dashboardTabs.smsCampaigns', route: '/business/dashboard?tab=smsCampaigns', tabId: 'smsCampaigns', icon: 'Smartphone', order: 8 },
        { id: 'loyaltyPrograms', label: 'Loyalty Programs', labelKey: 'business.dashboardTabs.loyaltyPrograms', route: '/business/dashboard?tab=loyaltyPrograms', tabId: 'loyaltyPrograms', icon: 'Gift', order: 9 },
        { id: 'seasonalOffers', label: 'Seasonal Offers', labelKey: 'business.dashboardTabs.seasonalOffers', route: '/business/dashboard?tab=seasonalOffers', tabId: 'seasonalOffers', icon: 'Star', order: 10 },
      ],
    },
  ],
  dashboardWidgets: [
    { id: 'active_promotions', label: 'Active Promotions', labelKey: 'modules.marketing.widgetPromotions', component: 'ActivePromotions', order: 10, size: 'medium' },
  ],
  permissions: [
    { id: 'marketing.view', label: 'View Promotions' },
    { id: 'marketing.manage', label: 'Manage Promotions' },
  ],
  settingsSections: [
    { id: 'marketing', label: 'Marketing Settings', labelKey: 'dashboard.settings.marketing' },
  ],
  defaultEnabled: true,
  optional: true,
  estimatedSetupMinutes: 5,
};
